### ISSUE TITLE
Wacom Intuos El Capitan

### ISSUE THREAD

**Issue by wordgroove** [pencil2d/pencil#345] opened 2015-11-15 07:14 UTC
Pencil has a issue with a lag when you use a wacom Intuos tablet pen and mac OS El Capitan.. It is the similar problem that Manga Studio ex and Artrage had. Artrage has released a new version with the tablet pen lag. When you draw with the mouse it is fine but drawing with the tablet there is a unusable lag

I have just discovered pencil and am very excited to use it, but with the pen lag it is not useable at the current time.. Hopefully some can fix it soon ... thanks Taz

**Comment by feeef** [comment] 2015-11-16 12:13
Hi @wordgroove,
Thanks for your comment. Pencil is very unstable at this state but I am currently working on getting a working version of Pencil soon. I'll keep track of this bug and have a look later, when the bitmap and drawing engines will be fully corrected.
Cheers!

**Comment by scaryslender18** [comment] 2015-11-21 20:36
I'm having the same exact problem too. I've also posted about it, and It is preventing me from animating. Well, guess it's back to pencil, paper, and light box for now :-)

**Comment by feeef** [comment] 2015-11-21 21:46
Thanks for the feedback. I will investigate this as soon as I get the time. What OS are you using? I will check if this is not a known issue with QT events handling and some tablets / drivers. I see no reason in the code of Pencil that would make a tablet work well and not another. The code is just handling tablet (press / move / release) events thrown by the QT framework.

**Comment by feeef** [comment] 2015-11-21 21:56
Sorry you are saying that you are using Mac OS. I didn't get that. :) Do you see the same problem with the same hardware on other OS? I will investigate anyway.

**Comment by wordgroove** [comment] 2015-11-21 21:58
@feeef  thank you thank you thank you... I'm using a Intuos touch tablet and El Capitan on a iMac 10.1.1 artrage and Manga Studio are having same problem...folks at artrage put out a new version and fixed it... Photoshop CS5 is fine never had a problem... when do you think you might be able to get at this... working on a project and would love to integrate Pencil... no hurries just wondering... thanks again

**Comment by feeef** [comment] 2015-11-21 22:05
@wordgroove, I am working on getting a usable version of Pencil in a week or 2. However, I can't reproduce your bug so it makes it harder for me to fix that. I am using a Cintiq and a Bamboo with Pencil running on Fedora and everything works fine.
I will investigate about this problem as it should be solved anyway. If it is a problem with QT and some tablet drivers, I should find some comments about it over the internet.

**Comment by carlosgf** [comment] 2015-11-22 12:52
My too cents:

I am using Win8.1 with Huion Graphic Monitor and it is working fine in Pencil2D and ArtRage: no lag at all

I am experiencing lots of lags with Krita but this is due to its code itself (their developers are working to turn its brushes faster than photoshop as they lately claimed)

**Comment by wordgroove** [comment] 2015-11-22 23:44
@carlosgf glad all is well for you... we are on Mac not Win.....
@feeef anything i can do to help you figure this out... it still doing it bad... let me know thanks Mucho Mucho... can't wait to be able to animate in Pencil..

**Comment by carlosgf** [comment] 2015-11-23 00:12
Oops, my bad!

**Comment by CandyFace** [comment] 2015-12-05 18:13
Just to put the problem into perspective, this is how bad it works in OSX 10.11 El Capitan for me. It's literally unusable
![This is really slow]
(https://thumbs.gfycat.com/HardUnluckyAbyssiniangroundhornbill-size_restricted.gif)

**Comment by scaryslender18** [comment] 2015-12-05 19:05
I'm having the SAME exact problem, and I would appreciate it if someone
would fix the problem.

**Comment by wordgroove** [comment] 2015-12-05 19:44
@feeef yep the lag continues
But thanks to @candyface u can see how bad it is
Any solutions?

**Comment by mcsblanc** [comment] 2015-12-10 13:29
Même problème. 
Pencil+Mac+Wacom

**Comment by chchwy** [comment] 2015-12-10 14:01
I'll have a look at it this weekend.

**Comment by feeef** [comment] 2015-12-12 09:04
I have fixed some bad coding I had written in the rendering of the BackgroundWidget class I implemented to handle the canvas background separately from the actual drawing. I was setting the widget's css style in the paintEvent function, which is not a good thing to do and was slowing down the rendering.

This fix is in my pull resquest so it should be in the next build.

Hopefully, it will help rendering speed on Mac as well!

**Comment by CandyFace** [comment] 2015-12-12 10:42
Awesome work feeef, unfortunately after manually grabbing your pull request and trying it out, i can say that it hasn't fixed the problem. The lag is still as bad as before.

**Comment by CandyFace** [comment] 2016-01-03 14:40
I can confirm that the commit has fixed the issue for me, maybe we should close it?

**Comment by wordgroove** [comment] 2016-01-03 19:11
There is a fix that works?
@ candyface 
Where can I download

**Comment by CandyFace** [comment] 2016-01-03 20:30
@wordgroove The newest nightly build is available at the pencil2d.org forum.
http://www.pencil2d.org/forums/topic/pencil2d-nightly-builds-2015/

**Comment by scaryslender18** [comment] 2016-01-03 20:54
The nightly build doesn't help. The problem is still there.

**Comment by CandyFace** [comment] 2016-01-03 21:01
are you sure you downloaded the latest version from google drive? the issue has been fixed for me since Pencil2D-mac-20151214. Pencil2D-mac-20151219 is the latest version, if unsure.

**Comment by scaryslender18** [comment] 2016-01-03 21:02
Yes, I am pretty sure. I downloaded the version at the top.

**Comment by CandyFace** [comment] 2016-01-03 21:03
But the version at the top is not the newest, look at the date on the file, not the order on drive.

**Comment by scaryslender18** [comment] 2016-01-03 21:20
Thanks, it wound up working. Haven't been able to use Pencil in months
because of this issue.

**Comment by scaryslender18** [comment] 2016-01-03 21:34
Several questions about the build though: Where is the eraser located, and
how does one insert a frame in-between 2 frames?

**Comment by CandyFace** [comment] 2016-01-03 23:25
The eraser? It should be available in the tools panel, or by shortcut E. the second question, hold down ctrl on the frame or select as many frames as you want to move, place the frame or frames, one spot ahead and add the frame in-between your two key frames. At least that it how i have done it so far. For further questions not related to this issue, join the forum, you might be able to get better answers there ;)

**Comment by wordgroove** [comment] 2016-01-04 02:04
Thanks @candyface
Do you know how to create a cycle
Or loop in pencil?

**Comment by feeef** [comment] 2016-01-19 15:38
@wordgroove can you confirm that this issue is fixed for you with the latest build?
Thanks!

**Comment by feeef** [comment] 2016-01-19 15:40
@CandyFace confirmed it has been fixed so I close this issue.

**Closed by feeef** 2016-01-19 15:40 UTC
Labels: bug
