### ISSUE TITLE
Software slowing after 200 frames

### ISSUE THREAD

**Issue by fudgiemuffin** [pencil2d/pencil#1031] opened 2018-07-31 19:15 UTC
Yeah, it's kinda self-explanitory. Whenever it passes 199 frames everything slows down and lags. This is really annoying because it makes animating nearly impossible.

**Comment by Jose-Moreno** [comment] 2018-07-31 20:08
@fudgiemuffin Hi. As far as  I understand Pencil2D is still looking to optimize and improve on performance. I've been told before that the program caches about ~200 frames or so before having to load new images for playback, so I would imagine this is the main reason why it lags. 

I'm not quite sure this makes animating "impossible", however we all agree that the program lacks a proper "preview" functionality for longer previews (10+ seconds) along with proxy resolution visualization (100%, 75%,50%,25%, etc), All of this has already been requested, but the team lacks enough manpower to implement it ASAP, so we'll have to wait. 

For now my only suggestion is to either work and preview smaller cuts (less than 10 seconds 240F at 24 fps), if that's feasible for your project, or export the image sequence to review the pencil test in your favorite video editor of choice.

You could also try more robust, yet free animation editors like Krita or Opentoonz to see if those incur on similar issues with playback for your system, or if it's just a Pencil2D thing and if you feel inclined, comment back here on your experience as it will help the team review how the user experience is impoverished by the lack of these features. Cheers.

**Comment by Kaikogf** [comment] 2018-08-22 03:31
I have a different experience while playing an animation with more than 200 frames

To be exact I played an animation with 10 layers and 370 frames (some of the layers had only some drawings, some were used for the background in which one frame was at the beginning and the other one at the end of the animation, etc....). 

The curious thing I noticed was that Pencil2D' speed was not constant while playing the whole animation. 
When the animation is being played across several frames from several layers, pencil2D's speed will slow down. On the other hand, Pencil2D will playback at its normal speed when the animation is at the end of it , and in my case using frames from one layer only.... 

Here is the thing: even adding several more frames to that particular layer, its speed will not be affected. 

Hope this make some sense to you since I was not fully focused of all situations around this behaviour

**Comment by Jose-Moreno** [comment] 2020-08-30 18:11
I'm closing this as a duplicate of https://github.com/pencil2d/pencil/issues/964 and also because the OP never replied with further information. While the original issue seems to be related to how frame caching works which is known to "cache" every x frames (the default is 200), this problem could also be blamed on bottleneck performance when playing back scenes with many frames (which seems to also be a factor here).

After looking into the linked issue I think we can treat this problem as both a result of the caching as well as a performance problem with complex scene files. I'll be asking for more tests in the other thread, so if someone has a similar problem please submit your own cases over there as a comment to confirm how this issue occurs in different platforms (right now it only seems to happen under Windows).

**Closed by Jose-Moreno** 2020-08-30 18:11 UTC
Labels: Duplicate, More Info
