### ISSUE TITLE
pen tool immediately switches to pencil

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#148] opened 2013-07-31 19:52 UTC
On Linux (Debian Sid 64, Qt 4.8.5) Pencil 0.5.4, select pen tool with a click as your first action and make a line. First line will be pen, but then it switches to pencil tool (pen is still highlighted in the toolbox). After switching back to pen the problem does not return until you restart the program.

If you select the pen with the P hotkey, it will be pen when you press the key, but pencil when you release it. In this case, if you draw with the pen while the hotkey is pressed, the problem will not occur when you release the key.

This seems to happen only if the pen is the first tool you use.  If you make a line with the pencil first and then switch to pen, there's no trouble. If you switch to the vector layer and then choose the pen (or choose the pen and then switch to vector layer) it sometimes doesn't happen, but usually does.

I couldn't reproduce this on Windows or in Pencil 0.5.3

**Comment by feeef** [comment] 2016-02-03 08:55
@mikshaw can you reproduce this bug on the latest nightly build? https://drive.google.com/folderview?id=0B-3xNJ86y4WsSmVUWk5rb2VkcXM&usp=sharing#list
Otherwise, we should close it.

**Comment by mikshaw** [comment] 2016-02-04 19:55
I think it had already been fixed, whether intentionally or not i don't know. I forgot about this thread =o)
I haven't been using nightly builds on linux...i just compile the latest from git.

**Comment by CandyFace** [comment] 2017-04-10 07:35
I can't reproduce this, so I'm closing the issue. it's presumably been fixed a long time ago.

**Closed by CandyFace** 2017-04-10 07:35 UTC
Labels: bug
