### ISSUE TITLE
When I export my animation as a movie it only exports the audio

### ISSUE THREAD

**Issue by DannyDamn** [pencil2d/pencil#1238] opened 2019-07-30 23:50 UTC
### Issue Summary
When I export my animation as a movie (mp4) I only get a blackscreen with my audio.

### Expected Results
My animation as mp4 with audio.

### System Information
+ Pencil2D Version: 
0.6.4 (latest)

+ Operating System:
Windows 10

+ RAM Size: 
8GB

+ Graphics Tablet:
XP-Pen Artist 22E Pro

**Comment by Jose-Moreno** [comment] 2019-07-31 00:44
@DannyDamn Hi, can you share the file you're trying to export with us? you can use this form to upload it: https://www.pencil2d.org/contribute/share.html

Also sharing a series of screenshots or a video of the process you're taking to export would help to see if there's any incorrect behavior that Windows 10 is generating when Pencil2D tries to export.

**Comment by DannyDamn** [comment] 2019-07-31 14:50
![Microsoft Edge 31 07 2019 16_49_03](https://user-images.githubusercontent.com/53487461/62222167-2f901380-b3b3-11e9-8976-0173283fc06e.png)
When I try uploading my file this happens.

**Comment by DannyDamn** [comment] 2019-07-31 15:12
https://youtu.be/_4E-lP47Aag
That is a link to how it looks like exporting my file.

**Comment by scribblemaniac** [comment] 2019-07-31 15:21
The file upload should be fixed right now. It will be down about 10 hours from now for a planned maintenance period that could be up to a day long.

**Comment by DannyDamn** [comment] 2019-07-31 15:30
It worked now! Thank you!

**Comment by DannyDamn** [comment] 2019-07-31 15:32
The Project FIle Submission worked now! 
![Microsoft Edge 31 07 2019 17_31_52](https://user-images.githubusercontent.com/53487461/62225660-2b66f480-b3b9-11e9-981e-e91d40a0431d.png)

**Comment by Jose-Moreno** [comment] 2019-07-31 20:06
@DannyDamn I'll take a look in a bit to the file itself, but meanwhile can you try exporting to the other available file formats? Try out AVI and WEBM as It may be that the default player you're using does not have the appropriate codecs to playback the MP4 with the specific code being used. It tends to happen on windows quite a bit actually.

To change the extension, press the browse button and below the name use the "Filetype" dropdown to select a different file extension.

**Comment by Jose-Moreno** [comment] 2019-10-01 01:45
@DannyDamn Hi I know it's been a while but I seriously tested this for a long time and in the end we couldn't reproduce this issue. After reflecting a bit on this after watching the video as well, I think your video player does not have the proper codecs to reproduce the MP4 H.264 video files.

Here's the file you shared in July 31st as an MP4 and it works for me without issue. 
[DannyDamn.zip](https://github.com/pencil2d/pencil/files/3674028/DannyDamn.zip)

If it still doesn't for you then please try using the free VLC Media Player and see if any Pencil2D exported video plays for you as this must be a codec issue. For now I'm closing this.

**Closed by Jose-Moreno** 2019-10-01 01:45 UTC
