### ISSUE TITLE
Timeline bar

### ISSUE THREAD

**Issue by gigigugi** [pencil2d/pencil#1482] opened 2020-10-16 19:12 UTC
when I was drawing I change the tool and the timeline bar disappear, so I need to close the program and re-open to the timelie bar reappear and when I change the tool again the bar disappear again. How can I fix it

**Comment by Jose-Moreno** [comment] 2020-10-16 23:19
@gigigugi Please download the latest development version (nightly build), this issue has already been improved https://www.pencil2d.org/download/#nightlybuild 

There are additional fixes pending but with the nightly build you should not be able to experiment this problem anymore.

**Comment by Jose-Moreno** [comment] 2020-10-16 23:21
Closing as duplicate of #1417

**Closed by Jose-Moreno** 2020-10-16 23:21 UTC
Labels: Duplicate
