### ISSUE TITLE
[BUG] stabilization function create artifacts on drawing strokes

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#677] opened 2017-05-26 23:31 UTC
### --Issue Summary--

When drawing with any tool that has pressure sensitivity, the strokes are leaving a full pressure dab at the end of the stroke.

### --Actual Results

You get lines that get a dot drawn on the last portion of the stroke

At first appears to happen randomly but it seems to be tied to the speed of the stroke being drawn as well as the stabilization feature. When you set the stabilization to level 3 (third dot) every line finishes with a full pressure dab when drawing "fast". But if you draw rather slow this does not happen.

**Note**: Other users have reported this issue as well on the [forum](http://www.pencil2d.org/forums/topic/pen-tool-leaves-an-ugly-dot-at-the-end-of-the-stroke/#post-29379)

### --Expected Results--

Drawing and making strokes at a fast speed should not prove visual artifacts.

### --Video or Image Reference--

![image](https://cloud.githubusercontent.com/assets/4912907/26515471/a399591c-4240-11e7-9198-ced1bad06144.png)

### --Steps to reproduce--

1. Open Pencil2D
2. Select Pen or Pencil tool
3. Draw fast, as if you were sketching on paper.
4. Press radial button to enable stabilization level 3
5. Draw again.

### --System Information--
+ Pencil2D Version:

Pencil2D Nightly Build May 20 2017
+ Operating System:

Windows 7 Ultimate

+ RAM Size:

+ CPU:

+ Graphics Tablet:

Wacom Intuos Pro 5
---

**Comment by CandyFace** [comment] 2017-05-27 11:41
I can't reproduce the dabbing with the Pencil tool if pressure is on, it does happen when it is off though and indeed there is still pressure too even though it's off. It happens no matter what with the pen... strange. 

I'll take a look at it.

**Comment by CandyFace** [comment] 2017-05-27 13:35
Alright I've located the problem, fix coming up asap ;)

**Comment by Jose-Moreno** [comment] 2018-11-23 05:33
This bug is back in November 13th 2018 build. The repro steps are the same (even changing the stabilizer). The computer & tablet specs are the same. This wasn't happening in October 14th 2018 build.

**Comment by scribblemaniac** [comment] 2018-11-23 08:40
Almost certainly reintroduced from #1059.

**Comment by scribblemaniac** [comment] 2018-12-04 00:30
@Jose-Moreno has helped us do some debugging work on this. Here is the most detailed log he provided from one of these reed strokes:
```
fn: setCurrentTool  call: setCursor() current tool "Eyedropper"
fn: setCurrentTool  call: setCursor() current tool "Pencil"
adjustPressure 0.447703 false
tabletPressEvent 0.447703
mousePressEvent
adjustPressure 0.468231 false
tabletMoveEvent 0.468231
mouseMoveEvent
adjustPressure 0.486804 false
tabletMoveEvent 0.486804
mouseMoveEvent
adjustPressure 0.513196 false
tabletMoveEvent 0.513196
mouseMoveEvent
adjustPressure 0.517107 false
tabletMoveEvent 0.517107
mouseMoveEvent
adjustPressure 0.521994 false
tabletMoveEvent 0.521994
mouseMoveEvent
adjustPressure 0.511241 false
tabletMoveEvent 0.511241
mouseMoveEvent
adjustPressure 0.410557 false
tabletMoveEvent 0.410557
mouseMoveEvent
adjustPressure 0.177908 false
tabletMoveEvent 0.177908
mouseMoveEvent
adjustPressure 0 false
tabletReleaseEvent 0
mouseReleaseEvent
fn: setCurrentTool  call: setCursor() current tool "Eyedropper"
fn: setCurrentTool  call: setCursor() current tool "Pencil"
```
Our current theory is that the issue is caused by the mouse events which definitely should not be there. This behavior is consistent with [this bug reported to Qt](https://bugreports.qt.io/browse/QTBUG-47007). This appears to be Windows 7 specific and fixed in Qt 5.12 which will be released in a few days. If that fails to fix the issue we will have to look into other options. These including ignoring mouse events if the tablet is active/just completed, or setting Qt::AA_SynthesizeMouseForUnhandledTabletEvents to false.

**Comment by chchwy** [comment] 2018-12-11 01:44
Will be working on this issue in the next few days.

**Comment by Jose-Moreno** [comment] 2019-02-05 09:22
@chchwy @CandyFace Ok I was testing some quick drawing and overall I think #1155 improved the drawing feel by a lot.

I incidentally found a minor issue when double clicking / tapping and moving but I don't see it as a critical issue since it is **_very_** hard to get by, but just wanted to let you know.

The issue at hand doesn't create a stroke like before but it does create a single dot with the last recorded alpha pressure. To reproduce it you have to explicitly double tap / click with the stylus a lot, it also has to be done super fast (~100ms?), almost as if you were trying to do some kind of "pointillism". 

I'll share a video later as an edit to this comment just to document it thoroughly in case there's a way to fix it completely in a future version. Thanks! :smile:

**Closed** 2019-03-03 13:03 UTC
Labels: bitmap, os:win, tablet support
