### ISSUE TITLE
I cannot draw anything

### ISSUE THREAD

**Issue by NikhilBarnwal** [pencil2d/pencil#1645] opened 2021-07-02 08:11 UTC
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by NikhilBarnwal** [comment] 2021-07-02 08:12
please set it

**Comment by Jose-Moreno** [comment] 2021-07-02 17:11
@NikhilBarnwal Hi, first of all this is the developer forum where you are meant to place tickets on confirmed issues.

We have a template for these issues that is very specific. You are assumed to fill the form sections at least to describe the problem, because developers can't know what the problem is if you don't accurately say what the problem is. 

Saying "I cannot draw anything" in the title is a statement so broad that no software developer in the world would be able to understand what's wrong with the software at first glance.

Additionally there could be problems with your mouse / graphics tablet, their driver software, your own computer specs, the way you downloaded the program or the way you opened the program.

So please, if you want help you **need** to be more specific. We have a policy of waiting for 2 weeks before closing low effort tickets so we will wait for you to describe your problem better, otherwise we will close this issue and i'll have to ask to gather your thoughts and rather post in the forum which is also active https://discuss.pencil2d.org/

**Comment by chchwy** [comment] 2021-07-14 01:12
Please provide more information otherwise this issue will be closed in 3 days.

**Comment by scribblemaniac** [comment] 2021-07-24 02:26
Closing issue due to lack of information.

**Closed by scribblemaniac** 2021-07-24 02:26 UTC
Labels: More Info
