### ISSUE TITLE
Can't save and open my projects

### ISSUE THREAD

**Issue by leleworms** [pencil2d/pencil#987] opened 2018-06-04 22:53 UTC
### --Issue Summary--
FileManager::save
strFileName = C:/Users/Gabri/OneDrive/Documentos/Animação/Os Hérois do Olimpo/O Herói Perdido/O herói perdido.pclx
strTempWorkingFolder = C:/Users/Gabri/AppData/Local/Temp/Pencil2D/O herói perdido.Y2xD/
layerCount = 3
layer[0] = Layer[id=1, name=Camada de Câmera, type=5]
layer[1] = Layer[id=3, name=Camada Bitmap, type=1]
layer[2] = Layer[id=2, name=Camada Vetorial, type=2]

Error Display
Title: Erro interno
Description: Um erro interno ocorreu. Seu arquivo pode não ter sido salvo com sucesso.

System Info
Pencil version: 0.6.1.1
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.16299
Product name: Windows 10 (10.0)

### --Expected Results--
I reinstall the program a lot of times, i use differents locations to save my projects and this error continue.

### --Video or Image Reference--
[http://prntscr.com/jqvs80](url)

### --System Information--
+ Pencil2D Version:

+ Operating System:
Windows 10

+ RAM Size:
8GB

+ Graphics Tablet:
One by Wacom

---

**Comment by chchwy** [comment] 2018-06-04 23:31
Hi @leleworms 
Sorry to hear that. Please do the following things that could probably save your work.

1. Open the folder `C:/Users/Gabri/AppData/Local/Temp/Pencil2D/O herói perdido.Y2xD/` in file explorer, if lucky you can find your work in the folder.
2. Rename your file from `xxx.pclx` to `xxx.zip` and unzip the file (yes it's actually a zip), take a look inside.
3. Upload the file to Dropbox/GoogleDrive or somewhere so then we can have a look

**Comment by leleworms** [comment] 2018-06-05 00:53
[https://drive.google.com/open?id=1T7wAX8K2qdeVs5U6-WOIJPQU2H8Racb3](url)

The .pclx have nothing inside, i put .zip and open with 7zip program but dont have any thing inside.

**Comment by chchwy** [comment] 2018-06-05 01:02
@leleworms How many frames were in the project? I can see 2 bitmap frames, is it correct?

**Comment by leleworms** [comment] 2018-06-05 01:07
@chchwy 

Yes, have two frames

**Comment by chchwy** [comment] 2018-06-05 02:44
Hi @leleworms 
Please find your pclx here:
https://www.dropbox.com/s/ap8rv9suwcc7zsx/O%20her%C3%B3i%20perdido.pclx?dl=0

And please download the latest nightly build:
https://www.pencil2d.org/download/#nightlybuild
It will give more details when failing to save the project, which can help us to find the root causes of these issues and make the file-saving more stable, appreciate it.

**Comment by Jose-Moreno** [comment] 2018-06-06 00:41
@leleworms Hey. Today a new development build was made with a fix for this problem. If you don't mind could you test it out with a disposable file and let us know if this has been fixed for you or not? Visit http://pencil2d.org/download#nightlybuild and look for the June 5th 2018 nightly build.

**Comment by leleworms** [comment] 2018-06-06 17:22
@chchwy 
@Jose-Moreno 
Thanks! i gonna try again, if the problem returns i comment here

**Comment by Jose-Moreno** [comment] 2018-07-04 20:31
@leleworms Hi, there's been a new fix implemented for the save file bug, if you can please test it and if the problem has been solved for you please let us know and close this issue:

Download the nightly build for July 3rd 2018 here:
https://www.pencil2d.org/download/#nightlybuild

**Comment by scribblemaniac** [comment] 2021-12-12 01:56
Given the lack of further information on this and how old the version is where this issue occurred, I am going to close this issue as solved. This was probably an issue with accented characters in the file or filename. I recall some issue pertaining to that was fixed a long time ago.

**Closed by scribblemaniac** 2021-12-12 01:56 UTC
Labels: Bug, File Save, File Load, No reply
