### ISSUE TITLE
File saving issue

### ISSUE THREAD

**Issue by carniworest** [pencil2d/pencil#1022] opened 2018-07-19 08:35 UTC
FileManager::save strFileName = C:/Users/Michał/Downloads/pencil2d-win32-0.6.1.1 (1)/Pencil2D/tf.pclx
strTempWorkingFolder = C:/Users/Michał/AppData/Local/Temp/Pencil2D/Default.Y2xD/
layerCount = 3
layer[0] = Layer[id=1, name=Camera Layer, type=5]
layer[1] = Layer[id=2, name=Vector Layer, type=2]
layer[2] = Layer[id=3, name=Bitmap Layer, type=1]

Error Display Title: Internal Error Description: An internal error occurred. Your file may not be saved successfully.

System Info Pencil version: 0.6.1.1
Build ABI: i386-little_endian-ilp32
Kernel: winnt 10.0.17134
Product name: Windows 10

**Comment by Jose-Moreno** [comment] 2018-07-19 16:39
@carniworest Hi, this issue has been mentioned and a fix pushed in the past. To test it out please download the latest development build a.k.a Nightly build and download any of the following files for your specific architecture

64bits: **pencil2d-win64-2018-07-17.zip**
32bits: **pencil2d-win32-2018-07-17.zip**

http://pencil2d.org/download#nightlybuild

If this solves your issue, please let us know in a comment so we can close this thread.

**Comment by Jose-Moreno** [comment] 2020-08-30 07:06
I'm closing this as a duplicate of existing issues that have more discussion or have more specific information. The problem itself was actually fixed in the past and ever since asking for the user to provide further feedback, it's been 2 years already.

To the OP, If the error continues on the newer versions please comment back and provide more feedback on this thread so we can reopen it and keep track of the issue.

**Closed by Jose-Moreno** 2020-08-30 07:06 UTC
Labels: Bug, Duplicate, File Save
