### ISSUE TITLE
Crashes when opening an animation file without the vector layer

### ISSUE THREAD

**Issue by TheSandBoxMKG** [pencil2d/pencil#952] opened 2018-04-22 03:42 UTC
### --Issue Summary--

When an animation file with the vector layer deleted is opened, the program crashes 
### --Actual Results--

The program crashes at opening animations without this particular layer
### --Expected Results--

It should load the animation file without crashing and without the vector layer
### --Video or Image Reference--

![imagen](https://user-images.githubusercontent.com/27746283/39091186-855a89ce-45c5-11e8-84c2-e5797673ab90.png)
### --Steps to reproduce--

1. Make animation
2. Delete vector layer
3. Save animation file
4. Close the program
5. Open the program
6. Open saved animation file
7. Oof
8. Program crashes without any error messages
 ### --System Information--
+ Pencil2D Version:
![imagen](https://user-images.githubusercontent.com/27746283/39091171-3ccfd77c-45c5-11e8-9cc9-dc9531078c55.png)
 + Operating System: Ubuntu 16.04 LTS
 + RAM Size: 8GB

**Comment by Jose-Moreno** [comment] 2018-04-22 03:44
@TheSandBoxMKG Hi, this is a very old issue that has been solved. Please use the latest version for Linux systems that can be run as an AppImage.

To run AppImages you have to right click on them, go to properties the to the permissions tab and toggle the "allow executable" option.

To download the latest version please go to http:/pencil2d.org/download.

**Comment by CandyFace** [comment] 2018-04-22 07:57
@TheSandBoxMKG did you install pencil2d via this command "sudo apt-get install pencil2d"
if so please use another option.

@Jose-Moreno I've noticed that installing via the apt-get downloads the old 0.5.4 version.. we should fix that since it's on our download page.

**Comment by CandyFace** [comment] 2018-04-22 11:28
Closing this since the issue is related to an old version. if this still happens in latest release, feel free to comment again and I shall reopen it.

**Closed by CandyFace** 2018-04-22 11:28 UTC

**Comment by Jose-Moreno** [comment] 2018-04-22 14:12
@CandyFace Ah I see. However the problem would be the canonical partners. I think they are the ones that determine the official repositories for the apt-get. At least for ubuntu I've always had to find a custom PPA repo for software I use but where the official repos it's not up to date with the developer repositories, so I literally have to add a ton of sources everytime before executing the apt-get command when I install ubuntu on a machine.
