### ISSUE TITLE
Need help (.pcl file copy glitch)

### ISSUE THREAD

**Issue by Bestiguy951** [pencil2d/pencil#1661] opened 2021-09-03 22:19 UTC
### Issue Summary
When i duplicate the .pcl file.It would show my layers and images being blank

### Actual Results
When i duplicated my .pcl file into 3 copies and i opened the original file the entire project had blank layers.

### Expected Results
i expected most of my files to be intact and unchanged

### Video or Image Reference
![image](https://user-images.githubusercontent.com/83618878/132069732-faea66a8-3522-436c-b1db-468799dc664a.png)
![image](https://user-images.githubusercontent.com/83618878/132069767-3501013f-ccf1-4713-9d61-b3ecd54dd5f4.png)

### Steps to reproduce
1.you make a project (add anything there on pensil2d)
2.you make copies of the same file by copy and pasting
3.you open the same project on pensil2d
4.all save data that you previously worked in is gone

### System Information
+ Pencil2D Version: Version: 0.6.6

+ Operating System:
Windows 10 (10.0)

+ RAM Size:
8.00 GB

+ Graphics Tablet:
none

**Comment by Jose-Moreno** [comment] 2021-09-03 22:48
@Bestiguy951 Hi, the problem is that you're using the PCL file format which is not only incorrectly dubbed as a legacy format, is very much used as an open project format. This means the images and resources will be located inside an associated folder of the name of the file as `fileName.data` and it's sueful when using file versioning systems to backup & keep track of files in studios. In your case the folder should be called something like `victor norf fc.data` and similar.

So what's happening is that the pcl file which is like an address book to tell Pencil2d where the resources are, might be in a different folder from the resource folder, and thus it can't find them.

If you use the **PCLX** which is instead a compressed version of the entire resources and the main logfile (the pcl file you've shown is converted to an xml file internally) then what you expect should happen; copying and pasting files will retain the project resources separately. With this format however when you open them they will be dumped to the temporary operating system folder, so if you have a program or antivirus that continuously checks and cleans this folder these files might get deleted by mistake and the same issue will happen even after you save the file (you would see blank frames), so knowing this it's up to you how you want to continue using these files but I do recommend to make an exception rule for the anvitirus / cleaner apps to avoid problems.

That said by default it should save as PCLX, but if it's not doing it for you please use **File > Save As...** to switch the type of save format that will be retained. On the other hand please look for the .data folder for your specific files before anything else, otherwise if you delete it by accident you might lose your work for real.

**Comment by scribblemaniac** [comment] 2021-09-06 03:20
As mentioned by @Jose-Moreno, the .pcl format has a corresponding .data folder paired with it. If you do not copy that with the same file name as your copied .pcl file, then it will not open properly, and it will not be properly backed up.

> Hi, the problem is that you're using the PCL file format which is not only incorrectly dubbed as a legacy format, is very much used as an open project format.

While it's not technically a legacy format, I personally discourage its use the least of which for reasons like this. The pcl file format is particular easy for users to mess up if they don't understand how it works.

I am closing this issue as everything described in the initial post is expected behavior.

**Closed by scribblemaniac** 2021-09-06 03:20 UTC
