### ISSUE TITLE
Presets can be accidentally overwritten

### ISSUE THREAD

**Issue by davidlamhauge** [pencil2d/pencil#1307] opened 2020-02-10 08:52 UTC
### Issue Summary
I work on a pilot, where I've made a scene that I use as a base for all my scenes. It has the palette I need, the start layers I need and so on.
So, when I start a new scene, I press Ctrl+N, to get a new scene. The preset dialog appears, and I choose the Default preset.
I start laying out the animation, and at some point I press Ctrl+S, to save my file.
 

### Actual Results
What happens now, is that it saves the changes to the preset file.
 

### Expected Results
What I would expect is that it asked for a filename, and I could save the file where I want it to be stored, and with the name I want to give it.
I very much like the idea that the preset is easy to update, but it should be deliberate. Maybe an extra option in the preferences?
 

### System Information
+ Pencil2D Version:
I use a nightly build from 2020-01-09, on a Win10, but I guess that this issue is OS-independent.
 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by CandyFace** [comment] 2020-02-10 16:50
This is not a bug, There are two ways to save a file, "save" via Ctrl+s which unless you haven't saved before, saves implicitly to the same file, where as "save as" via Ctrl+Shift+s always opens a dialog

**Comment by davidlamhauge** [comment] 2020-02-10 17:24
The Preset dialog is a choice you make, and I think there should be the same behavior whether you use it or not. 
This means, that the first time you press Ctrl+S, after you started a new scene by pressing Ctrl+N, you are prompted for a filename for the new scene, since you haven't saved it before.

**Comment by scribblemaniac** [comment] 2020-02-10 23:09
> This means, that the first time you press Ctrl+S, after you started a new scene by pressing Ctrl+N, you are prompted for a filename for the new scene, since you haven't saved it before.

This is exactly how the preset dialog was designed and is how it worked in my PR. The filepath was reset here so that it never overwrites the preset: https://github.com/scribblemaniac/pencil/blob/e1d828fef5726334d6ca54a18f4fe7314cffe084/app/src/mainwindow2.cpp#L1126. That line is now missing from the code, so it's not surprising that you are seeing this behaviour.

**Comment by CandyFace** [comment] 2020-03-06 22:44
Should be fixed now.

**Closed by CandyFace** 2020-03-06 22:44 UTC
