### ISSUE TITLE
copy and paste problem (chromebook)

### ISSUE THREAD

**Issue by prox237** [pencil2d/pencil#1654] opened 2021-08-05 22:06 UTC
when I copy and paste drawing it pastes a black rectangle please help.

**Comment by scribblemaniac** [comment] 2021-08-06 03:23
Your problem was already responded to here: https://discuss.pencil2d.org/t/copy-and-paste-problem/5811/2. If this does not solve your problem, you need to provide the details requested by JoseMoreno as well as which version of Pencil2D you are using.

For now I am closing this as a duplicate of #1641. If further details are provided and this ends up being a different issue, this can be reopened.

**Closed by scribblemaniac** 2021-08-06 03:23 UTC
