### ISSUE TITLE
Proposal: Deprecate version 0.5.4 and push for interstitial 0.5.5 release.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#584] opened 2016-12-17 15:23 UTC
@chchwy @gordielachance Lately I've been noticing that people are too prone to download the same old 0.5.4b version from the website, which has a plethora of bugs that have already been fixed, and some continue to report the same bugs over and over. 

I wanted to propose to you that we push the latest Nightly Build as an interstitial version download, so people can at least report bugs based on the newest code base, and not the old one which is not really that stable anymore and causes multiple issues on newer systems.

This could be something like version 0.5.5 for the moment, which we know is well in it's way to version 0.6, but not quite there. This is just to avoid duplicate bug and grief reports that continue to happen due to this older version we have on display.

To "Gordie": We could change the hyperlinks on the landing page and the download page to buttons in order to differentiate "Nightly Builds" from "recommended build"

Let me know what you think, but hopefully we can do this soon.

**Comment by CandyFace** [comment] 2017-04-09 20:41
Hmm this is a tough one because it's a problem that persists in almost any open source community. I'm usually against encouraging users to grab nightly builds, because they tend to be more unstable, even if they have plenty of fixes. They're meant to be experimental releases used by developers and users that aren't afraid of bugs.

Even if we put out a interstitial version though, it's still possible to get duplicates of same bug reports because it's still older than what we have on git. If anything, perhaps the 0.5.4 binary should just be removed, so people are forced to use nightly builds.

**Comment by Jose-Moreno** [comment] 2017-04-09 21:28
@CandyFace True. Although to be fair before I began promoting heavily the Nightly Builds, I had to explain every single time that certain bugs were fixed a long time ago. Like that bug with the red coloring where everything was red, and even I had to make a crash prevention guide just so people wouldn't barge into the forum crying over their lost data. But it still happened haha.

I didn't want to remove the build though considering the software is open you should be able to access older versions. Also there are few people who just can't use newer builds due to QT framework being incompatible their OS (MAC OSX 10.6 is no longer supported in newer QT's for example)

My main gripe with all of this is that we don't have enough "power users" that want to test the features. And we don't have enough developers to allow for continued bug testing. We are thankfully having a better pace at improving the software than previous years thanks to contributions from awesome people like your, Jakob, scribblemaniac, Francois and Matt of course.

I wish there was a way to let normal users know that although we want to improve, there's just not enough resources for us to go all out with this, so we need their support with at least regular testing and feasible feature requests.

So far I left a message on the landing page for Pencil2D.org explaining that the old dev version is deprecated, however one can still download it with a warning saying that you will get a lot of bugs that have already been fixed in newer "development" versions.

A lot of people don't read too much nowadays though :stuck_out_tongue:

**Comment by CandyFace** [comment] 2017-04-09 22:58
Alright, we're not removing the binary then, what you've written seems sufficient anyway. 

About the development, it can always get better, that's how it is with community development, it's up and down and takes time because development is not constant. To get more up to speed with what needs to be done and what's fixed, I asked chchwy today whether I could join the organisation, mainly to update and close old issues, since that too can easily scare new potential developers and or cause confusion.

It's hard to ask for "feasible" features because the average Joe won't know what's easy, hard or impossible to implement.

A small remark for the web page: "This version WILL NOT work for Windows 8+ or MAC OS X anymore." you forgot to mention which OS X version, ie. 10.9 is the last compatible :)

**Comment by Jose-Moreno** [comment] 2017-04-10 01:40
@CandyFace Ah, you're right. I didn't know at the time. So it's only compatible with 10.9 and above? I thought it was 10.7+ Would you mind to clear that up, so I can specify that? Thanks a lot for helping out, and I agree this is a community effort. 

Hopefully we just can get more people on board to help out, but I suppose that to do that we would require a dedicated organization, like a foundation or at least a dedicated group to support this software, there were conversations of that with feeef, but I suppose he's busy with his own ventures for now.

A previous Pencil developer re-surfaced recently on the forum and he raised several questions regarding Pencil2D purpose as well, and he's got some points that are worth discussing later on with everyone. If you'd like to read more on that please refer to this thread:

http://www.pencil2d.org/forums/topic/hello-again/

**Comment by CandyFace** [comment] 2017-04-10 07:25
The documentation mentions that it's from 10.9 and up now, http://doc.qt.io/qt-5/supported-platforms.html

Ah I see, I'll take a look at that thread.

**Comment by feeef** [comment] 2017-04-10 07:53
I don't consider releasing a 0.5.5 version that is based on a build that we think stable, encouraging people to get the nightly builds. It is the exact opposite, by having a very old (useless on most modern systems) release, we force the users to download the nightly builds.

We are not a big project with a lot of testers nor even many contributors so if we keep waiting for getting a full featured, well tested version before the next release, it may well never happen.

**Comment by scribblemaniac** [comment] 2017-04-10 08:04
> if we keep waiting for getting a full featured, well tested version before the next release, it may well never happen.

👍 👍

**Comment by CandyFace** [comment] 2017-04-10 08:11
So what are you suggesting @feeef, should we just slap version 0.6 on one of the upcoming releases, just for the sake of having a new release? I don't see the issue with forcing people to use a test version, when in reality, there is no stable.

**Comment by scribblemaniac** [comment] 2017-04-10 08:28
The issue is we're *not* forcing people to use use nightly builds. We're advertising a version that crashes, sucks on modern systems, and has been responsible for the corruption of many people animations as the **stable version**. What part of that sounds stable to you? If that is called stable, then why would anyone want to even try the nightly builds which are being called unstable!

I've been quite patient up until now with this whole issues, since @chchwy had [a clear plan for the v0.6 release](https://github.com/pencil2d/pencil/issues/505). But to be quite frank, very little progress has been made on this considering it has been nearly a year since that was posted. Don't get me wrong, I'm not blaming anyone for that, after all I could have done that myself if I decided to dedicate the time to finish those features. The point is, I believe we have an obligation to release a 0.6 version asap to prevent more serious user issues. The current version is far more stable, far more functional, and in my opinion contains enough changes to constitute a version bump to 0.6. After that we can make small 0.6.x patches much more frequently so that bug fixes and new features reach the users quickly and so that everyone can see that Pencil2d is under active development.

**Comment by CandyFace** [comment] 2017-04-10 09:04
The way I see: We have a nightly builds, which are on pencil2d.org advertised as possibly unstable and WIP but are placed in the top, so it's the first thing you see when you enter the website. Below we have the deprecated 0.5.4 which is not supported anymore. That alone should be enough to make people download the former and not the latter. It's not advertised as stable anymore, so there's no confusion to be made from that.

We can't prevent people from using the old and dusty build and report same issues though, unless we remove it. If users experience corruption and problems with the old and unsupported release, then we can only encourage them to use the newest release, whether that's a sudden 0.6 release or a random nightly build makes no difference to me. 

I don't feel like we have an obligation to provide new stable releases asap at all, if people want it faster, then they're welcome to contribute so we'll get there faster. Bumping the version just for the sake of it, when there's a plan, would be going against the small amount of planning the project actually has.

**Comment by feeef** [comment] 2017-04-10 09:10
@scribblemaniac, @CandyFace, here is a proposition :

The way the Kdenlive team manages to achieve such great progress with no more resources than us is pretty amazing and I propose to get inspired by them.

Every quarter, they plan to release a new version (labeled the ubuntu way - 17.04). They decide the tasks they can achieve in that short time and make sure to have them ready for the next release. It is not much on each iteration but the progress is still well visible. 

Also, before each release, they do a "Bug squashing day" where all the contributors meet on IRC and work together on fixing the maximum bugs for the next release. Of course not all bugs are fixed and if the new features can't make the next release, the release is just about this bug fixing.

I guess that we could get inspired by that?

What I propose is to freeze any feature development at this point. We organize a bug squashing day and we release a 0.6 (or 0.5.5) a week or 2 after. Just the time to check if there is any regression with our bug fixing. What do you think?

I haven't been very active on Pencil2D lately, so it is a good opportunity for me to be back! :)

**Comment by feeef** [comment] 2017-04-10 09:13
It is April right now so we could even adopt the Ubuntu style versioning by releasing the 17.04 version by the end of the month.

**Comment by CandyFace** [comment] 2017-04-10 09:26
That sounds like a good way to make visual progress, i'm in on that idea @feeef. A weekly meeting on irc wouldn't be bad either, the blender community does this and it seems to work really well.

Anyway, I've joined the IRC channel now and i'm basically always on IRC to be able to talk to.

As for bug squashing, personally i'm quite busy this week (except for today) so figuring out when to do this, that's might become an issue.

**Comment by J5lx** [comment] 2017-04-10 11:24
I personally don’t like that date-based versioning scheme. While it isn’t a bad fit for a whole distribution consisting of lots and lots of separate software packages, I think a more semantic versioning scheme is preferable for single pieces of software, i.e. 0.0.x bump means bugfix etc. and x.0.0 bump means major, potentially breaking changes. It’s not for nothing that many other projects are doing it that way, e.g. future GIMP version 3.x is coupled to switching to GTK3 (which will break plugins), likewise Krita version 3 meant switching to Qt5, and TYPO3 CMS version 8 bumped the system requirements to PHP 7.x (potentially breaking extensions) (of course it’s not *just* the cited changes, but you get the idea).

That aside, though, I agree that the proposed measures are a good thing.

**Comment by CandyFace** [comment] 2017-04-10 11:34
@J5lx Hmm I see, well we could change from date to build based naming, as I've mentioned in other thread though, the server can easily get confused and might suddenly skip build numbers but if that's not a problem, then i'm okay with changing it.

**Comment by J5lx** [comment] 2017-04-10 11:59
@CandyFace I was talking about releases, not about nightly builds. @feeef suggested adapting Ubuntus versioning scheme YY.MM and that is what I’m opposing here. When it comes to nightly builds, build time/date is by no means a bad way of marking the result.

**Comment by feeef** [comment] 2017-04-10 13:04
@J5lx , I was just proposing the versioning scheme but I am not attached to it at all so 0.5.5 or 0.6 is also good to me!
The idea what to say, lets try to make regular releases so we are forced to get things well organized. We can still define 4 releases a year with the classic versioning scheme.

**Comment by feeef** [comment] 2017-04-10 13:06
I say 4 but the date based versioning actually defines 3 releases.

**Comment by CandyFace** [comment] 2017-04-17 09:20
@Jose-Moreno 
I suspect that people still download the deprecated version, because they seemingly don't read but just look for a download link. The page is very cluttered on first sight. 

The download section could be cooked down to this basically

The Download section should look like this:
### Latest version - In Development:
Windows | Pencil2D 0.5.x 
Linux | Pencil2D 0.5.x
Mac | Pencil2D 0.5.x


### Deprecated builds:
No longer supported! Download them at your own risk. This version WILL NOT work for Windows 8+ or MAC OSX < 10.9.

Windows | Pencil2D 0.5.4 
Linux | Pencil2D 0.5.4 
Mac | Pencil2D 0.5.4 

ANCIENT:
Windows | Pencil2D 0.4.4b


### Compilation:
Follow the guides here if you want to compile Pencil2D yourself

Windows 
Linux
Mac

**Comment by Jose-Moreno** [comment] 2017-04-17 15:30
@CandyFace Will do, I like your arrangement and i'll implement it before the day's over.

The way it is now was to choke new users into downloading anything but the other version, since when you first land on the page you'll only see the first part. There has been a reduction on people trying to download the old version, but I also noticed recently that there's some youtubers and artists that STILL use the old version and they pass on this knowledge (and personal links) as people always ask them "what software are you using?".

Either way I do think it's too cluttered, In fact I wanted that when people accessed to the webpage downloads to make a giant red button popup to alert them that they should read. But I can't do that since I don't have that kind of access (take this as a lighthearted joke :stuck_out_tongue_closed_eyes: )

**Comment by Jose-Moreno** [comment] 2017-04-17 23:12
@CandyFace Alright, it's done, the main page has been updated. Next I'll see how to deal with the people on youtube and tumblr so they can upgrade their Pencil2D version unless they have older operating systems of course :roll_eyes:

**Comment by chchwy** [comment] 2017-11-15 07:55
Dear all, 
I've updated all public download pages from the shitty 0.5.4 to latest 0.6-rc.

Please check:
http://pencil2d.github.io/download/
https://www.pencil2d.org/

Then we can close this issue, cheers.

**Closed by chchwy** 2017-11-15 07:55 UTC
Labels: release

**Comment by gordielachance** [comment] 2017-11-27 06:40
WOW!
Congratulation guys !
This seems to be excellent work.  25K + downloads ??? !!!!

**Comment by chchwy** [comment] 2017-11-27 06:44
WOW @gordielachance 
Haven't hear from you for a while. Nice to have you here!!

**Comment by gordielachance** [comment] 2017-11-27 06:54
ahah - and I'm sorry for that !
A lot of stuff to do here.  While I'm here, have you got any requests regarding the website ? I'll have some time for it, probably this week...

**Comment by Jose-Moreno** [comment] 2017-11-27 07:02
@gordielachance actually @J5lx setup a discourse forum as a test and @chchwy has been improving the backup website just in case. 
We've been wondering if it would be best to redirect pencil2d.org to that site and migrate the forum database to the one so there could be more control on how people interact with the project, as well as to handle the spammers and bots on a regular basis. 
However we wanted to discuss that with you since you've been the webmaster for a long time and we consider your input is quite important on these matters. (we also have a discord server now, I sent you an invite over the forum as a private msg)
I'm sure there's a lot more to talk, but I'm fairly tired, so hopefully Matt and the rest can fill you in. Good to hear from you, hope things are going well!

**Comment by J5lx** [comment] 2017-11-27 07:37
@gordielachance Just one little thing, we moved back to #pencil2d (with only one #) as our official IRC channel (see https://github.com/pencil2d/pencil/issues/540#issuecomment-344703808), so it’d be great to have that reflected in the menu bar on the website.

Other than that, I agree with what @Jose-Moreno has said. In case you’d like to have a look at the Discourse forum I set up, go to https://pencil2d-discuss-j5lx.de/, with the second dash replaced by a dot. More details are in https://github.com/pencil2d/pencil/issues/558#issuecomment-343735142.

**Comment by scribblemaniac** [comment] 2017-11-27 08:19
@pencil2d/website-admin @gordielachance Just an idea here. It would be really nice if the content of pencil2d.org came from [our github.io site](https://pencil2d.github.io). This would allow any developer to easily update the website. We can't rely fully on github.io because it doesn't support the server side scripting necessary for forums. I think what we should be able to do is host the Discorse on a some dedicated server under a `/forums/` subdirectory, point the `pencil2d.org` domain name to that server, enable `mod_proxy` then add something like this to the .htaccess file:
```
RewriteCond %{REQUEST_URI} !^/forums/
RewriteRule ^(.*) https://pencil2d.github.io/$1 [P]
```
This should transparently redirect (i.e. without the url in the user's address bar changing) any address that is not `pencil2d.org/forums/*` to `pencil2d.github.io`. In other words, it would appear as if everything was on pencil2d.org, but really only the forums would be hosted there and everything else would be open-sourced and hosted on Github.

**Comment by J5lx** [comment] 2017-11-27 10:01
Pretty much agree here, but it’d probably be more straightforward to put the forum on a subdomain (e.g. discuss.pencil2d.org). Plus, my existing discourse setup is already nginx→nginx→rails, so adding another reverse proxy on top of it would make it kind of ridiculous.
