### ISSUE TITLE
import music

### ISSUE THREAD

**Issue by LucyLegendary89** [pencil2d/pencil#1409] opened 2020-08-02 14:45 UTC
### Issue Summary

 
when i import a sons the sons isn't play 
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment] 2020-08-02 19:50
@LucyLegendary89 Umm hi. To better be able to help you we ask users to fill in the template so we know their computer characteristics, otherwise it is impossible for us to provide accurate support.

On the other hand **this is a development forum** where you report bugs that are proven to exist. In any other case we ask our users to please use either the **discord server** or the **user forum** that you can find at http://pencil2d.org/community

With that said, please make sure you are using the download version of Pencil2D and that you are using WAV files. If you are trying out MP3 files we suggest you convert them to WAV using a free audio editor like Audacity (http://audacityteam.org)

If you try loading the WAV files and it still doesn't work, please reply back with your current **Pencil2D version** and your **operating system version** otherwise we can't help much like this.

**Comment by Kaikogf** [comment] 2020-08-05 11:56
I checked last version (v0.65) and there is in fact an issue with the sound layer.

First ISSUE: When importing an audio (File > Import > Sound...) we are asked to _create a new sound layer_. Even despite the windows Layer property shows the name of the Sound Layer (which is **Sound Layer** by default), it will add the name **Sound Layer 2**   

Second ISSUE: After importing a WAV sound correctly, hitting play will reproduce the sound properly, but if I hit **Jump to the Start** button, there will be no sound. I have to press Stop in order to have the sound back. It may be what @LucyLegendary89 was referring to...

**Comment by Jose-Moreno** [comment] 2020-08-07 00:17
@Kaikogf I'd prefer that you reported each of your issues individually so we can keep track of what breaks and what gets fixed. 

There are some issues with multiple elements but that make part of the same problem, in this case, the problem from the OP could be similar to another one reported where the actual sound didn't even load, but since there is no description we can't be sure.

Other than that I had the same problem as your "second issue" while testing another feature. In fact this happens only when you to to start during playback, not when it's paused, but it's still can be a breaking issue.

As for your first issue I can confirm the index is skipped and instead of showing sound layer it shows sound layer 2 as if it had created a sound layer before, but then again let's please report this in individual threads otherwise these reports will be lost as a comment and maintainers don't get notified with a comment if they have not engaged with the thread.

**Comment by Kaikogf** [comment] 2020-08-08 01:43
@Jose-Moreno 
I will do it right now. You are right 👍

**Comment by Jose-Moreno** [comment] 2020-09-05 05:26
Either this is related to #1448 which partially blocks sound import under specific conditions or the user is using an older version of Pencil2D along MP3 files with codecs that are not open. 

Since we don't have enough information and there was no further feedback from the user for over a month I'm closing this.

In any case please download the latest development build at http://pencil2d.org/download#nightlybuild and try again to import your sound files in case the issue keeps repeating under version **0.6.5**

**Closed by Jose-Moreno** 2020-09-05 05:26 UTC
Labels: More Info, Sound

**Comment by Kaikogf** [comment] 2020-09-06 13:41
@Jose-Moreno 

Tested it again. I will open new posts but here some information to begin with
The issue related to adding a new sound layer (adding a wrong name , instance “sound layer 2” when there is no other layer present) is fixed 👍 

The other issue (hitting Jump to the Start button, there will be no sound) is still there. Will update my other post related to this. With a small twist, meaning I found out how to avoid this situation ... 🥇  (joking)
