### ISSUE TITLE
it wont let me do anything

### ISSUE THREAD

**Issue by BonnieBoi** [pencil2d/pencil#1003] opened 2018-06-23 15:47 UTC
when i try to do something like to draw, it wont let me to draw

**Comment by Jose-Moreno** [comment] 2018-06-23 17:55
@BonnieBoi Hi and welcome. As a small announcement I'll have to let you know this is a forum to report confirmed technical problems & "bugs" with the software which is why there is a template with questions so you can tell the developers how is it exactly that the problem is happening. 

With such little amount of information it's almost impossible for them to know what is going on and would only appear as if the user was using the software in a wrong way.

Next time if you're unsure it's a software bug please ask first in the forum or DISCORD server which you can find here: http://pencil2d.org/community

### **Now for possible solutions, please check each of the following:**

1) Make sure you have the red marker on a frame (numbered column) that has a little colored square (drawing container)
2) Make sure you have the layer (row) with keyframes selected and active (you can know this by looking at the small black dot on the left of the layer name)
3) Make sure you are using a drawing tool inside the program like the pencil, pen, or brush
4) Make sure the drawing tool has a size above 2 so you can see it on the canvas.
5) Make sure you DON'T have a layer with a solid color or an image blocking the layer you're trying to draw ON inside the program.

If you follow the previous troubleshooting steps and it still does not work **please answer the following questions** to allow the developers to help you further:

1) What Operating System are you using? (e.g. Windows 7, MAC OS High Sierra, Ubuntu Linux, etc)
2) Which version of Pencil2D are you using? (To learn this info go to the HELP menu > ABOUT > and copy and paste here the information that appears on the dialog box
3) Are you using a mouse or a graphics tablet)? It doesn't draw with either?
4) Have you tried to use the program in a different computer? did it work?
5) If posible capture a screencast video of the problem while you use the software using free software like OBS (this is software that people use to record their screen and the resulting video you can later upload to youtube) http://obsproject.com

Thanks--

**Comment by Jose-Moreno** [comment] 2018-08-08 20:35
**Closing**
---
_**Reason**_
OP never corrected their report after a month, so further support was impossible without proper information.

**Closed by Jose-Moreno** 2018-08-08 20:35 UTC
Labels: invalid issue, more info, user error
