### ISSUE TITLE
Pencil doesn't ask you to save before close

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#387] opened 2015-12-21 21:38 UTC
If you start a new drawing you can accidentally close Pencil without saving because Pencil doesn't remind you that you yet haven't saved this project nor does it notice that the project you loaded has changed (e.g. you added drawings to it)

**Comment by ManuAros** [comment] 2015-12-21 21:43
Ok, just noticed you already reported this on the Pencil2D forum yourself feeef. :)

**Comment by chchwy** [comment] 2015-12-23 15:32
I'm working on it :)

**Comment by Jose-Moreno** [comment] 2016-02-04 22:31
@chchwy I think #282 is a duplicate of this problem. Since you assigned yourself to this one more recently, It may be best to close the other one since its almost a 1 year old report :+1:

**Comment by chchwy** [comment] 2016-02-09 02:27
@Jose-Moreno Thanks, I have closed #282

**Closed** 2016-09-02 01:35 UTC
Labels: bug
