### ISSUE TITLE
Can not save animation.

### ISSUE THREAD

**Issue by nukebo212** [pencil2d/pencil#1050] opened 2018-08-22 04:00 UTC
### --Issue Summary--
 When I try to save an animation there is an error.

### --Actual Results--
 I am not supposed to get an error and I have enough storage left where I am saving the animation.

### --Expected Results--
 Nothing should happen but my animation being saved.

### --Video or Image Reference--

FileManager::save
strFileName = D:/pencil2dfiles/MyAnimation14.pclx
strTempWorkingFolder = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/
layerCount = 4
layer[0] = Layer[id=1, name=Camera Layer, type=5]
layer[1] = Layer[id=2, name=Vector Layer, type=2]
layer[2] = Layer[id=3, name=Bitmap Layer, type=1]
layer[3] = Layer[id=4, name=Bitmap Layer, type=1]
- Layer[3] failed to save
  Layer::save
  strDataFolder = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
  - Keyframe[66] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 66
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.066.png
  BitmapImage could not be saved
  - Keyframe[65] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 65
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.065.png
  BitmapImage could not be saved
  - Keyframe[64] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 64
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.064.png
  BitmapImage could not be saved
  - Keyframe[63] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 63
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.063.png
  BitmapImage could not be saved
  - Keyframe[62] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 62
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.062.png
  BitmapImage could not be saved
  - Keyframe[61] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 61
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.061.png
  BitmapImage could not be saved
  - Keyframe[60] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 60
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.060.png
  BitmapImage could not be saved
  - Keyframe[59] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 59
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.059.png
  BitmapImage could not be saved
  - Keyframe[58] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 58
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.058.png
  BitmapImage could not be saved
  - Keyframe[57] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 57
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.057.png
  BitmapImage could not be saved
  - Keyframe[56] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 56
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.056.png
  BitmapImage could not be saved
  - Keyframe[55] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 55
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.055.png
  BitmapImage could not be saved
  - Keyframe[54] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 54
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.054.png
  BitmapImage could not be saved
  - Keyframe[53] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 53
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.053.png
  BitmapImage could not be saved
  - Keyframe[52] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 52
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.052.png
  BitmapImage could not be saved
  - Keyframe[51] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 51
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.051.png
  BitmapImage could not be saved
  - Keyframe[50] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 50
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.050.png
  BitmapImage could not be saved
  - Keyframe[42] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 42
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.042.png
  BitmapImage could not be saved
  - Keyframe[40] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 40
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.040.png
  BitmapImage could not be saved
  - Keyframe[39] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 39
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.039.png
  BitmapImage could not be saved
  - Keyframe[38] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 38
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.038.png
  BitmapImage could not be saved
  - Keyframe[36] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 36
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.036.png
  BitmapImage could not be saved
  - Keyframe[35] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 35
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.035.png
  BitmapImage could not be saved
  - Keyframe[12] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 12
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.012.png
  BitmapImage could not be saved
  - Keyframe[2] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 2
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.002.png
  BitmapImage could not be saved
  - Keyframe[1] failed to save
  LayerBitmap::saveKeyFrame
    KeyFrame.pos() = 1
    path = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data
    strFilePath = C:/Users/nicko/AppData/Local/Temp/Pencil2D/Default.Y2xD/data/004.001.png
  BitmapImage could not be saved

Error Display
Title: Internal Error
Description: An internal error occurred. Your file may not be saved successfully.

System Info
Pencil version: 0.6.1.1
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.17134
Product name: Windows 10 (10.0)

### --Steps to reproduce--
 I just hit Ctrl+S and I get an error.

### --System Information--
+ Pencil2D Version:
0.6.1.1

+ Operating System:
Windows 10

+ RAM Size:
 16 GB

+ Graphics Tablet:
 None, a laptop.

---

**Comment by Jose-Moreno** [comment] 2018-08-22 04:27
@nukebo212 Hi, this is a known issue already and it's getting fixed. However until the devs say it's okay to recommend a development build I'm afraid I'll have to ask you to follow this guide to prevent losing work from this problem.

https://discuss.pencil2d.org/t/answered-making-jpegs-stransparent/2981/4

You are welcome however to get the latest development version where I believe they have addressed the issue, but please understand that it does have a few other problems that are being solved and it's unstable, but you can try it out to see if it solves the saving issue for you. Just make sure you have plenty of backup copies as outlined in the guide linked above.

http://pencil2d.org/download#nightlybuild

**Comment by Jose-Moreno** [comment] 2020-08-30 07:33
Closing as duplicate of #987 and while this one has a lot of information regarding which keys were not saved, after providing a workaround and a version with a potential fix, we never received additional feedback after 2 years.

**Closed by Jose-Moreno** 2020-08-30 07:33 UTC
Labels: Bug, Duplicate, File Save
