### ISSUE TITLE
Can't export my animation as a movie

### ISSUE THREAD

**Issue by Tymow** [pencil2d/pencil#561] opened 2016-11-06 12:51 UTC
### --Issue Summary--
I can't export my animation whether as MOV nor any else format.

### --Actual Results
When I say "export as movie" and choose any format (I tried all) nothing happens.
No loading bar or anything.

### --Expected Results--
A sign of "rendering/converting" and my rendered file in my chosen directory.

### --System Information--
+ Pencil2D Version: 0.5.4

+ Operating System: Mac OS Sierra 10.12.1

+ RAM Size: 4GB

+ CPU: 1,6 GHz Intel Core i5

---

**Comment by Jose-Moreno** [comment] 2016-11-06 17:46
@Tymow Thank you for submitting an issue with the template :smile:  

This is a bug that has already been reported as this particular problem was due to the feature itself being disabled since it was broken. Only recently our lead developer managed to re-implement it so **If you'd like to test this feature working** you can download the latest Nightly Build for MAC on the following link and let us know if it works for you as well on this same thread.

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM?usp=sharing#list

Nightly Builds are development updates so they shouldn't be seen as final releases in any shape or form, even though they contain a hefty amount of fixes progressing toward the next stable release.

Note that you will only be able to export MP4 or AVI for now and there is a duration limit issue when exporting each movie that only allows for 8 seconds to be rendered every time, so we still recommend working on cuts.

If you require MOV especifically you can convert from MP4 easily with different solutions for MAC OS.

**Comment by Tymow** [comment] 2016-11-06 18:43
Thank you very much! 
Just one little issue more: when you draw something your mouse cursor and the drawn line have a little delay. Is there also a night build for it? 😅

Thanks again!

**Comment by Jose-Moreno** [comment] 2016-11-06 20:33
@Tymow I know what you mean. So far as a workaround what I have to do is to make the window really small and the lag will be diminished. 

We'll have to do this meanwhile another dev and friend of the project implements a different approach to drawing in pencil, which will at least guarantee that we have a good drawing tool with optimized speed, or so I understand. For this we will have to wait though as there is not yet an E.T.A on the feature.

**Comment by chchwy** [comment] 2016-11-08 03:43
Hi @Tymow 
Could you please try the latest nightly build (Nov 8 2016) for Mac and see tell me does it work better? Thanks.
https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM?usp=sharing#list

**Comment by Tymow** [comment] 2016-11-08 06:41
Hi @chchwy,
yes it works better. Still when I make a sudden move with the mouse the line has a little delay but not as long as in the previous build.
Also the 8 second export problem has been solved.
Keep it up guys!

**Comment by chchwy** [comment] 2016-11-10 11:00
Thanks @Tymow
I'm closing this issue since the problem is solved. 
We'll continue tracking the pen delay problem in #486.

**Closed by chchwy** 2016-11-10 11:00 UTC
