### ISSUE TITLE
Main xml file has vanished from project

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#936] opened 2018-04-02 17:24 UTC
### --Issue Summary--
context: https://discuss.pencil2d.org/t/help-my-animation-is-corrupted-i-need-help/2540/6

The user had been working on an animation over the course of a month when it suddenly stopped working.

having investigated the project file which was provided to me in a private message, all content is still there except the main .xml file. This suggests that the file has been deleted from both the temporary folder and saved project file, rendering it impossible to open again.

**Comment by chchwy** [comment] 2018-04-09 01:11
I looked into the file saving code of 0.6 again and found one thing: the file handle wasn't properly closed after writing the content of main xml file. So it is possible that the file is still in the operating system buffer and hasn't been flushed to disk when pencil2d is compressing the pclx file.

https://github.com/pencil2d/pencil/blob/9a9afada9fd7819a710899e14fac8cb3e22aee7a/core_lib/structure/filemanager.cpp#L356-L370

In current code base, we do flush and close the file handle in Line 324-325, so the main XML file will be surely on the disk when doing compression. Theoretically, this situation will not happen anymore after releasing the 0.6.1 since I don't see any other possibilities that the main XML will disappear without popping up error messages.
https://github.com/pencil2d/pencil/blob/c1ee7007d80e404904d865ba356b7f43b440e053/core_lib/src/structure/filemanager.cpp#L322-L339

**Comment by Jose-Moreno** [comment] 2020-08-28 05:42
@chchwy @CandyFace Do you think this still has any risk of happening in 0.6.5 at all? Or has the filemanager code improved beyond any possibility of this problem occurring for unsuspecting users? If this isn't the case then I think we can close this issue 👍

**Comment by chchwy** [comment] 2020-08-28 06:03
No. Let's close this issue.

**Closed by chchwy** 2020-08-28 06:03 UTC
Labels: Bug, Bug: File Save, Investigate

**Comment by CandyFace** [comment] 2020-08-28 06:06
In 0.6.5... maybe, however with the recent improvements done in #1436, there's at least a more graceful way to handle those situations, if the content still exists... but that's for 0.6.6. I wouldn't count on all issues being fixed though but I think it's fine to close the issue for now and then we can always open a new one should they surface again.

It's safe to say that we've certainly made changes that should prevent it from happening.

**Comment by scribblemaniac** [comment] 2020-08-28 06:18
I also won't completely rule out the possibility that this can still happen, and we are definitely lacking certain safeguards to prevent this from happening in the future (for example, as a result of a regression bug). However I support closing this issue as we haven't seen any users complaining of this specific form of corruption in a long time.

I also should note that #1436 wouldn't have helped with this situation at all because the project did save and the program presumably did exit normally, which would result in the temporary project folder being deleted and the recovery process not being triggered.

**Comment by chchwy** [comment] 2020-08-28 06:26
Just run through the code. At least I don't see any possibility that writing main.xml to disk will fail. Unless the app crashes during the file save, but that's not the scope of this issue.
