### ISSUE TITLE
No camera movement during video export

### ISSUE THREAD

**Issue by JustkeepgoingPencil2DDevelopers** [pencil2d/pencil#1061] opened 2018-09-07 19:36 UTC
Issue Summary:

When I would like to export a video (doesn't matter if it is gif/apng/mp4/avi) it won't move the camera according to camera layer. It works fine with same file in exporting series of png files.

I think it is just a missed switch or if else in the code as it works in png export. I guess making a vide should be the same just making a movie as end result.

Cheers,
Jason

**Comment by JustkeepgoingPencil2DDevelopers** [comment] 2018-09-07 19:38
Issue Summary:

When I would like to export a video (doesn't matter if it is gif/apng/mp4/avi) it won't move the camera according to camera layer. It works fine with same file in exporting series of png files.

I think it is just a missed switch or if else in the code as it works in png export. I guess making a vide should be the same just making a movie as end result.

Cheers,
Jason

**Comment by scribblemaniac** [comment] 2018-09-07 19:46
This is a bug that we have fixed and will be in the next stable release. Until then, please download [the latest nightly build](https://www.pencil2d.org/download/#nightly-build-) and camera motion will be applied to exported movies. Please let us know if you are still having troubles with the latest nightly build.

Closing as a duplicate of #960.

**Closed by scribblemaniac** 2018-09-07 19:46 UTC

**Comment by Jose-Moreno** [comment] 2018-09-07 19:57
@JustkeepgoingPencil2DDevelopers Hi. I'm tagging you because a developer answered your issue and as he described, this is a known issue that was already fixed. Please look at his comment and download the most recent development build in order to be able to export properly the camera motion. If you have any question, let us know.

**Comment by JustkeepgoingPencil2DDevelopers** [comment] 2018-09-07 20:04
I am superstaisfied!

Morr <notifications@github.com> ezt írta (időpont: 2018. szept. 7., P,
21:57):
