### ISSUE TITLE
Exporting only gives me one frame

### ISSUE THREAD

**Issue by TheIrkenLuxray** [pencil2d/pencil#1129] opened 2018-11-23 03:31 UTC
When I try to export my animation as either an MP4 or a GIF file, I'll only get the first selected frame instead of the whole sequence of frames.

 

### Actual Results
Upon exporting an animation, only the first frame (among the range) is included, resulting in a still image or a 1/12-second video.

 

### Expected Results
The GIF or MP4 displays all frames selected.

 

### System Information
+ Pencil2D Version: 0.6.2

 

+ Operating System: Windows 8.1

 

+ RAM Size: 8GB

 

+ Graphics Tablet: HUION NEW 1060PLUS

**Comment by Jose-Moreno** [comment] 2018-11-23 03:37
@TheIrkenLuxray Hi thank you for your report. Would you mind trying one of the most recent development builds to see if the problem is still present there? Here's a direct link to Windows 64 bits from October 14th: https://drive.google.com/open?id=1-kZs1-OMhX8E2bc4rYLcP8hCkJH-2-4B

Also if this test does not provide the expected result Is it possible that you can share a link to your pencil2d project file so developers can take a look at it?

**Comment by TheIrkenLuxray** [comment] 2018-11-23 03:56
@Jose-Moreno I have tried it with the Nightly Builds version, but I get the same result. Here's my project file.

[angel.zip](https://github.com/pencil2d/pencil/files/2609672/angel.zip)

**Comment by Jose-Moreno** [comment] 2018-11-23 04:09
@TheIrkenLuxray Ok I just downloaded the file. I'm on Windows 7 btw. I can see only 5 drawings in the PCLX. 

1) I exported a GIF and It worked as expected (it shows the 5 drawings on a loop)

2) Exporting an MP4 however is a different story as using VLC or a few other players videos with less than 10 frames are normally clipped from beginning and end (frames are dropped) so in this case it looks like it's "still" image. However using Quicktime Player does playback the MP4 properly.

![angel_test_gif](https://user-images.githubusercontent.com/4912907/48928303-974ca100-eeab-11e8-8469-80c3439f703c.gif)

I used the nightly build I linked on my previous comment. I used the File > Export > Animated GIF / Movie | MP4 options

**Comment by TheIrkenLuxray** [comment] 2018-11-23 16:57
@Jose-Moreno I wasn't aware that VLC Media player did that, so I tried it with Chrome's web player and it worked fine. The GIF file worked with Chrome too, so the fault must have been with my computer's own software instead of the program itself. Thank you for helping me!

**Comment by Jose-Moreno** [comment] 2018-11-23 17:09
@TheIrkenLuxray You're welcome. Yeah VLC does that and to this day I still don't know why, there were a few other players that did the same. 
If the problem Is resolved then I'll close this issue. If you have any other issue please create a new thread, however if you are not sure it's an actual "bug" please use [Pencil2D's forum](http://discuss.pencil2d.org) or Pencil2D's Discord to get help more quickly and so we can triage if it's a bug or not and report it here or fix it on the spot, that way developers can focus their efforts solely into fixing application problems, have fun! :slightly_smiling_face:

**Closed by Jose-Moreno** 2018-11-23 17:09 UTC
Labels: investigate
