### ISSUE TITLE
Canvas rotation

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#8] opened 2013-06-27 12:19 UTC
Like Krita (and Photoshop), a very great feature would be the ability to rotate the canvas while drawing in Pencil2D.

**Comment by nicholasopuni31** [comment] 2016-07-31 19:48
the only bug I got on my issue is "rotating" the selected canvas

**Comment by Jose-Moreno** [comment] 2016-07-31 20:22
Also Go to View > Rotate Clockwise & Rotate Anti-Clockwise, Shortcuts are R and Z for incremental rotations. 

Since we're talking feature request, personally I dislike how the ALT + Rick Click dragging works. It should be a bit more smooth. and there should be some indication to know you're rotating it and to which side.

**Comment by Jose-Moreno** [comment] 2016-10-16 17:31
@chchwy We sort of have this feature now, however the rotation feature while pressing the ALT key + Clicking any mouse button only moves clockwise, and it seems the speed of the mouse movement is factored into the amount of degrees that the canvas rotate, however it also seems that it isn't always checking the relative rotation but interpolating from one point to the other.

A further improvement for this request would be to allow a "drag & rotate" functionality where the screen rotation follows the position of the mouse and takes into account the relative distance it moves, instead of having discreet or smooth rotation Clock-wise. 

So if I move the mouse in the left side region of the screen , the screen should rotate counter-clockwise, and if I move the mouse right it should go clockwise.

**Comment by Jose-Moreno** [comment] 2017-04-13 03:48
@chchwy If scribblemaniac's refactoring of the hand tool via #641 is succesful, do you think we can consider this very early request fulfilled?

**Comment by CandyFace** [comment] 2017-04-17 08:53
I can confirm that @scribblemaniac implementation works great, so i'm closing this. If canvas rotation requires further enhancement, then we can make a new issue.

**Closed by CandyFace** 2017-04-17 08:53 UTC
Labels: enhancement
