### ISSUE TITLE
#1751 It was not resolved and I could not speak at the forum

### ISSUE THREAD

**Issue by morsmordreb** [pencil2d/pencil#1752] opened 2023-03-22 02:22 UTC
### Issue Summary
 I don't know why the forum has been banned from Posting something, so I don't know how to feedback information。
    Frustratingly, I still couldn't handle hand-tools, even with a recent version of the client.
    I read your tutorial carefully, especially in the camera layer with hand-tools operation, but I can't like you, I don't know whether the mouse needs to be operated at the same time with button assistance.
    Please help me, and I wonder if it is convenient to add your friend. I am a developer, and I have some things I want to develop together.
   

<img width="1249" alt="025d28c7-b503-469e-8211-4d56172294bd" src="https://user-images.githubusercontent.com/88188802/226784904-11dd309d-b652-49bb-8050-415110901035.png">

https://user-images.githubusercontent.com/88188802/226785275-651928ba-f3d3-431d-9de8-d134f6142ad1.mp4

**Comment by Jose-Moreno** [comment] 2023-03-22 07:51
@morsmordreb Hi. I'll try to reply to your comments in order

### Forum

I'm sorry to hear you have not been able to use the forum. I don't really know the cause, but it may be because you are a new user, however you should be able to post 😕 I'll ping a developer in case they might know the cause or have a potential solution to that problem @J5lx 

### Github
I know I closed the other thread, but you can still comment on any closed thread you started. That way we can have focused discussions in a single area. 

We are trying to keep Github as a place to report verified issues with the software, so hopefully you can solve the forum problem soon to post questions over there.

### Camera System
The idea of the first tutorial is that you should animate the car on a different file. Then export it as an image sequence and import that into the file with the background.

I see the hand tool is not working for you, please try using a recent development version found on the link below.
These versions have a **new system** to operate the camera in a different way.

[https://pencil2d.org/download/nightly](https://pencil2d.org/download/nightly)

To manipulate the camera with the new system have to use the move tool (black arrow icon) when the camera layer is selected.

The hand tool is now reserved only for the workspace view transformations (translation, rotation, scale of overall editor view; this does not affect the resulting video or image)

Here is a video on how to use the new system in the nightly builds.
https://user-images.githubusercontent.com/4912907/226833459-6ecc6bde-704e-404e-8c66-6c4a072802aa.mp4

### If Nothing else works...

Then please try a different software meanwhile we investigate the problem.
If you really need to move different layers and objects easily, you can try the following free applications for quicker & better results in motion tweening (motion interpolation):

- Synfig [https://github.com/synfig/synfig/releases/tag/v1.4.4](https://github.com/synfig/synfig/releases/tag/v1.4.4)
- TupiTube Desk [https://www.tupitube.com/index.php?r=custom_pages%2Fview&id=6](https://www.tupitube.com/index.php?r=custom_pages%2Fview&id=6)
- Enve2D [https://github.com/MaurycyLiebner/enve/releases](https://github.com/MaurycyLiebner/enve/releases)
- Opentoonz [https://github.com/opentoonz/opentoonz/releases/](https://github.com/opentoonz/opentoonz/releases/)

**Comment by morsmordreb** [comment] 2023-03-22 17:03
Thanks.
After reading your description and explanation, I understand that the online tutorial is the old version, and the new version works through mobile tools. Thank you. I am a developer. I will deal with the problem of code or submission in the future through github, and I will deal with the problem of usage or function through the forum. Thank you again

**Comment by MrStevns** [comment] 2023-05-29 08:31
Given that there hasn't been any activity on this in a while, I will close the issue.
Let us know if you still need help.

**Closed by MrStevns** 2023-05-29 08:31 UTC
Labels: Question, Camera
