### ISSUE TITLE
Pencil2D-Nightly Build get crashed

### ISSUE THREAD

**Issue by linganesan** [pencil2d/pencil#564] opened 2016-11-10 11:27 UTC
### --Issue Summary--

Pencil2D Crashed
### --Actual Results

Pencil2D get crashed when I click the 'Multilayer Onion Skin' option
### --Expected Results--

Should not be get crashed
### --Steps to reproduce--

Goto menu bar & Select: View->Onion Skin ->Multilayer Onion Skin
### --System Information--
+ Pencil2D Version: Pencil2D - Nightly Build

+ Operating System: Fedora

+ RAM Size: 8GB

+ CPU: 2.40GHz Intel Core i-7

Error log:
ASSERT: "false" in file ../../pencil/core_lib/managers/preferencemanager.cpp, line 282

**Comment by scribblemaniac** [comment] 2016-11-11 00:04
Thanks for reporting, this should be fixed when the next nightly build is released 😄

**Comment by CandyFace** [comment] 2017-04-11 17:01
Can't reproduce this anymore, closing.

**Closed by CandyFace** 2017-04-11 17:01 UTC
Labels: bug, testing
