### ISSUE TITLE
[request] More stable pencil2d downloads.

### ISSUE THREAD

**Issue by Projectashgreninja** [pencil2d/pencil#635] opened 2017-04-09 17:06 UTC
The only versions of pencil 2d are the unstable ones and when I click on the more stable and older version it takes me to dropbox and now I'm left with unstable, not responding, crashing  windows version. I want the more stable version of pencil 2d.

**Comment by Jose-Moreno** [comment] 2017-04-09 17:18
@Projectashgreninja I'm sorry but older versions are actually not stable anymore and have a lot of bugs that have already been fixed, particularly on newer systems. 

The Nightly Build for November 2016 might be the most stable to date, and I can  personally attest to that because I made a long new year's animation recently without a single crash.

Of course Pencil2D is an on going project and more testing and work needs to be done, but this is only possible thanks to the generous volunteering time that developers are providing to it.

If you're confused about which files to download here's the actual file names for the latest working version:

For MAC is: Pencil2D-mac-20161108.zip
For WIN is: Pencil2D-win64-20161102.zip

Right now developers are testing how to integrate changes as fast and as reliably as possible, so this year's builds are still not being advertised for normal use.

However if you say the one you are using is really unstable we need to know more information like which operating system you are using and which version of Pencil2D is exactly that you have otherwise devs can't take a look.

Thanks for commenting, and please follow up with the info if the above version still doesn't work for you.

**Comment by Jose-Moreno** [comment] 2017-04-09 17:21
@chchwy Is there any way we can have a proper binary to allow people to download? I proposed that here #584 but no one commented on it. I had to divert people form downloading the old 0.5.4 dev version because it's already too old, and a lot of fixes have been implemented since then.

I think that despite whatever issue, we can release an interstitial version, while we continue to refine the program for an 0.6 release. Please let me know what you think.

**Comment by Projectashgreninja** [comment] 2017-04-09 17:23
I'm okay with it

**Comment by feeef** [comment] 2017-04-10 07:42
I guess it is time to release a 0.6 version. It won't be worst than the very old "stable" version on the website, wish is not stable at all.

**Comment by chchwy** [comment] 2017-04-11 04:55
I'll make a windows build tonight since there is no ci for windows yet.
And I agree that it's time to release a 0.6. What we have to do is any issues should really be fixed before 0.6 release?

**Comment by Projectashgreninja** [comment] 2017-04-11 05:00
The issues should be fixed and the new version has to be tested for some time before released so we can make sure there are no issues for the release.

**Comment by chchwy** [comment] 2017-04-11 05:30
The problem is there are already too many known issues, just look at this issue tracker. It is not possible to be fixed all of them in few days. We can only pick the important ones first.

One thing I will work on is camera interpolation, the camera layer is broken now.

**Comment by CandyFace** [comment] 2017-04-11 16:00
it's not realistic for us to fix all of them before we release, that is if we want it to happen within this month. However it would certainly be nice if the camera layer worked as intended. The memory leaking issue is serious too. but it's difficult to replicate and debug.

**Comment by Projectashgreninja** [comment] 2017-04-12 01:04
Then we just do what we can and fix the rest along the way , unless there is another way.

**Comment by chchwy** [comment] 2017-11-01 02:30
@Projectashgreninja 
The recent pencil2d version has improved a lot in many ways. Also I believe 0.6 will be released soon.
Please try the nightly builds out and tell us what you think.

I'm going to close this issue, thanks.

**Closed by chchwy** 2017-11-01 02:30 UTC
Labels: release, request
