### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BillyCort1** [pencil2d/pencil#1668] opened 2021-10-16 20:01 UTC
![Bez tytułu](https://user-images.githubusercontent.com/92649614/137600751-71defcc3-1515-46bd-9de3-6fb7d95d5e47.png)

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by BillyCort1** [comment] 2021-10-16 20:01
the program turned off by itself, I didn't do anything, it just turned off. if I accidentally clicked alt f4, it would show me whether or not to close, I did it for 10 hours without a break and at the end it turned off by itself

**Comment by Jose-Moreno** [comment] 2021-10-17 01:15
Closing as duplicate of #1669

**Closed** 2021-10-17 01:15 UTC
