### ISSUE TITLE
Line in vector layer gets a little bit transparent when drawn

### ISSUE THREAD

**Issue by giureggio** [pencil2d/pencil#579] opened 2016-12-03 20:25 UTC
### --Issue Summary--

Everytime that I am going to draw something at the vector layer, independently of the tool I am using, the line gets a little bit transparent after I release the mouse.

### --Actual Results

The line gets a little bit transparent when drawn.

### --Expected Results--

I believe the opacity of the line should stay the same way it does while I am drawing, that is, before I release the mouse, as it happens in the bitmap layer.

### --Video or Image Reference--

![image](https://cloud.githubusercontent.com/assets/24321090/20861850/5f6ed85e-b981-11e6-8fde-dc2a02b430e9.png)
- This is an image of a circle being drawn in the vector layer, using the pen tool.

![image](https://cloud.githubusercontent.com/assets/24321090/20861734/a4283402-b97e-11e6-99ce-aaa0aeffb630.png)
- This is an image of a circle already drawn in the vector layer, using the pen tool. In this case, the mouse button had been released

![image](https://cloud.githubusercontent.com/assets/24321090/20861751/f532ee50-b97e-11e6-970f-aa2ae0ab082e.png)
- This one is of a circle drawn in the bitmap layer also using the pen tool.

### --Steps to reproduce--

1. Open Pencil2D Animation v0.5.4;
2. Click on the vector layer;
3. Draw something using the pen tool;
4. Click on the bitmap layer;
5. Draw something using the pen tool;
6. Notice the diferences between them concerning the opacity of the lines.
*Note: these was made with the configurations gave by the program when it was opened.

### --System Information--
+ Pencil2D Version:

Pencil2D Animation v0.5.4

+ Operating System:

Edition: Windows 10 Home
Version: 1607
OS Build: 14393
+ RAM Size:

4.00 GB
+ CPU:
Procecessor: Intel(R) Core(TM) i3-3227U CPU @ 1.90 GHz 1.90 GHz

+ Graphics Tablet:

---

Hope to hear from you soon :smile:

**Comment by scribblemaniac** [comment] 2016-12-03 20:42
Thank you for your detailed report! This is not actually a bug, but is part of the relative transparency feature. Layers other than the one selected will appear slightly transparent. To disable this, you can click the small circle directly below layers. There are some bugs associated with this feature as well, which are discussed in #552.

**Comment by giureggio** [comment] 2016-12-04 03:22
Thank you for your quick reply! I will check the problem again.

**Comment by Jose-Moreno** [comment] 2016-12-04 05:28
@giureggio I have a small video showcasing this feature, just in case you have difficulties finding how to use it:

https://www.youtube.com/watch?v=jJxJ4bGrt3U

Note: please turn your speakers volume on, since the volume is a bit low.

**Comment by Jose-Moreno** [comment] 2018-06-16 16:10
@chchwy @scribblemaniac @CandyFace We should close this issue as it was never a bug to begin with. 

However I still think causing the passive layers to be dimmed when working on an active layer (what I used to call "relative layer transparency") Should be brought back, since that's why there was a toggle on the layers section of the timeline that allowed you to make it fully opaque, relative (passive layers slightly dimmed) or just to isolate the active layer.

I also asked before if it was possible to export the hardcoded "dim" value to manipulate it so passive layers could be "dimmed" at will with a global slider (this would be basically global passive layers opacity) but I never really got that answered.

**Comment by Jose-Moreno** [comment] 2018-08-09 20:47
**Closing**
---
_**Reason**_
Originally this was not a bug but a feature to allow artist to "focus" on the active layer's content. To get a fully opaque layer visualization you required to use the circular checkbox toggle on the left hand side of the timeline (grey by default, black activated full opaqueness). However since v0.6.0 this behavior has been temporarily disabled so this thread is no longer valid either way.

**Closed by Jose-Moreno** 2018-08-09 20:47 UTC
Labels: invalid issue
