### ISSUE TITLE
Last frame getting skipped while looping

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#838] opened 2017-12-19 00:18 UTC
### --Issue Summary--
When playing back an animation with looping enabled, the last frame does not show for as long as it should.

### --Expected Results--
The last frame should play for the same amount of time as all of the other frames.

### --Video or Image Reference--
https://youtu.be/pMA7M-OL8uQ?t=1m40s

### --Steps to reproduce--
1. Create a few frames
2. Enable looping
3. Lower FPS (even to 1) to increase visibility of issue
4. Play the animation

### --System Information--
Pencil2D Version: 0.6.0 & ec017ea

Operating System: macOS 10.13.1

RAM Size: 16 GB

**Comment by CandyFace** [comment] 2018-01-05 14:15
Has anybody tested his after the two recent changes to the timeline playback? https://github.com/pencil2d/pencil/commit/8319cb5e4cb8677a338917b749615544701b0447

**Comment by Jose-Moreno** [comment] 2018-01-08 18:11
@scribblemaniac @CandyFace Just checked this with 1fps playback on Jan 1 2018 build, and it's working as expected (it takes one second to show the last frame before jumping back to the first frame). I'm on windows so could either of you verify if that is the case for MacOS?

**Comment by CandyFace** [comment] 2018-01-09 15:25
I can confirm that it's working as intended in Jan 1 nightly build on Mac OS too.

I'm closing the issue.

**Closed by CandyFace** 2018-01-09 15:25 UTC
Labels: bug
