### ISSUE TITLE
Didn't Save Correctly/File Corrupted

### ISSUE THREAD

**Issue by allnewjmk8** [pencil2d/pencil#1062] opened 2018-09-15 21:00 UTC
### --Issue Summary--
Issue saving project, closed program and restarted and Pencil2D says that file is partially corrupted. 
Installged the latest version of Pencil2D and still won't open project.

### --Actual Results--
Corrupted Files/Save Problem
### --Expected Results--
Should save and open files properly

### --Steps to reproduce--
1. Opened program and started working
2. Autosave was running and started to save project
3. Issue prompt popped up and said to come here
4. Excited program and restarted computer
5. Opened program again opened Pencil2D project
6. Issue prompt popped up again
7. Came to GitHub
8. Saw same issue
9. Installed latest version from nightly builds
10. Opened new version
11. Experienced same issue

### --System Information--
+ Pencil2D Version: v0.6.1.1
and Nightly build Version: 2018-09-12_07:57:18

+ Operating System: Windows 10 64-bit

+ RAM Size: 8GB

+ Graphics Tablet: Wacom Intuos

---

**Comment by Jose-Moreno** [comment] 2018-09-15 21:27
Hopefully we can also have a way to recover corrupted files that happen fortuitously (due to blackouts or interrupted save operations) as I've proposed in #1045 But sadly we require help from someone who's willing to dedicate themselves to undertake that implementation and so far no one has offered to contribute :slightly_frowning_face:

**Comment by Jose-Moreno** [comment] 2020-08-30 07:30
Closing as duplicate of #987 and after potential fix was issued, OP never provided feedback to corroborate if this problem kept recurring or not for their specific situation and user environment.

**Closed by Jose-Moreno** 2020-08-30 07:30 UTC
Labels: Bug, Duplicate, File Load, File Save
