### ISSUE TITLE
pencil2d icon does not appear in the app menu, Ubuntu 18.04

### ISSUE THREAD

**Issue by Lvaskz** [pencil2d/pencil#1027] opened 2018-07-26 14:54 UTC
Hi, I'm using Ubuntu 18.04, community theme, 64 bit
version of pencil 2d 0.6.1, for 64 bit
I am using a tool to integrate the appimages in the applications menu; appimagelauncher.
The detail is that the pencil2d icon does not appear in the applications menu, could you add one?

**Comment by J5lx** [comment] 2018-07-26 18:19
Hi @Lvaskz! I’m sorry to hear that the installation isn’t working entirely correct for you. As it turns out, we already have an icon embedded in our AppImages. However, I just tested appimagelauncher and I can confirm that the icon does not show correctly for me either. From a quick look, it seems that this is caused by a shortcoming in appimagelauncher. When appimagelauncher installs an AppImage, it renames its icon so that its name becomes unique and doesn’t conflict with other icons on the system. It only does so for the default icon, though – Pencil2D’s AppImage, however, contains additional icon names in several different languages (these are currently all identical to the default icon name, but our translation tool inserts these entries for us automatically), and these additional icon names are currently *not* updated by appimagelauncher. Therefore, if your system is configured to use a language for which our AppImage includes an additional icon name entry, it will search for an icon with our default name “pencil2d” but won’t find it because appimagelauncher installed the icon with a different name. Therefore, it would probably be best to open a bug report for appimagelauncher – if the maintainers have additional questions that you can’t answer, you can point them here.

That said, if you are really extra sure that your system is not configured to use any of the additional icon names, there is also something else that could be going wrong: In version 0.6.1, there was a bug that caused the icon to be installed in the wrong location (see #946 for details, if you are interested). I don’t think this bug affected our AppImages, but if it did there is a chance that updating to 0.6.1.1 will solve your issue.

I hope this helps, even if just a little. Let us know if it doesn’t, or if you need more assistance.

**Comment by TheAssassin** [comment] 2018-07-26 19:12
This is not quite true. After extracting it, I just found one icon in the AppImage, which is `squashfs-root/usr/share/icons/hicolor/256x256/apps/pencil2d.png`. This is the output of ImageMagick's `identify`:

```
squashfs-root/usr/share/icons/hicolor/256x256/apps/pencil2d.png PNG 256x256 256x256+0+0 8-bit sRGB 24.8KB 0.000u 0:00.000
```

There is no other icon file in the entire AppImage.

**Comment by J5lx** [comment] 2018-07-26 19:45
@TheAssassin It's not that there is more than one icon, it’s that there’s more than one icon entry in the desktop file (that’s what I was referring to when I said icon name), see  [app/data/pencil2d.desktop](https://github.com/pencil2d/pencil/blob/master/app/data/pencil2d.desktop):

```desktop
[Desktop Entry]
…
Icon=pencil2d
…
Icon[he]=pencil2d
…
Icon[ar]=pencil2d
…
Icon[pt]=pencil2d
…
Icon[pt_BR]=pencil2d
…
 ```

Right now, appimagelauncher only replaces the first one of these (without a locale key) with the file name it generates during installation, while all the other ones continue to be set to just pencil2d (at least that’s what it did when I tried to install our AppImage earlier.

**Comment by TheAssassin** [comment] 2018-07-26 19:49
_Now_ I understand. Yes, that's a big issue, you're absolutely right.

This is actually a bit annoying, as these entries are entirely redundant. If they weren't there, it would simply work. I guess there's no `[en]` entry, which is why it worked for me.

This counts as [Linux Desktop Platform Issue](https://gitlab.com/probono/platformissues).

I am going to fix this upstream in [libappimage](https://github.com/AppImage/AppImageKit) asap. I already have some code performing similar work to work with localized `Name` entries, which I will re-use for this, too.

Thanks for bringing this up, @J5lx and @Lvaskz.

**Comment by J5lx** [comment] 2018-07-26 20:15
Yeah, the redundant icon entries are in fact kinda annoying. The problem is that last I checked Transifex didn’t provide any option to prevent translations of certain keys entirely (you can only mark them as untranslatable, which I did, but even then translators can still use the source string as translation). So the status quo is that on one hand redundant entries are kinda annoying but standards-compliant while on the other hand removing them manually every time we update the translations is *also* kinda annoying and there is no standard way to work around that, so yeah. Not exactly perfect, but it works – normally at least.

**Comment by TheAssassin** [comment] 2018-07-26 20:17
We should probably make [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) (linuxdeployqt successor) recognize such redundant entries and remove them.

Anyway, working on this at the moment.

**Comment by Lvaskz** [comment] 2018-07-26 20:46
"Thanks for bringing this up, @J5lx and @Lvaskz." No problem, it is hard to try explain some issue when I am not programmer or similar but, it is ok.

**Comment by TheAssassin** [comment] 2018-07-27 00:35
Should be fixed now, guys. Thanks again for helping me understand this issue. Desktop files can be annoying to support, especially due to the lack of a good parser...

**Comment by TheAssassin** [comment] 2018-07-27 00:38
@J5lx a tip from my side, you could greatly improve desktop integration support by writing a `X-AppImage-Version` entry into your desktop files on build. Tools like AppImageLauncher or AppImage "app stores" can make use of that information, and greatly improve the UX.

**Comment by Lvaskz** [comment] 2018-07-30 14:11
@J5lx can you confirm, please if the issue was resolved, with the new appimagelauncher's binary? In my case not. Any way I should see what is hapenning or asking some help.

**Comment by TheAssassin** [comment] 2018-07-30 17:51
@Lvaskz can you search for the desktop file that AppImageLauncher wrote to your system?

```
cat ~/.local/share/applications/appimagekit*pencil2d.desktop
```

I just noticed mine's totally broken, I'm already working on a fix, I just want to see whether yours looks similar.

**Comment by Lvaskz** [comment] 2018-07-30 17:59
Hi, I have seen several of those in my system. The problem is that I can give you this information until later, it is that I am with the work computer, not on my personal computer.

**Comment by TheAssassin** [comment] 2018-07-30 18:15
@Lvaskz sure, no problem, perhaps I'll fix it in the meantime ;)

**Closed** 2018-07-31 20:27 UTC
Labels: investigate
