### ISSUE TITLE
bug report : onion skin not working + scrolling down timeline absent + unable to delete camera layer

### ISSUE THREAD

**Issue by doryfor** [pencil2d/pencil#568] opened 2016-11-13 20:59 UTC
this bug report is divided in 3 sections:
1)onion skin not working 
### --Issue Summary--
there is a little button with two arrows pointing sideways. when i click it, nothing happens

### --System Information--
latest nightly build : Pencil2D-win64-20161102
windows 10

2) scrolling down not working 
i saw this bug was already mentioned on github and apparently fixed? this was the only official place i could find to report bugs, and since it wasn't there already, i thought i might aswell.
### --Issue Summary--
the sidescrolling bar is there, but the button has disappeared, i cannot scroll down the timeline vertically. 

3)unable to delete camera layer
### --Issue Summary--
when i have a camera layer selected, if i press the (-) button, the "are you sure you want to delete layer: camera layer" dialogue box appears, but upon pressing delete, nothing happens. it works fine for other layers.

have a nice day, 

Doryfor

**Comment by Jose-Moreno** [comment] 2016-11-13 21:11
@doryfor Hi! Right now I'm using the same version on Windows 7 and it's working for me as intended.

1. Onion skin is activated still by using the "Display" panel on the right hand side and pressing the corresponding buttons. If you can't find them press shortcuts O and ALT+O to enable them

The diamond button is to enable adjacent frame or keyframe onion skinning, not to enable the onion skin altogether.

2. Exactly what scrolling function are you referring? Is it the timeline scrolling when you have multiple layers? This is also working as intended on mine. Try to focus the timeline panel by clicking on any layer and try to use the scroll.

3. This one is intended, due to the problem of people complaining about not having a working visible area, the camera layer no longer allowed to be deleted because it was always required to be used during export and it would be possible to see the render area otherwise.

The only one that worries me is point No. 2. If this behaviour continue to happen do you think you could edit this thread and only leave that as a bug for windows 10? Also I'd like to ask of you to post a gif, a video or an image that portrays exactly what happens, as well as to a few steps on how to reproduce it. Thanks a lot!

**Comment by doryfor** [comment] 2016-11-14 13:20
hi jose,
thank you for enlighting me on point 1&3! onion skin works fine for me too :p i really like the new ability to change onion skin colours.
as for point 2  : 
@scribblemaniac  posted this : the description says "Fix non-native vertical scrolling behavior for the timeline " and it is marked as fixed. 
https://github.com/pencil2d/pencil/pull/531/commits/e4645aea5185f7159f8a3e53996e2c54c94ce2da

just in case though, here is a description of the bug encountered : 
even with multiple layers "hidden" beyond the border of the timeline, the scroll bar does not have a scroll button, making it impossible to scroll down. the bug is always there, whenever i open this version of pencil on windows 10 
![pencil bug vertical scroll](https://cloud.githubusercontent.com/assets/23439151/20266216/7ad1f6dc-aa75-11e6-9b69-691d4e75134a.PNG)

**Comment by doryfor** [comment] 2016-11-14 13:37
i have another question: 
when i'm on the camera layer, i can't move the background independently from the camera layer. 
this means, the camera layer is alway in the same place relative to the other layers. (even when on the actual camera later). zooming in and out also works on all layers at the same time. heres a vid to explain what i mean : 

![ezgif-2291148809](https://cloud.githubusercontent.com/assets/23439151/20266733/cd4a509c-aa77-11e6-9460-ef87de31ba02.gif)

**Comment by Jose-Moreno** [comment] 2016-11-14 14:22
@doryfor Yeah No. 2 seems like a MAC only bug  alright, if @scribblemaniac committed that fix it should be working on the newest nightly build for MAC. Guess this issue has more ramifications than intended so it's worth investigating

Regarding the camera, yes that's what I meant by "intended" yet missing feature. This has to do with issue #567 which I requested yesterday before you sent yours. Right now don't think of the camera as a camera, but rather think of it as a fixed viewfinder. If you want to have more space to work on double click the camera layer and increase the canvas resolution. Moving the camera to do pans is impossible at the moment though, you can only move the canvas like in regular drawing software. So it's useless to make "new" camera layers.

In fact we actually have to discuss the implications of having multiple camera layers, because in theory having multiple camera layers would be great for multiple cuts in the same file, like opening holes on the "passepartout" but I don't know if this is possible through code right now. Although if you could keyframe the same camera, that would serve the same purpose, plus having multiple cameras would be intense for the export routine as well since you'd have to create some kind of marker system to let pencil and the user know which camera is supposed to be exported next. I'll make a request later too, maybe we can get something good out of this issue.

Matt said there that as far as he know no one messed with the camera code, but I'm almost positive that the camera motion had to be disabled in order to allow persistence on the canvas. It was basically a trade-off. He tagged my request as a bug though, so I guess there's that.

**Comment by doryfor** [comment] 2016-11-14 14:36
alrighty thank you for your for taking the time to explain. i'm still a tad confused because i don't know much about programming. nonetheless, i hope everything will be resolved quickly.

**Comment by scribblemaniac** [comment] 2016-11-14 16:57
To clarify a bit, e4645ae would only have an effect on the direction of scrolling, not whether or not a scrollbar appears. I cannot replicate your behavior on a mac or linux, so this is a windows 10 only issue it seems. There is a reasonably good chance that this issue will be fixed in #533. Also I suspect that multiple cameras would be a large pain for the current code since there are places that are hardcoded under a one-camera assumption if I remember correctly.

**Comment by doryfor** [comment] 2016-11-14 17:23
well, there you go, tried it with one camera layer only and it works fine on a new project! the bug occured when i imported an old project with two preexisting layers, and that's the only way i've found to replicate the bug. if you actually manually add another camera layer to a project created in the new nightly build, everything works fine too.

**Comment by scribblemaniac** [comment] 2016-11-14 18:01
Ah okay then, now I understand the issue. It should be fixed with #572 and should be in the nightly builds soon hopefully. In the mean time as a workaround you can add a layer and then remove it to force it to update.

**Comment by CandyFace** [comment] 2017-04-10 08:00
Alright just to clear this up, the only issue I see that remains is the ability to remove new camera layers. That bug has been reported already in #425 

I'm closing this as the original mentioned issues seems to have been fixed.

**Closed by CandyFace** 2017-04-10 08:00 UTC
