### ISSUE TITLE
Copying and Pasting Issue

### ISSUE THREAD

**Issue by Lightningbender** [pencil2d/pencil#1231] opened 2019-06-22 14:24 UTC
### Issue Summary
When I select an area of a frame to copy, copy it, and then try to paste it on another frame, instead of just pasting the area that I copied, the entire frame gets pasted. Funny thing is is that I just downloaded the new may 30 version and it seems to be working fine there. But when I open this older project it doesn't. Is it because the project's from a version I downloaded a while ago? Because I always just assumed when you download the newest version, your projects automatically use that version.

 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment] 2019-06-22 16:18
@Lightningbender Hi. Pencil2D is a portable application that means that you have to always explicitly run the file that you just downloaded, because if you created a quick access for a previous version, that shortcut will point to the previous version no matter what. This could be worked around if you extracted all the new files on the same pencil2d folder you had before, but honestly It's better to just delete the previous version and run the new one.

Also, be careful when copying and pasting, pressing CTRL + A will select the entire frame. While only manual selections will copy the specific area you selected. The older version 0.6.2 had copy pasting issues that were fixed, but even if you created the file there, the issue does not stay with the file since it was a problem with the base software, and not how the files were created.

Please try out to clean your computer from any previous Pencil2D versions and use the latest one to let us know if the problem persists or not.

Also please let us know what is at least your current operating system, as this helps to narrow down the root cause of every issue we encounter.

**Comment by Jose-Moreno** [comment] 2019-10-01 01:34
Hi, it's been a while. Without further information we can't do much here as copy pasting issues were fixed in previous versions. Please download the latest version (0.6.4 at the time) at http://pencil2d.org/download and try out the export again. If you still have issues please comment back in this thread and reopen it with more precise information as well as uploading the problem file to a file hosting service so our developers can inspect the issue in detail.

**Closed by Jose-Moreno** 2019-10-01 01:34 UTC
Labels: investigate, more info, tool: move-transform
