### ISSUE TITLE
[BUG] LOOP shortcut' icon doesn't work properly

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#299] opened 2015-04-09 02:26 UTC
Pencil2D build with MasterCode 08APRIL2015
WIN8.1

The LOOP functionality works just fine. Its icon is not working fine.
Example:
- Open Pencil2D
- Add several frames (no need to draw anything)
- Use the PLAY button' shortcut key. It should start playing the animation from frame One. When reaching the last frame it will stop. Everything OK till now.
  Now select the LOOP checker-box arrow manually (without the help of its shortcut) and click the PLAY button again. Now using the SHORTCUT KEY turn OFF the LOOP.
  Result: the animation will stop at the end of the last frame BUT the LOOP icon will continue ON, and will remain so till you deactivated it by clicking on it.

LOOP-tool works fine despite the state of this icon.

**Comment by Jose-Moreno** [comment] 2016-02-04 22:55
@tasaif  I've confirmed this bug to also exist in Nightly Build JAN 15 2016.

It seems that the Timeline Loop Button state is only working with the Animation Menu > Loop Button state in one direction. The Looping functionality works in each case as reported previously.

When you press or unpress the Timeline Loop button, the Menu Loop Button changes as expected. However the button state in the timeline is not synchronous when activating the loop button from the menu (or using it's assigned shorcut CTR+L, as was reported originally).

**Comment by tasaif** [comment] 2016-02-05 00:21
Got it, thanks for looking into this

**Comment by Jose-Moreno** [comment] 2017-04-13 06:47
@chchwy @CandyFace This bug has been fixed on latest builds for Windows ever since Nightly from Nov 2016. Please confirm on MAC / Linux if possible and close this.

**Comment by CandyFace** [comment] 2017-04-13 07:22
I can confirm that it works on mac. Closing this.

**Closed by CandyFace** 2017-04-13 07:22 UTC
Labels: bug
