### ISSUE TITLE
"UNDO" 

### ISSUE THREAD

**Issue by otto-reis0210** [pencil2d/pencil#1403] opened 2020-07-24 11:11 UTC
my english is not very good .. i am turkish
ANYWAY
I liked the pencil 2d application.
but i have a serious problem
"undo" button
not working.
constantly restarting the application
After a while he started to squeeze.
sometimes I can't see anything I draw sticks.
please find a solution.
I'm going crazy every day
#1052 
#352 
#105 
#36

**Comment by davidlamhauge** [comment] 2020-07-24 11:45
Hi @otto-reis0210 ,
Sounds odd. 
Undo is working, both via the menu and the shortcut (Ctrl-Z for Undo, Shift-Ctrl-Z for redo).
What Undo button are you referring to?

**Comment by Jose-Moreno** [comment] 2020-07-25 02:16
@otto-reis0210 Hi. Sorry to hear you are having issues with Pencil2D. Please answer these questions so we have more information to find the cause of the problems. Also if you have a specific file that is always crashing for you, please attach it as a ZIP file here.

1. What version of Pencil2D are you using?
![image](https://user-images.githubusercontent.com/4912907/88446650-714e7100-cdf1-11ea-8f0d-d03d987c4a93.png)
2. What is your current operating system?
3. What are your computer hardware specifications? Example: AMD fx-6300 CPU  with 6 cores, 16GB RAM, Wacom Intuos Tablet, etc
4. Are you working with vector layer or bitmap layer?
**Note:** If you're working with vector layer, please don't use it can crash the application in weird cases. The layer is broken and it will only be fixed AFTER the bitmap drawing engine is replaced to have brushes and presets per tool.
5. IF you're using the smugde tool or blur tool, please don't use it anymore. It is known to crash the application if you undo or under weird circumstances.
6. Trying to delete the first keyframe of any layer can sometimes lead to crashes. Always leave at least the first keyframe in position. This will change in the future.

**Undo / Redo will be improved in the future**, there are already advances for this feature, but it will probably not be available until next year.

If you need to finish your work and get rid of the frustration the crashes cause you, for now I can only recommend looking into another software meanwhile Pencil2D is fixed. Consider taking a look at this list and try other applications that will help you continue your work:

https://pencil2d-software.tumblr.com/post/184584013311/alternative-desktop-animation-software-pencil2d

**Comment by scribblemaniac** [comment] 2020-10-09 01:36
Closing due to lack of further information from the user. Based on the fact that they mention the application restarting, it could have been a crash-on-undo issue like #843, #1096, #1412, etc. In any case, it will likely be fixed when the undo/redo branch is merged.

**Closed by scribblemaniac** 2020-10-09 01:36 UTC
Labels: More Info, Undo
