### ISSUE TITLE
Filled area of a bitmap layer seems to have different layer order than it's layer.

### ISSUE THREAD

**Issue by aprekates** [pencil2d/pencil#684] opened 2017-06-04 12:41 UTC
### --Actual Results
In a new canvas.
Draw in the bitmap layer a horizontal line with the brush tool (lets say red)
Create a new bitmap layer and select it.
Draw again with the brush tool a black area.
Use the bucket to fill the area with another color.
Now make the layer with the filled area first in the stack (lower)
The line seems to be in front of the oultine but not the filled area.

### --Expected Results--
I'd expect the line to be in front of the lower layer.

### --System Information--
+ Pencil2D Version:  02/11/16 Build

+ Operating System:
Windows 10

+ RAM Size:
8 GB

```
-->

**Comment by Jose-Moreno** [comment] 2017-06-04 18:35
@aprekates This is not exactly a bug, it's an intended feature that seems to never have been fully developed by the original author of pencil. Usually when you are working on any production coloring can become difficult particularly if you require to fix colours after applying the paint. You can do this in TVPaint as well, where you can choose if you want to colour a layer below the linework, or in the current layer with the linework.

Pencil2D has a workflow where you can have your lineart and your colour separated (that's why automatically bleeds the color down one level). However I'd argue that since the feature is not explicitly advertised we should enhance this further, giving the user the option to change between behaviours. It's important that the user always know what will happen.

I think implementing this shouldn't be difficult as it is, but this feature should come as a part of fixing the whole bucket fill tool and the bitmap engine. With that said however the bitmap engine has not been pursued much more because we want to implement MyPaint library to handle the bitmap graphics. I think the fill tool should still need some work for the vector engine though, and there hasn't been much progress on the MyPaint lib integration for about 10 months, so we're at odds with that.

As for related bugs with this /feature requests associated with this issue, i'll write some of my own:

1.The "solo" / isolate layer function should help with this, but it doesn't so we should also consider this when improving the feature.
2. Also there's an issue with the undo function. When the color bleeds to the following layer you can't undo the fill, which is inconvenient. However if you fill the lineart on the same layer you will be able to undo normally (i'll make a separate report about this in due time)

**Comment by aprekates** [comment] 2017-06-04 21:34
Thanks for the feedback.

My argument is that since this is mainly a simple animation with not steep learning curve it'd make
sense to remove that half-implemented feature and make it optionally available when it's ready.

**Comment by CandyFace** [comment] 2017-06-15 14:33
duplicate of #524, closing.

**Closed by CandyFace** 2017-06-15 14:33 UTC
