### ISSUE TITLE
New implemented sound import formats are not properly loaded.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1452] opened 2020-09-05 22:18 UTC
### Issue Summary

In 0.6.5 new sound formats were added to allow for their import. However so far from my testing the following types don't work:
+ OGG
+ FLAC
+ WMA
+ AIFF (I have a sample that imports fine and another one that doesn't, probably a similar setting as the issue with )
+ AAC
+ OPUS (Opus files by default run disgustingly slow on Windows 10, but this problem aside, Pencil2D just won't load the samples)
+ CAF (Have not tested CAF but i'm pretty sure it doesn't work either)

The weird thing is that the files are actually stored in the PCLX / PCL data folders, and if I play back those sound, they are properly played by VLC. The only one that wasn't was the OGG file that I used.

### Expected Results

All provided sound formats should work, not only load into the file, but load in the timeline and be able to be played back and scrubbed normally like WAV or MP3 files.

### Video or Image Reference

![image](https://user-images.githubusercontent.com/4912907/92314305-7e877f80-ef9b-11ea-8d55-ab3e3d02d453.png)
_The single keyframes is a sign of limited success_

### Steps to reproduce

1. Open Pencil2D
2. File > Import > Sound >Create New Sound Layer
3. In the file explorer > Choose a sample for each of the mentioned filetypes. Please do note if certain filetypes work on macOSX or Linux distributions as I haven't tested that (e.g Opus)

### System Information
+ Pencil2D Version:
Nightly Build Sep  4 2020

commit: 09190a77649b69a7e5497768a1544762bfaf6e23
date: 2020-09-05_00:07:49

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

**Comment by Jose-Moreno** [comment] 2020-09-05 22:23
Here's a file with test sounds that don't work so you can inspect the data folder 
[sound_issues.zip](https://github.com/pencil2d/pencil/files/5178761/sound_issues.zip)

**Comment by scribblemaniac** [comment] 2020-09-06 06:20
Alright. I've tested this and I believe I've found the issues. There are actually two problems here:
1. Following the reproduction steps exactly, there is an importing error caused by #1449 which may cause a crash or do nothing depending on the build settings. This should be fixed as of commit d7b578f and you can test this on any build after that and it should import and playback all these formats just fine (note: this does not fix #1449).
2. If you try to import audio with the Add Keyframe button, menu item, or shortcut on a sound layer, the audio conversion step is not triggered and it may or may not playback successfully depending on the codecs your platform supports. This is a bug and I will assign myself to fix it.

**Closed** 2020-12-27 06:25 UTC
Labels: Bug, File Import, Sound
