### ISSUE TITLE
[ISSUES] Making changes to the UserInterface Panels some changes will not be saved when restarting Pencil

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#744] opened 2017-08-28 01:39 UTC
### --Issue Summary--
I have played with some panels on the User Interface, and most of them can be changed its size and position on the canvas.
This is just explaining what I got and hopefully it will show some inconsistencies on most of the Panels and even in some of the options inside them.

None of the following situations are an Issue _per si_, but I believe it is worth to mention.

_Panels attached to its default location:_
Changing the _**WIDTH**_ of any panel [Color wheel, Color Palette, Display, Tools/Options] will remain saved when restarting Pencil2D
When changing the **_HEIGHT_** of the panels, the **_DISPLAY Panel_** will be _the only one_ to remain saved when restarting Pencil2D

_Panels detached to its default location:_
Changing the Width or Height of any panel will remain saved when restating Pencil2D

_Changes inside Panels:_
Color Palette. Changing the presentation of the swatches will not be saved when restarting Pencil2D
Color Wheel. Changing RGB to HSV will not be saved when restarting Pencil2D. Also when changing colors it will bring BLACK as default
Tools. The Pencil tool will always be active when restarting Pencil2D, even when selecting another tool

### --Expected Results--
Any change on the width or Height of any Panel should be saved when opening Pencil2D next time. The same goes to any modification inside the Panels meaning for instance when selecting the BRUSH tool as a preference tool will allow to restart Pencil2D with this tool already selected

I think this is the way to go
;)
👍 

### --System Information--
+ Pencil2D Version:
Last build 27August2017

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

**Comment by Kaikogf** [comment] 2017-08-31 17:11
I forgot to mention that the same thing happens when resizing the camera to a different default size, it will not be saved.
:(

**Comment by Kaikogf** [comment] 2017-11-07 05:05
A similar behaviour from **_Nightly Build Nov 7 2017_**

Selecting a different "Interpolation feature" (on the Option's panel) will not be saved when restarting Pencil2D

**Comment by scribblemaniac** [comment] 2017-11-07 23:35
The panel layout is saving fine for me, including the height of the other panels. Can you provide some specific steps to replicate?

As for the changes within panels, I agree most of these should be saved, but it would be better if we did that after refactoring the Preferences module. I don't think the starting color should be saved though, and I can't think of any other programs which do that either.

**Comment by Kaikogf** [comment] 2017-11-08 03:46
Do you mean the starting colour to be always Black? I agree. I just mention that the black colour was used as default starting colour

My last comment was referring to changes within the **_Options_** 's panel: the selection made on the new bar "No Interpolation or Simple Line Interpolation or Strong Line Interpolation" will not be saved when restarting Pencil2D. Meaning that when selecting _Strong Line Interpolation_ for instance and restarting Pencil2D it will bring back the _No Interpolation_ option.

Thanks

**Comment by Jose-Moreno** [comment] 2018-06-16 16:32
@Kaikogf Can you test if this issue still happens for you on the latest development build? also, as for your lat comment the "line interpolation" feature saves now as of Mach builds. So if possible review your issue and close it if you're satisfied :slightly_smiling_face:

**Comment by Kaikogf** [comment] 2018-07-02 13:02
@Jose-Moreno 
:)

Great improvements here! All panels changes are now saved when resizing its height and width

About the "line interpolation", here is an issue:
The BRUSH tool is working fine and any change from the Stabiliser (none, simple, strong) is correctly save when opening pencil2D again.
The PENCIL and PEN tool Stabiliser are working together, meaning that if selecting **Strong** for the _Pencil_ tool and now going to the _Pen_ tool and selecting **None** and closing Pencil2D, it will open again with the last selection for BOTH tools ;)

Simple to test it.


Great work into pencil2D ! :+1:

**Comment by Kaikogf** [comment] 2018-07-02 17:23
@Jose-Moreno 
..."but the value is not shared for the Pen tool."
Not exactly. Wherever tool you choose at the end (pen or pencil) its value will be shared with the other tool...

**Comment by Kaikogf** [comment] 2018-07-02 17:46
@Jose-Moreno 
I think my words are not understood correctly. When I say value I am meaning none simple strong.  
Picking up None for (lets say the Pen tool) and Simple for the Pencil tool will make the Pen tool to have the Simple "value"

**Comment by CandyFace** [comment] 2018-07-02 19:08
The reason it's not being shared with brush is caused by a typo :3
Otherwise that tool would also have its values shared with the other tools. That doesn't make sense though.
pull request coming up soon.

**Comment by CandyFace** [comment] 2018-07-02 21:13
Fixed in #1007 

> The BRUSH tool is working fine and any change from the Stabiliser (none, simple, strong) is correctly saved when opening pencil2D again.
The PENCIL and PEN tool Stabiliser are working together, meaning that if selecting Strong for the Pencil tool and now going to the Pen tool and selecting None and closing Pencil2D, it will open again with the last selection for BOTH tools ;)

**Comment by CandyFace** [comment] 2018-07-03 05:42
Any other remarks regarding this issue before I close it?

**Comment by Jose-Moreno** [comment] 2018-07-03 19:04
@CandyFace Most of the UI issues discussed in the original post were solved in recent updates along the fix you pushed for the stabilizer problem. So I think this can be closed now. Thank you for stepping in! :smiley:

**Closed** 2018-07-03 19:04 UTC
Labels: bug

**Comment by Kaikogf** [comment] 2018-07-03 19:19
Yes, it is all good now. Thanks @CandyFace @Jose-Moreno
