### ISSUE TITLE
[BUG] Pencil2D keeps opening a "save changes" window after some clickings on the canvas

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#782] opened 2017-11-07 04:54 UTC
### --Issue Summary--
The title says it all

### --Steps to reproduce--
Just open Pencil2D and tip several times on the canvas (around six times will trigger the issue): Pencil2D will open a window for "saving the animation" (?)
Close the window and repeat the steps again 

### --System Information--
+ Pencil2D Version:
Version used: **_Nightly Build Nov 7 2017_**

+ Operating System:
Windows 8.1 

+ RAM Size:

+ Graphics Tablet:
Huion tablet

**Comment by Jose-Moreno** [comment] 2017-11-07 05:13
@Kaikogf This is not a bug, but a rather annoying by product of the autosave feature which wasnt working until now. 

The auto save can't work properly unless you save the work for the first time saving every number of strokes (you change this on the preferences). But I did find some bugs with the autosave which I'll report later.

We should also think on how to properly trigger the autosave, because people normally don't tend to save before drawing, so this can appear like a bug to other users as well even though it's not.

**Comment by CandyFace** [comment] 2017-11-07 08:34
Autosave should save automatically and in the background, with no need for the user to do anything, so it's a bug imo.

**Comment by chchwy** [comment] 2017-11-07 08:40
But at the beginning, the app has no idea about where to save the file, so the file dialog will pop up at least once. This is inevitable.

**Comment by CandyFace** [comment] 2017-11-07 08:41
We could just have a autosave folder in documents or the like under Pencil2D/Autosaves or something and name the saves after the date.

**Comment by scribblemaniac** [comment] 2017-11-07 08:58
Yes, most programs do not autosave to the actual file. If a user opens a file, makes a bunch of changes without saving, and then decides they don't want to save those changes, they would expect that quitting without saving would have not modified the file at all. With the way it is implemented now however, the autosave will have overwritten their file, which is not ideal. It's better than not having autosave at all, but it's worse than a proper autosave to temp directory + crash recovery.

**Comment by chchwy** [comment] 2017-11-07 09:18
So at the moment, the auto-saving is an option in preference. Users can turn it off if they don't want to overwrite current file. If the option is on, users must be aware of the auto-saving is constantly overwriting the file. 

And the file saving may take plenty of time especially when there are hundreds of frames. So if the auto-saving goes in the background, we have to deal with data consistency.

Crash recovery is another feature that can be implemented, but it is not necessary to be related to auto-saving.

**Comment by CandyFace** [comment] 2017-11-07 09:25
Alright so if we're keeping it this way for now, then it should at least be a choice by the user to save and thus enable autosave or not. The window shouldn't popup by itself, as the user won't understand the behaviour.

**Comment by CandyFace** [comment] 2017-11-07 09:46
@scribblemaniac i'm saying that even if we have a toggle to enable autosave in preferences, it should still be up to the user when the first autosave should happen. I agree that it creates the potential problem of the user forgetting to save the first time, risking their work being deleted but it's less verbose than triggering a popup out of nowhere. 

if the user has no intention of saving in the beginning, it's going to be annoying to close the popup every x click.

**Comment by chchwy** [comment] 2017-11-07 09:56
Maybe we can pop up a dialog when a user clicked `new document`, and ask the user whether he/she want to enable auto-save or not. (Most of painting softwares have a pop-up dialog before you can actually draw something).

**Comment by CandyFace** [comment] 2017-11-07 10:07
Asking the user, no matter when, to save their document is not ideal imo. There are plenty of times where one opens a document, makes some doodles and closes it again without saving. If autosave adds this behaviour, then it should be clarified that the user will be forced to save their (empty document) when they create it. To be that seems unnecessary. 

I would rather control myself when to save and thus start autosaving than having potential empty documents being created on my desktop.

**Comment by Kaikogf** [comment] 2017-11-08 03:20
Glad you all agree to agree :)
👍 

Best regards

**Comment by chchwy** [comment] 2017-11-14 12:36
Hey guys,

In the 14 Nov 2017 build, I added a **"Never ask again"** button on the autosave reminder. So if you are working on an unnamed new animation, the reminder will no longer annoy you after pressing the "Never ask again".

I think it's a compromise before a proper crash recovery is implemented in the coming future.
Please let me know If you have any better ideas. I'm gonna to close this issue.
Cheers.

**Closed by chchwy** 2017-11-14 12:36 UTC
Labels: question

**Comment by Kaikogf** [comment] 2017-11-15 03:15
Simple and efficient idea for this "issue".

I believe it is the best solution in case someone will check the auto-saving without knowing exactly how it is going to work. 
And to be honest @Jose-Moreno was the one to point exactly the real issue behind this behaviour: the check box for auto-saving was always on... 👍
