### ISSUE TITLE
File open dialog appears behind application window

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1259] opened 2019-09-02 17:58 UTC
### Issue Summary

In certain versions of Pencil2D on Linux, the file selection dialog used for importing, opening, and exporting shows behind the main application window when opened.

### Expected Results

The file selection dialog should always appear in front of the main window when opening up.

### System Information
+ Pencil2D Version: v0.6.4

I have noted this behavior in the flatpak version, but not in the appimage version, and not when building the current master from source. It may be specific to this release.

+ Operating System:

Ubuntu 19.04

**Comment by J5lx** [comment] 2020-05-26 21:35
I started looking into this but I really don’t see what we might be doing wrong here. The request for the file dialog seems to conform exactly to [the specification](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-FileChooser.OpenFile) as far as I can tell. For reference, here’s the method call issued by Pencil2D:

<details>
<summary><code>OpenFile</code> method call issued by Pencil2D</summary>

```
method call time=1590524302.206735 sender=:1.144 -> destination=org.freedesktop.portal.Desktop serial=20 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=OpenFile
   string "x11:35651590"
   string "Open animation"
   array [
      dict entry(
         string "filters"
         variant             array [
               struct {
                  string "All Pencil Files PCLX & PCL"
                  array [
                     struct {
                        uint32 0
                        string "*.pclx"
                     }
                     struct {
                        uint32 0
                        string "*.pcl"
                     }
                  ]
               }
               struct {
                  string "Pencil Animation File PCLX"
                  array [
                     struct {
                        uint32 0
                        string "*.pclx"
                     }
                  ]
               }
               struct {
                  string "Old Pencil Animation File PCL"
                  array [
                     struct {
                        uint32 0
                        string "*.pcl"
                     }
                  ]
               }
               struct {
                  string "Any files "
                  array [
                     struct {
                        uint32 0
                        string "*"
                     }
                  ]
               }
            ]
      )
      dict entry(
         string "handle_token"
         variant             string "qt479871533"
      )
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "multiple"
         variant             boolean false
      )
   ]
```

</details>

The parent window id supplied by Pencil2D is also correct, I checked that. Additionally, the open dialog shows perfectly fine in KDE, this issue is only present in GNOME (both on Ubuntu 19.10 and Arch).

At this point I’m positive that this is not a bug in Pencil2D. I’m quite certain that the real culprit here is xdg-desktop-portal-gtk (namely this issue: flatpak/xdg-desktop-portal-gtk#306) and I’m inclined to close this issue as invalid/not-our-bug – or should we still keep it open for now? @scribblemaniac

**Comment by scribblemaniac** [comment] 2020-05-28 05:16
@J5lx I agree with your assesment that this is caused by the linked issue. However, there may be a way we can work around it. I was thinking that something like this would work:

In `FileDialog::openFile`, replace the call to `QFileDialog::getOpenFileName` with something like this:
```
QFileDialog openDialog( mRoot, strTitle, strInitialFilePath, strFilter );
 openDialog.open();
 QApplication::setActiveWindow(openDialog.window());
```
Obviously there will be a bit more to it than that as we will have to connect to the signal to get the result wherever that is used, but that is probably a better thing to do anyway.

Unfortunately (or maybe fortunately), I am unable to reproduce this issue with the flatpak version on Ubuntu 20.04, so I am unable to test if the above code would fix the issue. Can you maybe try this?

**Comment by J5lx** [comment] 2020-06-02 15:45
Hmm, I’m not sure if I like that sort of workaround, but it could certainly work. I’ll give it a try when I find the time.

**Comment by J5lx** [comment] 2021-09-19 14:49
This issue [has been fixed](https://codereview.qt-project.org/c/qt/qtbase/+/337969) in Qt 6.1+, and the fix has also been [backported to the Qt 5 Flatpak runtime](https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/36) a while back. Closing.

**Closed by J5lx** 2021-09-19 14:49 UTC
Labels: Bug, UX, Linux, Not Our Bug
