### ISSUE TITLE
Audio almost always lags when when pressing play. i have to go to the start of the animation and press play a few times and only then the audio works.

### ISSUE THREAD

**Issue by DWDemon** [pencil2d/pencil#1227] opened 2019-06-19 13:44 UTC
### System Information
+ Pencil2D Version:

 v.0.6.4? i just downloaded the newest one

 

+ Operating System: 
windows 10
 

+ RAM Size: 

8.00GB

 

+ Graphics Tablet: 
wacom intuos pro

**Comment by Jose-Moreno** [comment] 2019-06-19 19:32
@DWDemon Well this depends on many variables and actually the behavior you're describing is meant to happen like that for the animations previewed in the editor. In Pencil2D there's a feature called the "image cache pool" basically it helps compensate when your computer has lower resources to spare so it "pre-loads" the images. But the only way to do it is by playing back the animation so the "cache" is created.

The image cache is set to 200 images by default but you can increase this number, however we only recommend this if your computer has a LOT of RAM (e.g 8~16+ GB)

Now, the issue where the sound is lagging that's a new one. I'm not sure if the pool cache also effects the audio, and while it wouldn't surprise me, I'll ask the other devs to see if this is true or not. Depending on that we can further investigate this problem. 

However, please, edit the issue and fill it with the info we ask of you on the template. We at least need to know:
1. What is your current version of Pencil2D
2. What is your Operating system and it's version
3. And record a video of the problem to see how the sound lags, and upload it to streamable.com (which can be done anonymously) so everyone has a better chance to find the cause of this, otherwise it will take a long time to get work done.

**Comment by SanoStar** [comment] 2019-10-02 04:41
Hello this is my first time participating in debug forums.
I just ran into an issue where Audio won't properly play unless I play it from the beginning.
I was writing down the lyrics to the song to keep track of the timing and aligning the keyframes to the song beats, however when I'd play in the middle of the song it would add about +5 secs to the misalignment of sound and timeline every time I paused and played. (Pause +5 sec off)

Now I have to play the sound from the beginning every time if I want it to be accurate, and it's REALLY off otherwise.

This is my first time providing a video example of an issue, I hope it works.

[SoundLag.zip](https://github.com/pencil2d/pencil/files/3679489/SoundLag.zip)

**Comment by Jose-Moreno** [comment] 2020-07-30 07:02
@SanoStar A new release will be shipping soon with what the developers consider fixes this problem. I'm closing this issue and we ask you to test the new release next week. If you'd like you can also test a development build closer to the release here:

**Windows 64 bits** https://drive.google.com/file/d/1JQ6-Hp_nt9XWPwJh4vOyusDEb-VhRSJC/view?usp=sharing

If you still continue to have this problem let us know in this same thread and we will re open this once we've tested your new report. Thank you for your patience.

**Closed by Jose-Moreno** 2020-07-30 07:02 UTC
Labels: investigate, more info, sound
