### ISSUE TITLE
The program turned off by itself

### ISSUE THREAD

**Issue by BillyCort1** [pencil2d/pencil#1669] opened 2021-10-16 20:02 UTC
### Issue Summary

The program turned off by itself, I didn't do anything, it just turned off. if I accidentally clicked alt f4, it would show me whether or not to close, I did it for 10 hours without a break and at the end it turned off by itself.

 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment] 2021-10-17 01:13
@BillyCort1 Hi. Thank you for your submission.

First off it is recommended not to consider closing the software by pressing ALT + F4. Secondly, the program might have closed off because the amount of memory needed for a 10 hour session without breaks exceeded your current hardware RAM size. 

However that said such issue has only been verified to happen if you either never saved your work or if you had gigantic images and a lot of them too. 

If you save your work at least once and then let the autosave function kick in you can work for an entire day without issues (some users have reported leaving their Pencil2D software open overnight without problems).

From your description, we simply don't have enough information to help developers understand what was the problem since there's a mix of several potential behaviors that could make this happen, so instead to prevent you from experiencing this issue again here are some of my personal recommendations:

1. Always save a newly created Pencil2D document before you start to work on it, then activate the autosave function in **Edit > Preferences > Files**
2. For lengthy animation, separate the animation in scenes and save each scene as a single Pencil2D file. This also helps editing later down the pipeline, and in case your files get corrupted you only lose one scene and not all the animation.
3. Always save a backup copy of your project file after reaching important milestones. You should have as many backup copies as milestones for a single daily session of work.
4. From a technical and academical perspective try not to over saturate your Pencil2D file with many layers and many frames, try to use just enough to describe the motion. If you are going to add sound, it's better to rely on adding the audio in a video editor _after_ the animation is done. In Pencil2D the sound you add should only be necessary for dialogue or syncing to the beat of a music track.
5. Do take breaks. It's important for your health.

**Comment by chchwy** [comment] 2021-10-20 01:24
Hi, @BillyCort1 `Alt + F4` has been the keyboard shortcut of closing an app since a long time ago.

Please check the Windows keyboard shortcuts here:
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec

**Comment by J5lx** [comment] 2022-06-05 21:36
Hi, since your report doesn’t contain enough information for us to figure out what went wrong, I’m closing this issue. Please let us know if you can provide further information that can help us track down the cause.

**Closed by J5lx** 2022-06-05 21:36 UTC
Labels: More Info, Crash, No reply
