### ISSUE TITLE
[BUG] Pencil shows save changes dialog twice when opening a file.

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#548] opened 2016-10-16 07:48 UTC
### --Issue Summary--

When opening a new file without saving your current file, Pencil will ask you to save your changes before opening the file browser and then it will ask again after selecting the file you want to open.
### --Actual Results

When I try to open an existing file without saving my current file, I get the save prompt first before Pencil shows me the file browser and after selecting a file to load, but before the loading operation for the new file.
### --Expected Results--

It would make sense just to make it ask before opening the new file.
### --Steps to reproduce--
1. create new file
2. Draw a stroke
3. Go to File > Open, and select a new file to load.
4. Pencil will ask you to save your changes. Pick either Yes or No. In my test I chose "No".
5. Pencil will pop the file browser. Select the file you want to load and press "Open"
6. Pencil now will ask you to save your changes "again". I picked "No"
7. The new file loads.
### --System Information--
- Pencil2D Version:
  Nightly Build Oct 10 2016
- Operating System:
  Windows 7 Ultimate 64bits
- RAM Size:
  4GB
- CPU:
  AMD Phenom II x4 965 BE

**Comment by chchwy** [comment] 2016-11-10 11:06
should be fixed, need to verify in next nightly build

**Comment by CandyFace** [comment] 2017-04-11 17:04
I can't reproduce this anymore, confirmed fixed. Closing.

**Closed by CandyFace** 2017-04-11 17:04 UTC
Labels: bug, testing

**Comment by Jose-Moreno** [comment] 2017-04-12 02:12
I can confirm this has been fixed in the latest build for April 11 on Windows 7.
