### ISSUE TITLE
Drawing Bug

### ISSUE THREAD

**Issue by OllieJD** [pencil2d/pencil#535] opened 2016-09-21 04:27 UTC
For Mac tablet users, the drawing tool is incredibly slow and hard to use. The rotating tool turns on randomly at will as well. Please fix this. 
Other than these minor complaints, this open source animation software is terrific.

**Comment by Jose-Moreno** [comment] 2016-09-21 05:15
@OllieJD Hi, can you be a little more specific? I's is usually good practice to state the following on your bug reports:

1) Software Version (Go to Menu Help > About > Copy paste version number as well as displayed build date if it's a Nightly Build)
2) Drawing Hardware Specs: Tablet Brand, Driver Number (e.g. Wacom Intuos 5 driver v 6.3-15)
3) Hardware Specs (e.g. AMD Phenom II X4 965, 4GB RAM, Graphics Card: y/n , etc)
4) If it's a particular bug try to summarize how and when are you experiencing it. (i.e Everytime I use tool A, after doing action X, bug happens)

This way developers can pinpoint the issues faster, otherwise it becomes a "needle in the haystack" kind of problem.

Now regarding Pencil version 0.5.4b it has been reported in the past that there's lots of issues with newer upgrades of MAC OSX. If you're using this version of ]Pencil2D please try to download and test a recent Nightly Build for your OS here: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM#list

Regarding the rotation functionality there's two different "rotation tools": The canvas / view rotation and the marquee selection rotation. Please specify which are you referring to. However try to test first with the Nightly Build to see if the issue is resolved for your case.

Thanks for understanding and let us know what happens good or bad. Take care

**Comment by J5lx** [comment] 2016-09-21 16:30
@Jose-Moreno This is a bit off-topic, but have you considered setting up [an issue template](https://github.com/blog/2111-issue-and-pull-request-templates) with that list you gave (software version, hardware specs etc.)? That would be an efficient way of letting new contributors know what info is needed.

**Comment by Jose-Moreno** [comment] 2016-09-22 00:14
@J5lx Hey! Thanks for the suggestion. Actually there was one (although not as in-depth) in the forum. But it seems noone really reads the forum these days. I'll try to make a downloadable template or post it on a page on the website and pass it on through the social media through the mods. Thanks again for the idea! :smile:

**Comment by J5lx** [comment] 2016-09-22 05:53
@Jose-Moreno Actually I meant a GitHub issue template that is automatically filled into the issue creation form right here on this site. The blog post I linked contains details about that.

**Comment by Jose-Moreno** [comment] 2016-09-25 14:34
@J5lx I'll look into it, I don't have admin rights, but once I get the template made I'll pm the admin to use this. Great idea and thanks a lot for suggesting it!

**Comment by CandyFace** [comment] 2017-04-11 12:38
This was fixed in #345, closing.

**Closed by CandyFace** 2017-04-11 12:38 UTC
