### ISSUE TITLE
Ctrl+Mousewheel causes freezing instead of zooming

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#333] opened 2015-08-13 21:46 UTC
This issue occurs only in the nightly build, not in 0.5.4.

**Comment by carlosgf** [comment] 2015-08-13 22:43
This issue is also related to the  #307 issue

**Comment by Spark01** [comment] 2015-08-15 21:44
This was evidently fixed in the dev branch. Should I go ahead and close it?

**Comment by carlosgf** [comment] 2015-08-16 02:31
I was not able to reproduce your issue (I am using a Pen-tablet, no-Mousewheel). If you tested it and it was OK, you should close it

Thank you

**Closed** 2015-08-16 05:09 UTC
Labels: bug
