### ISSUE TITLE
Problem zoom  version Nightly Build

### ISSUE THREAD

**Issue by zarco1794** [pencil2d/pencil#1286] opened 2019-10-24 09:38 UTC
I try zoom in zoom out, , this action not work very well 

 Actual Results
The tool zoom not work very well when using the pen 

Expected Results
The zoom in and zoom out to be should fluid when using the pen

hint: Explain how the function should behave in the context you're using it.
when trying to zoom You can not properly control the function of the tool when using the pen
But yes work when using mouse

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/39812147/67473819-bc044800-f629-11e9-932c-4650cd8d44bd.gif)

<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/U8Rk9JrgK6VMiFaMP3" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/U8Rk9JrgK6VMiFaMP3">via GIPHY</a></p>

### System Information
+ Pencil2D Version: Nightly Build 2019-10-07

+ Operating System:
+Windows 7 64 bits
+ RAM Size: 8 Ram
+Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
+ Graphics Tablet: AMD Radeon R7 200 Series
+Wacom Intuos S

**Comment by Jose-Moreno** [comment] 2019-10-24 16:05
@zarco1794 This bug happened to me before in previous versions but the devs had fixed it. I also was using a Genius MousePen 8x6.

1. First thing, please make sure you are using the latest drivers on your Wacom Intuos S, and also please check that the "Windows Ink" option is turned off.

2. Next please try the stable release (0.6.4) does this happen to you in that version as well?

3. Additionally, in the Nightly Build try to zoom in / out in a new blank file and let us know if the same behavior that you show in the GIF happens when zooming in the new file. I'm asking this because there was an explicit problem with the zoom when the drawing goes outside the camera frame borders and beyond the canvas visible area, which produces visible stuttering when using the zoom tools and I have yet to report it as well.

4. You mentioned that with mouse the zoom is working. Can you go to your wacom intuos driver settings and enable the "mouse mode" and see if this also "fixes" your problem? (Don't leave the mouse mode enabled afterwards or your tablet won't work as you expect it. This is only to check if the mouse events vs tablet events are causing this problem)

![image](https://user-images.githubusercontent.com/4912907/67503858-fb449000-f64d-11e9-9803-3a785ef31b82.png)

We'll be pending confirmation on your behalf to continue troubleshooting this issue. Thanks!

**Comment by zarco1794** [comment] 2019-10-27 15:52
I think the error is due to setting the camera with a resolution of 1920 x 1080. Create a new document with lower resolution and it is working fine

**Comment by zarco1794** [comment] 2019-10-27 16:04
I sorry, not resolution problem, i Open project in version stable, later quit and i open same project in Night Build, well work for seconds later the bug  happened again

**Comment by zarco1794** [comment] 2019-10-27 16:09
https://github.com/pencil2d/pencil/issues/1286#issuecomment-545988937 

Select this option ( mouse in Wacom Intuos) and work very well

**Comment by zarco1794** [comment] 2019-10-27 16:20
In Layer Camare the zoom work very well

**Comment by Jose-Moreno** [comment] 2019-10-27 22:55
@zarco1794 Thank you for taking the time to make these tests. 

Once the developers resume their work, I'll look into trying to replicate this problem so we can see if it's possible to fix it soon. 

So far we are aware that there is an issue when generating the mouse vs. tablet events in the framework that Pencil2D uses "under the hood".

If there's any update I'll comment here and let you know.

**Comment by Kaikogf** [comment] 2020-02-26 03:53
I managed to replicate this same issue. I also realized that the camera layer also brings the trembling zoom in/out issue, but noticed that if the frame is almost empty (just some line brushes on it) the smoother the zoom will be in that frame

**Comment by Jose-Moreno** [comment] 2020-03-01 21:46
After some tests, this is basically the same as #1169 . Similar to Kaiko and the OP, I'm also experiencing a regression with the same behaviors and tools as the cited issue, but now in the latest nightly build available in Google Drive (2020-01-09)

To expand the description:
I'm using both the Hand Tool and the Zoom behavior when using the drawing tools, and both have the same problem.

**Nightly build**
commit: 4a5f8b65a7679e7f23a87eb8c60b15f35a4cfc6a
date: 2020-01-09_10:40:27

Operating System: Windows 7 (6.1)
CPU Architecture: x86_64
Qt Version: 5.12.5

**Graphics Tablet**: Intuos Wacom 5 Small (PTH-450)
**Driver version**: 6.3.38-2 (latest available at wacom.com)

Notice that it says Windows 7 because i'm using the application with Windows 7 compatibility so my    tablet has working pressure with the latest drivers, **however** I'm currently using **Windows 10 v1809** and **even without the compability switch** the same issue occurs..

**Comment by Jose-Moreno** [comment] 2020-03-01 22:07
@Kaikogf @zarco1794 Hi, can you test this in the latest nightly build for 2020-01-09 but mapping MMB and RMB click to separate stylus buttons and testing each one individually?

As per #1189 Middle mouse button behavior is broken, so If you map and use the `Right Click` to Zoom when working with the stylus instead, this should work fine, however using Middle Mouse Click will bring this problem consistently. 

If possible can you both test and report back if this works for you or not? Thanks.

**Comment by Kaikogf** [comment] 2020-03-09 02:15
@Jose-Moreno 

Here the results:
win8.1x64bits
Imported an image (200kb) to the bitmap layer with a resolution camera 1920/1080, using the default shortcut keys.

(using CTRL key):
CTRL + RMB: the zoom in/out is trembling. Another issue is that the zoom is reset to a value of 1% every time the RMB is released and pressed again.
CTRL + LMB: the zoom is OK
RMB (moving the canvas): OK

(using SHIFT key):
SHIFT + RMB: the zoom is OK
SHIFT + LMB: the zoom is OK
LMB (moving the canvas): a slow issue (the icon is a close hand)

NOTE:
I noticed when pressing RMB alone, the icon tool is a hand fully opened. Pressing LMB the icon is a close hand.

**Comment by Jose-Moreno** [comment] 2020-03-09 03:46
@Kaikogf Well I asked specifically to test RMB and MMB, but this values help too.

If you can update the comment later, to add the MMB behavior, that'd work best. Either way thank you again for your time with these tests 😄

**Comment by Kaikogf** [comment] 2020-03-10 03:02
@Jose-Moreno 
Sorry my bad. Instead of LMB is MMB. I am going to edit last post. RMB will keep as RMB

**Comment by Jose-Moreno** [comment] 2020-08-30 17:30
This problem has been tested under Windows & Linux and was fixed by this commit https://github.com/pencil2d/pencil/commit/9e1555ebda8f4d365e7d6c1e7db96c58ba66e416 

@kaiko @zarco1794 please test the latest nightly build from August 30th and let us know how it works with both MMB and RMB. Additionally the zoom is now "targeted" so the canvas center will move towards the cursor unlike before where the canvas was always centered relative to the view :tada

**Closed by Jose-Moreno** 2020-08-30 17:30 UTC
Labels: Bug, Hand

**Comment by Kaikogf** [comment] 2020-09-03 13:34
@Jose-Moreno 
I tested it under similar conditions to my previous post, and it showed no real issues here. The zoom feature is lot more smoothly. 
I was not able to test it under the building code (not able to build it on my PC) so I used the last new version v.0.6.5

(using CTRL key):
•	CTRL + RMB: the zoom in/out is OK _[was trembling before this version]_
•	CTRL + MMB: the zoom in/out is OK _[was trembling before this version]_

(using SHIFT key):
•	SHIFT + RMB: the zoom in/out is trembling.
•	SHIFT + MMB: the zoom in/out is OK

Odd thing. And you mentioned it before @Jose-Moreno . I waited a little bit in order for the software to settle down (if that were even possible LOL) and tried the last commands shortcuts, but now everything was working fine, no trembling while using the zoom feature. Closing Pencil2D and open it again fresh will bring the trembling zoom when applying shortcut **_SHIFT+RMB_**.

**ISSUE:** the canvas is set to a random zoom value (usually lower than 10%) every time the MMB/RMB is released and pressed again while pressing CTRL. 
On the other hand, while pressing (SHIFT+RMB), it does not show that issue.

**Comment by Jose-Moreno** [comment] 2020-09-05 02:10
@Kaikogf Hmm I'm testing the latest nightly build. I tried with all the combinations you mentioned but none of them gave me "trembling" nor the 10% zoom issue. Can you please try the version from September 4th at least? And when you open Pencil2D please make sure you are using the development version and not an existing version just in case.

I do have one issue, but that seems to be unrelated to the zoom problem itself and i'll report it separately. When I press MMB with my stylus third button mapped to MMB, the application does not PAN automatically while hovering the stylus. 

I have to explicitly press the pointer button (LMB) to pan, but that's because the hand tool is already invoked due to pressing MMB. This does not happen with a mouse though and when i press CTRL in that "locked" state I can zoom normally.

There's also trouble when using MMB and ALT to rotate the canvas, but again this only happens with the stylus.

**Comment by scribblemaniac** [comment] 2020-09-05 04:40
I forgot to comment on this. Definitely test with the latest development build as at least the issue which @Jose-Moreno was having was only fixed after v0.6.5. Will look into it more if it persists in the newest nightly build for example.

**Comment by Kaikogf** [comment] 2020-09-07 13:51
So, here is the video reference
Strange thing but the issue related to the random zoom value is no longer present, so this video shows the trembling issue. 

Steps:
Imported an image, (build from day 5th/Set)


![Pencil2D](https://user-images.githubusercontent.com/28032931/92394337-473edd00-f119-11ea-9122-68625a8605f4.gif)


CTRL+RMB
CTRL+MMB
SHIFT+RMB
SHIFT+MMB

👍
