### ISSUE TITLE
[BUG] Pencil2D will show Runtime Error and close

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#930] opened 2018-03-29 03:23 UTC
Just do as following:

Open Pencil2D
Select the Polyline tool
Check the Bezier box > Pencil will show the error and close

[I checked the nightly build from 15Mar2018 and pencil showed no error]

Pencil v. 28Mar2018

Win8.1 x 64bits
32Gb
Huion tablet

**Comment by Jose-Moreno** [comment] 2018-03-29 04:42
According to the repro steps, this is a possible duplicate of #885

**Comment by chchwy** [comment] 2018-04-02 10:40
Fixed in 708d418

**Closed by chchwy** 2018-04-02 10:40 UTC
Labels: bug, polytool
