### ISSUE TITLE
Warning? 'cant read the file'

### ISSUE THREAD

**Issue by StarMelody** [pencil2d/pencil#1190] opened 2019-03-12 22:29 UTC
this only happened to 2 of my projects. It claims that they are images and not animations. I am a youtuber that does animations and I needed these 2 animations to be completed soon.

I've reopened these projects multiple times and it worked. all my other unfinished animations open normal. but only recently a few of my animations wont open.

<img width="960" alt="ffdfsfsdf" src="https://user-images.githubusercontent.com/48497020/54239580-d34a5700-44d8-11e9-887b-f77178e6eb9b.png">

uh... I click on the 'open file' thing and select my animation file and the picture above is what I get instead of it opening.

I use Version: 0.6.0
Windows 10
I think it was 4GB

i dont quite understand. I looked through all the other pencil2d files and they all worked. 2 of them wouldnt work. if there is any way to fix this, please help.

**Comment by StarMelody** [comment] 2019-03-12 22:38
scratch that. just updated to 0.6.2

**Comment by Jose-Moreno** [comment] 2019-03-12 23:54
@StarMelody If possible please share the files that can't be opened so the developers can inspect them. You can use any cloud hosting storage service you like and post the link here.

The warning you show on the screenshot used to happen before but the problem was fixed on most instances and people were able to open their files again. In your case it could be that the files have also been corrupted, which is why 0.6.2 is not opening them either.

**Comment by StarMelody** [comment] 2019-03-16 20:30
this one I am more concerned about. the other can be remade since i used an
old are style. please fix this file. thank you.

https://drive.google.com/file/d/13mcP8IlUx_CogvacGJ1_bsStw6ysqLgf/view?usp=sharing

**Comment by Jose-Moreno** [comment] 2019-03-16 20:48
@StarMelody Just FYI before anything else. Corrupted files can't be fixed, but we can try to recover most of what's in it, whatever that is. 

We have a guide to do the same thing I'm about to do in order to recover the work, but in any case it is impossible to recover the full animation with how the drawings are positioned on the canvas, unfortunately.

https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105

Nevertheless while I try it out please take a look at the give particularly the part about the temporary files folder, as it is more likely to recover a full snapshot of a previous version than anything else.

**Comment by Jose-Moreno** [comment] 2019-03-17 00:03
@StarMelody Alright I recovered what was in the file, I hope at least it's enough so it won't be a major setback for you. 

https://drive.google.com/open?id=1yFr3q8XnK8xq7m0gEQl_k2VGuTAJbM86

I found a couple drawings up to frame 200~ or so, a soundtrack and I put them as they were ordered. Note however that they are NOT properly aligned, you'll have to move the mouth, the eye and the girl's body to match what you had before, but at least now you won't have to redraw everything.

Make sure to use the latest development version found at http://pencil2d.org/download#nightlybuild.

Once you're done with your setup, please make another copy to keep that one as a backup and keep working with a few more extra copies until you're finished. That way you won't be suffering major setbacks in case the file corrupts again.

We'll be looking into a way to improve file recovery handling, so cases like this will be reduced to a minimum, but for now the best way to fight this is to prevent it as much as possible. Cheers.

**Comment by scribblemaniac** [comment] 2019-03-21 06:49
Closing as the project has been recovered and there isn't really any way to get more information on the cause of this.

@StarMelody If you encounter a file becoming corrupted while using the latest version (v0.6.3) please open a new issue.

**Closed by scribblemaniac** 2019-03-21 06:49 UTC
