### ISSUE TITLE
things needed to add in v0.6.7 which will make pencil 2d cool

### ISSUE THREAD

**Issue by Abhinav-ms-903** [pencil2d/pencil#1679] opened 2021-11-19 05:18 UTC
1.need to increase functionality of smudge tool in vector layer 
2.fix error in filling  on vector layer (i know pencil 2d focuses on bitmap but it will be great if solved)
3.add a bone  tool in bitmap and vector too
4. rotating the selection (i know that it is a hidden tool but most of the people wont know ... after research  only  i understand ctrl + rotate will help)
5. make able to move keys 
6. the poly-line tool  goes bended while drawing
7. make the fill tool effective  in bitmap layer
these 7 can make v0.6.7 better than animate.cc ,synfig,or blender

**Comment by scribblemaniac** [comment] 2021-11-19 08:52
In the Pencil2D project, Github issues have a very specific purpose. They are to either report *confirmed*, *individual*, *unique* issues with the program, or to report *individual*, *unique* features requests. Their purpose is to providing tracking of tasks for developers, not to provide support to users, we have other channels for that. If you want to post your wishlist of what you would like in the next version, this is **not the correct place** to do so. Our forums are better suited to discussions about problems you are encountering or for your to post your overall thoughts or ideas for the future of the program (we even have [a section for that](https://discuss.pencil2d.org/c/ideas/8)).

Both @J5lx  and I have pointed out problems with the new issues you are creating in this repository. I have tried to make it as clear as possible what these issue are and are not for, but if you are still confused you may ask for clarification on any of my points in a comment here. We welcome people to find ways to improve upon Pencil2D, but creating issues that do not conform with the rules we have laid out for Github issues is a drain on our developer's time and makes it more difficult to track. This is a warning that continuing to disregard these rules may result in your issues being deleted, reported as spam, or you being banned completely from contributing to the repository. I would not like to see it come to that, so I highly recommend you move your future issues/ideas to the appropriate section of our official [forum](https://discuss.pencil2d.org/) or [Discord server](https://discord.gg/8FxdV2g).

If you really want to continue posting issues here, they need to fit into one of the two categories I have listed in the first paragraph. In both cases you need to clearly and specifically explain what your issue or desired feature is. You need to have searched this repository's past issues thoroughly to assure that you are not posting a duplicate issue or request. For feature requests, provide examples of use cases and similar features from other programs. For any issues with the program reported, you should follow the template provided whenever you create a new issue, filling out all the specified areas so we can more easily isolate the problem. If it is a visual problem, share screenshots of the issue. Whenever possible, provide specific, repeatable steps to reproduce the issue. If you need examples of what good issue reports or feature requests look like, look at some of the issues files by myself or @Jose-Moreno. No always, but in general they are examples of the structure and level of detail that we would ideally like to see in every Github issue.

<hr>

As for the actual contents of this issue:
1. The purpose of the smudge tool in the vector layer is to move strokes and control points. If you want it to do something else, say exactly what it is you want it to do. However I will say in advance that the tool already has a very clear purpose and I don't see any additional functionality being added to that. A smearing or blurring effect like what is done on the bitmap layer is not possible with vectors.
2. Duplicate of #1678
3. The focus of Pencil2D is on traditional hand drawn animation. Adding bone support would be a very large amount of work, add a lot of complexity to the project which are both reasons why it will likely never happen. I believe there was some interest in eventually being able to group strokes together on the vector layer but that is likely about as far as Pencil2D will go in that direction. As you mentioned, there are already multiple other programs which do this already, and which are better suited to such workflows.
4. As it has been said, this already exists. If you need help with it, go to our dedicated support channels. There has been some work to make more intuitive controls, which will probably be in the next release.
5. If you mean change shortcuts, this can already be done in the preferences window.
6. The polyline tool will produce straight lines unless you have the bezier option checked, in which case it will produce bezier curves.
7. Again you need to be more specific. What's not effective about it? How would you have it work? There will be significant changes to the bucket tool in the next release which will allow for expansion and filling to different layers among other things.

> these 7 can make v0.6.7 better than animate.cc ,synfig,or blender

Honestly, that's not our goal. We see Pencil2D as simply a tool as part of a larger collection of tools designed to fulfill specific needs within the animation area. We will never do vector animation as well as synfig, or 3d animation like blender, or cloud integration like animate.cc. Trying to be the one and only program for everything is well beyond the abilities of our meagre volunteer development team, and would result in an unwieldy, unusable program.

**Closed by scribblemaniac** 2021-11-19 08:52 UTC

**Comment by Abhinav-ms-903** [comment] 2021-11-19 09:40
i said these as other programs dont allow a easy interface like this
so i just wished these tools
but i think i have only two ways
1 . to be a developer and learn c++ qt and then add the tools
2. to leave this application  and go on to other professional (adobe animate) or free  software with professional  tools like synfig

**Comment by Abhinav-ms-903** [comment] 2021-11-19 09:54
@scribblemaniac  i'm Sorry for it 

as you said these :
Honestly, that's not our goal. We see Pencil2D as simply a tool as part of a larger collection of tools designed to fulfill specific needs within the animation area. We will never do vector animation as well as synfig, or 3d animation like blender, or cloud integration like animate.cc. Trying to be the one and only program for everything is well beyond the abilities of our meagre volunteer development team, and would result in an unwieldy, unusable program.

i didnt knew that its yours goal  and i am new github user i think it would be reason
why signed in github is because yours site is shown private connection and i cant visit i triyed many ways but not possible
then i used these tags and realeses to download it i was unable to visit your forum and i think i need to sign in discord too
or rather than these i think  have only two ways
1 . to be a developer and learn c++ qt and then add the tools
2. to leave this application and go on to other professional (adobe animate) or free software with professional tools like synfig

**Comment by scribblemaniac** [comment] 2021-11-20 02:50
> but i think i have only two ways
> 1 . to be a developer and learn c++ qt and then add the tools
> 2. to leave this application and go on to other professional (adobe animate) or free software with professional tools like synfig

Unfortunately this is often the case for open source projects. When everyone is working on a volunteer basis, the priorities of the project ultimately come down to the priorities of the contributors. What gets done is only what they are willing to work on. We maintain a list of alternative software where you may find another tool that better suits your needs: https://pencil2d-software.tumblr.com/post/184584013311/alternative-desktop-animation-software-pencil2d. Some of these programs are much simpler than Synfig and Blender, although that's not a high standard for simplicity. Possibly look into TupiTube or RoughAnimator.

> why signed in github is because yours site is shown private connection and i cant visit i tried many ways but not possible
then i used these tags and realeses to download it i was unable to visit your forum and i think i need to sign in discord too

Yes you will need a discord account if you wish to join our discord server. You will also need to create a new account if you wish to post to our forum, but it should be publically accessible for viewing. If you think this may be an error beyond just troubles with your computer or internet connection, please [report this issue in the github repository for our website](https://github.com/pencil2d/pencil2d.github.io/issues/new). There's no issue template there, but the same rules generally apply. Be as specific as possible: copy in whatever error messages you are getting, what url(s) you are trying, and specify the browser you are using. Describe any troubleshooting steps you have already taken and their results.

**Comment by Abhinav-ms-903** [comment] 2021-11-20 07:01
yeah so i tried other vpn and browser to get assess  to yours website but that it always shows this :


Your connection is not private
Attackers might be trying to steal your information from www.pencil2d.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
Subject: www.pencil2d.org

Issuer: R3

Expires on: Jan 28, 2022

Current date: Nov 20, 2021

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIFJzCCBA+gAwIBAgISBJzum2Mh5ZIAU7sLHFl/dhCoMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTEwMjkyMDE3MDJaFw0yMjAxMjcyMDE3MDFaMBsxGTAXBgNVBAMT
EHd3dy5wZW5jaWwyZC5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCrxxsM7cYB+Oqps88IF0+iy3w0xGYS5u/zmBd5yWXuZkwfmpJ9M+4H+i4VYve0
8x/VTy6xZ6hJQr/jzJq3MEbCaPUoqWRpb0xLZCTJ3O1Gn6Qfwu9vNtC8aSe44tYY
cEAstPXuj/cNjG4Dkudd1j68u8lbKBCgWvY39eGeFSNybo5pAQmkjKTJ19sFAZBI
S5AgjDh6CmB0eRgmMI5gCxe5JKCA3z8UANMJ5zRHNWN8VNKgneFX0csT0zwwJJeO
6jQAn8xsDGr3VLxeYNxGMcIJ3tnD42MejxzFkJDo2oa+ffHDHxqGaZsL4LIMRwjI
klkrZi/6oTihLxBl9pf9FoczAgMBAAGjggJMMIICSDAOBgNVHQ8BAf8EBAMCBaAw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYD
VR0OBBYEFGNOFYVWWqSUAsIWQqSll5o4AleXMB8GA1UdIwQYMBaAFBQusxe3WFbL
rlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDov
L3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5v
cmcvMBsGA1UdEQQUMBKCEHd3dy5wZW5jaWwyZC5vcmcwTAYDVR0gBEUwQzAIBgZn
gQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5s
ZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwBvU3asMfAx
GdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAXzN6cZJAAAEAwBIMEYCIQDB8jX4
LD1DqHFn02dkH7Baz+OIWE1D24+aq9BNM0rmEAIhAMsHpdze42gnImVhHzDIXbTZ
1Ryxbcq6gK1P6sIDGUzdAHYARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+
bUcAAAF8zenGswAABAMARzBFAiEA+GrseG1InDYkNHZB0avL+4QyKPHOLj4c5R5W
jbCQ2v4CICXrc17TG8lf/w4BHD7kuc4XQGgP8YqE0SMrS5FV2FbjMA0GCSqGSIb3
DQEBCwUAA4IBAQA18NIfxqOytcodZ9qKGA3LKFxQOWprmt7HJB9MFfA9SuV0Ddb0
Cu9f5iL2czaiJlU20qXok1xucydLwCnG5AisNFcg5fU0rGB11MxdH2PYCgaZHCJJ
+wYc+qQQhbbXVzpMspQ32jzxyXtu/i4DkgNtvF+lPXhwfcZ9Vcb0XdiNBJsQlmkg
0+XnQqJvrkXntoXsUkAi6H/FZnRF4rBiE2W/5vrgEx/HGkOHlrVzI3fAkCRZc8hh
TfrZxzxysJo+79xBijpYBNvQ9Z707MnonSbdVDjG+fvdd3xs49NHLnruJaDp+TkE
Mea8M6TL+lDABOiRu86NwKd8zF+BoTiOx5ie
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEZTCCA02gAwIBAgIQQAF1BIMUpMghjISpDBbN3zANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIwMTAwNzE5MjE0MFoXDTIxMDkyOTE5MjE0MFow
MjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxCzAJBgNVBAMT
AlIzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwIVKMz2oJTTDxLs
jVWSw/iC8ZmmekKIp10mqrUrucVMsa+Oa/l1yKPXD0eUFFU1V4yeqKI5GfWCPEKp
Tm71O8Mu243AsFzzWTjn7c9p8FoLG77AlCQlh/o3cbMT5xys4Zvv2+Q7RVJFlqnB
U840yFLuta7tj95gcOKlVKu2bQ6XpUA0ayvTvGbrZjR8+muLj1cpmfgwF126cm/7
gcWt0oZYPRfH5wm78Sv3htzB2nFd1EbjzK0lwYi8YGd1ZrPxGPeiXOZT/zqItkel
/xMY6pgJdz+dU/nPAeX1pnAXFK9jpP+Zs5Od3FOnBv5IhR2haa4ldbsTzFID9e1R
oYvbFQIDAQABo4IBaDCCAWQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8E
BAMCAYYwSwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5p
ZGVudHJ1c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTE
p7Gkeyxx+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEE
AYLfEwEBATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2Vu
Y3J5cHQub3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0
LmNvbS9EU1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYf
r52LFMLGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0B
AQsFAAOCAQEA2UzgyfWEiDcx27sT4rP8i2tiEmxYt0l+PAK3qB8oYevO4C5z70kH
ejWEHx2taPDY/laBL21/WKZuNTYQHHPD5b1tXgHXbnL7KqC401dk5VvCadTQsvd8
S8MXjohyc9z9/G2948kLjmE6Flh9dDYrVYA9x2O+hEPGOaEOa1eePynBgPayvUfL
qjBstzLhWVQLGAkXXmNs+5ZnPBxzDJOLxhF2JIbeQAcH5H0tZrUlo5ZYyOqA7s9p
O5b85o3AM/OJ+CktFBQtfvBhcJVd9wvlwPsk+uyOy2HI7mNxKKgsBTt375teA2Tw
UdHkhVNcsAKX1H7GNNLOEADksd86wuoXvg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----

Certificate Transparency:

SCT Sectigo 'Mammoth' CT log (Embedded in certificate, Verified)

SCT Google 'Xenon2022' log (Embedded in certificate, Verified)

www.pencil2d.org normally uses encryption to protect your information. When Chrome tried to connect to www.pencil2d.org this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be www.pencil2d.org, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit www.pencil2d.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by Abhinav-ms-903** [comment] 2021-11-20 07:04
so i am learning blender grease pencil  
now i am using both grease pencil & pencil 2D for getting a smooth animation 
any way ... Pencil2D is A great software it is a doorstep to animation for me and others 
now its time to try other softwares

**Comment by scribblemaniac** [comment] 2021-11-20 08:35
At a glance that appears to be the correct certificate, and as you can tell from the expiry date is not expired. Something is wrong on your end, possibly your system clock is off? There's a full troubleshooting guide for the issue here: https://www.clickssl.net/blog/neterr-cert-date-invalid, I would go through that testing after each section until the issue is fixed. You will likely have the same problem on many other websites that use HSTS if you don't fix the underlying issue.
