### ISSUE TITLE
[ISSUE] Vector Layer will be kept active even when using a Bitmap layer

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#755] opened 2017-09-12 02:30 UTC
### --Issue Summary--
After using a vector layer and starting drawing/painting on a Bitmap layer, changes applied on the active layer (bitmap) will also affect some colors on the vector layer

### --Actual Results
When changing colours on the bitmap layer, it will affect the last colour applied on the vector layer

### --Expected Results--
Vector and bitmap layers are independent.

### --Steps to reproduce--
. Open Pencil2D
. Select VECTOR layer
. Select Pencil tool and check the "FILL CONTOUR" (for better visualization) and uncheck "show outlines only" feature  on the DISPLAY panel (for visualization of the shapes being filled.
. Draw 3 circles using different colours
. Select now the BITMAP layer and change the colour of the ColorWheel panel: as a result the last filled circle on the VECTOR layer will changed accordingly. It happens when using any other drawing tool

### --System Information--
+ Pencil2D Version:
Pencil2D last build 12 SET2017

+ Operating System:
Win8.1 x 64bits

+ RAM Size:
64GB

+ Graphics Tablet:
HUION GT185 HD

**Comment by Jose-Moreno** [comment] 2017-10-30 21:11
@Kaikogf @chchwy Hi. I'm sorry to repeat myself, but this is not a bug. If you use Toonboom Harmony 15 or even older versions, this will happen as well. It's intended behaviour when you work with global color palettes for even a small production. Vector color has to be fully editable. bitmap not so much as it's used for sketching or artistic painting.

I understand it's hard to get away from the way image editors like GIMP or Photoshop normally work. But the color palette in Pencil2d or Toonboom is NOT a swatch palette where colors are static. These colors are expected to be editable anytime, they are sort of "live" colors (similar to Illustrator) due to the volatile nature of an animation production where art direction decisions must be made last-minute.

Basically one have to use it like this:
1) For Bitmap, create a single swatch that will serve as your "all-in-one" color switcher.
2) For Vector create ONE color for every part that has a color attached as seen on your color model. 

For example if you have a black t-shirt, black pants and black shoes on your character, you HAVE to create 3 black colors, one corresponding to each part of the character.

The solution for this confusion is for the user to create and name specific color palettes to use for either bitmap and vector layers. 
Pencil2D team could think in the future of creating separate palette windows for both layers, or using visibility tags for color swatches that activate when either layer is active, but this is not a bug. I'm afraid it is actually a standard in animation production.

**Comment by chchwy** [comment] 2017-10-31 00:36
Thanks for your detailed explanation @Jose-Moreno. 

I understand it is a very useful feature. Since the colour palette is dedicated to vector layers, the question here is the feature which allows us to change a colour later isn't work on Bitmap layer. 

So what I'm going to do is "detaching" the connection between a bitmap pen tool and the colour palette. The colour changes won't affect other vector layers when a user is working on a bitmap layer.

In a long run, 2 different colour palettes for bitmap and vector layers might be the way to go. The current colour palette is so misleading because it contains a list of colour name, not a list like black t-shirt, black pants, and black shoes.

**Comment by Kaikogf** [comment] 2017-10-31 01:17
I think I understand what you are talking about @Jose-Moreno. Still I find it confusing that is why I called it an Issue. Anyway thank you for your explanation 👍 


@chchwy 
"So what I'm going to do is "detaching" the connection between a bitmap pen tool and the colour palette. The colour changes won't affect other vector layers when a user is working on a bitmap layer". 👍  
I start to remember reading about implementing a kind of switch for On/Off this feature (affecting/no-affecting vector Layers when working with Bitmap Layers). So, that is what I wanted to explain here

**Comment by chchwy** [comment] 2017-11-01 02:13
Fixed in 1 Nov version

**Comment by chchwy** [comment] 2017-11-02 05:44
@Kaikogf please try this out and tell me what you think if you have time. :D

**Comment by Kaikogf** [comment] 2017-11-04 02:21
I will test it on the following days @chchwy. Thank you

By the way there is a bug that keeps opening a windows (like the one when importing images/sound). It is not consistent though but I will try to get it right.

**Comment by Kaikogf** [comment] 2017-11-07 04:43
@chchwy 
I have tested it with the last version **Nov 7 2017** and it is working very well Thank you for the changes! 👍 
If working on a Vector Layer and then changing to a Bitmap layer, it will no longer affect any colour used on the Vector layer.

When strictly using vector layers, it will behave as @Jose-Moreno explained above, so it is working OK

**Comment by Jose-Moreno** [comment] 2017-11-08 22:19
@Kaikogf @chchwy I know this was solved, but I still think we might need to work a better solution for the palette to work with the bitmap layer as well. Maybe create a virtual copy of the current palette for both layers, Or at least to have a separate "bitmap swatch panel" for the bitmap layer.

As a USER this is what happened to me just today. When I was working earlier, I wanted to organize the colors of my file, and then I tried to change the color of a swatch for about 5 minutes until I got infuriated, but then I "remembered" that the code had changed. So i had to click the vector layer, change the color of the swatch and then come back to the bitmap layer... This means that every time I want to change my swatch colors I have to change to vector mode. 

I find this quite impractical, I know some people prefer bitmap over vector drawing, but the end game of Pencil2D is to make vector as smooth and useful as bitmap layers. In toonboom and even clipstudio paint, vector lines are used for clean-up, while bitmap is used for sketching. This was the same paradigm used for the old Pencil.

At least before both layers had the same "permissions" to the color palette, and I solved it with the work around I mentioned (creating a custom color exclusive for bitmap work), now it feels as if the bitmap layer has restricted permissions and can't do anything without asking vector layer for help. I cannot even think what will happen when people use it now. We'll get loaded with threads saying "my color swatches don't change color".

Again I understand the need to quickly change the colors as if it was photoshop, but I feel this is not the best way to solve this, since it's not a programming problem, it's a design issue we need to discuss :confused:

**Comment by chchwy** [comment] 2017-11-16 02:47
I'm reopening this issue because I think what @Jose-Moreno said is right.
The solution can only be a temporary solution we still need to sort this issue out by a more proper way.

I'll leave it for a while and be thinking about what to do.

**Comment by Kaikogf** [comment] 2018-01-01 02:13
@Jose-Moreno @chchwy 

Well, I think I am missing something about this "issue". But as I have said in other comments I am taking care of the Bitmap workflow, so when things go around Vector tools I confess that I have zero knowledge about the way it should work. 

Still I am very pleased that you all are listening users about our "concern and ideas"

Please continue. Pencil2D is far more attractive now! 👍

**Comment by CandyFace** [comment] 2018-05-10 20:48
Ability to edit swatch color has been added to both bitmap and vector in #961 

I am working on a proper solution but because vector is so attached to the palette, this will require more thorough work to work properly.

**Comment by Jose-Moreno** [comment] 2019-09-29 02:23
I'm closing this as the original issue is no longer applicable. The vector and bitmap code for the swatches has been separated, which brought forth a new set of issues, but so far you can no longer "update" bitmap layer colors by changing the swatches when having a vector layer active.

You're welcome to test this again in 0.6.4 and above in case there is any leftover issue stemming from this.

**Closed by Jose-Moreno** 2019-09-29 02:23 UTC
Labels: bug, color palette
