### ISSUE TITLE
All I see is red

### ISSUE THREAD

**Issue by AngieIsWeird** [pencil2d/pencil#525] opened 2016-07-31 08:20 UTC
so i tried to use color but it was not working, all it did was turn what ever i colored red and freezes my animation sometimes

**Comment by Jose-Moreno** [comment] 2016-07-31 13:51
@AngieIsWeird Hi, first of all, if you're going to report a problem please try to search if others have asked  the same before. Also when communicating what the problem is please try to describe how the problem happened. i.e "I was drawing with the pen tool on a vector layer, but when I tried to color my drawing it all went red..." 

This particular problem has been addressed already, So I can provide you with 2 choices:
1) Workaround: The red coloring only happens when you draw on a VECTOR layer (unless you tell us otherwise). It is indeed a simple bug, but it's easy to counter. You have to fill the shape then select the fill with the black arrow (move tool) and with the fill selected just use the color palette to give it a new color.

2) Use a newer, but unstable, version of pencil: You can use a Nightly Build and see firsthand if your current problem has been addressed or not, as these are pencil versions that are incrementally fixed by the developers, however they lack common stability, but are usually superior to the current 0.5.4b version.
Download them here: https://pencil2d.github.io/download/

IfF your issue is resolved, please consider closing this post using the CLOSE button. If you still continue to have the issue, even after testing a new version, then please describe how exactly the problem is happening, write the version you're using, and let us know your operative system.

Good luck.

**Comment by chchwy** [comment] 2017-11-06 06:18
Hi @AngieIsWeird, 
If you are still interested in Pencil2D, please try our recent nightly build: <http://pencil2d.github.io/download/>. It has been improved and got a bunch of bug fixes.

Feel free to open another issue if something still goes wrong. I'm gonna to close this :)

**Closed by chchwy** 2017-11-06 06:18 UTC
