### ISSUE TITLE
inconsistent sound sync

### ISSUE THREAD

**Issue by DogBoyMark** [pencil2d/pencil#1298] opened 2019-11-16 16:47 UTC
when I pay the movie, the audio is never in the same sync. If it was consistent then fine, I can sync the video when finished, but I cannot complete movie because sometimes the audio moves a few seconds before or after the video

Version: 0.6.4
Operating System: Windows 10 (10.0)
CPU Architecture: x86_64

length 00:03:40 (hh:mm:ss)
it was an Mp3
converted to .wav and seems to be better

**Comment by Jose-Moreno** [comment] 2019-11-16 17:09
@DogBoyMark Hi. This is actually a known issue although it didn't specifically had a ticket open. 

Unfortunately we might need a sound specialist programmer to fix this because right now even though there have been improvements done over the past versions to fix sync, there's still a gap between playback and exported sound, sometimes it ranges from 1-3 frames up to 20 frames depending on the user hardware.

Also the sound playback tends to have difficulties depending on these hardware restrictions so we understand that getting an accurate sound replay at any given time frame is sometimes not possible.

For now please update / edit your initial comment to properly write out part of the original template...we need that info to help developers at least know where they have to test things out, as well as:

- Pencil2D version
- Operating System
- Type of sound used (mp3 vs wav)
- Length of the sound (seconds, minutes, etc)
- If possible share the sound or the Pencil2D project and the movie export as a zip file (_you can use a cloud file storage account you already own or use www.wetransfer.com and look for the **anonymous link option**_)

**Comment by rebe83** [comment] 2020-02-06 05:50
Not the above person, but I am also having this issue. 
Version: 0.6.4
Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Sound used: mp3
audio length: 14:29

What seems to be happening is, for every frame, the moment you pause on isn't the same as what that frame is loaded to start on, and so the audio that is played is from seconds beforehand.
So for example, if I'm starting the animation at frame 1, everything will be in sync the whole way through, but if I ever pause, the sound will end up off by a some amount. (Unsure if it increases in offset the farther into the sound the pause happens)
You can see what I mean by starting the animation, and pausing when it gets to the second keyframe(frame 32). When you press play, it will play the audio that originally played at frame 22. So by that point, the "resume" audio is already 10/9ths of a second behind.

I was keyframing the project when I noticed this problem, so the screens I have weren't changing at the right time with respect to the audio. Therefore some frames and words written on them are accurate to "resume" times where i was going keyframe to keyframe and not start-to-keyframe.
Also, You are able to "coast" on the same sound and have it appear on a range of frames by quickly pausing an unpausing, so I'm not sure that that is really what's going on with that, but it might help figure out the cause. 

I included the project file as well as the movie export (unzipped sorry, but it's just 20MB)
The website says the link expires in a week, so 2/13/20

https://we.tl/t-izuyojH1AU

**Comment by Jose-Moreno** [comment] 2020-02-06 18:14
@rebe83 Hi. Thank you for confirming this issue. In fact recently another contributor reported a similar problem. In his case using a WAV filtype diminished the issue. If you can please try out converting the sound to .wav and let us know if there's any noticeable improvement. I'll pass your file and comment to the devs. Thanks again!

**Comment by rebe83** [comment] 2020-02-07 02:00
After converting it, it seems to work perfectly. When pausing and resuming quickly, no sound is repeated, and pausing and moving around seems to pick up at the correct part of the audio. 
I noticed that when resuming audio, there is some audio that is skipped over due to the pause. This might mean that the way WAV files are directed to read/store the position of audio is handled differently than the case of .mp3, where perhaps mp3 is treated as a -1 while WAVs are treated as a +1. Just a guess from knowing bugs I have when I'm programming, I don't know anything about sound encoding/decoding or how the system is set up in pencil2d.

**Comment by Jose-Moreno** [comment] 2020-02-08 04:01
@rebe83 We don't really have a sound expert either. But I think your comments and testing will surely help the developers find a way to deal with this. For now, I'll try to spread this common knowledge as it's something we didn't realize before and I'm sure it's been affecting many users without us knowing 😕

**Comment by nylonstring** [comment] 2020-07-18 15:44
I have the same problem too

Version: 0.6.4
Operating System: Windows 10 (10.0)
Sound used: mp3 and wav
audio length: 3:12

I've tried using both formats and they both act the same for me. It seems to play normally if I start from a very early frame (around 1-12), but if I jump to any other point in the timeline, it goes off sync.

**Comment by Jose-Moreno** [comment] 2020-07-19 03:34
@nylonstring Hi! Can you test the latest nightly build of Pencil2D for your current OS? I believe the developers have addressed this issue with MP3's and the patches will come for the upcoming release, however it would be great to have your feedback as you've experienced this issue first hand.

**Win 64bits** https://drive.google.com/file/d/196YT2n9kh2pDTFuIGida_1ugzdwt9a1m/view?usp=sharing
**Win 32bits** https://drive.google.com/file/d/1iygldiQrLFcNnRyRh9MNRXV0JXw2HKnv/view?usp=sharing

**Comment by Jose-Moreno** [comment] 2020-07-30 07:04
A new release will be shipping soon with what the developers consider fixes this problem. I'm closing this issue and we ask everyone involved in this thread that you to test the new release next week. If you'd like you can also test a development build closer to the release here:

Windows 64 bits https://drive.google.com/file/d/1JQ6-Hp_nt9XWPwJh4vOyusDEb-VhRSJC/view?usp=sharing

If you still continue to have this problem let us know in this same thread and we will re open this once we've tested your new report. Thank you for your patience.

**Closed by Jose-Moreno** 2020-07-30 07:04 UTC
Labels: bug, investigate, sound
