### ISSUE TITLE
MP4 Export Crash

### ISSUE THREAD

**Issue by jimmerjorns** [pencil2d/pencil#1493] opened 2020-10-30 18:16 UTC
### Issue Summary
Export doesn't work
 

### Actual Results
Exit status: CrashExit
Exit code: 1
Thats what it says in the text box thing
 

### Expected Results
It would export normally as a mp4 file
 

### Steps to reproduce
I have no idea, i used redo before this so maybe thats the problem
 

### System Information
+ Pencil2D Version: 0.6.5 (stable)

 

+ Operating System:
Windows 10
 

+ RAM Size:
16GB
 

+ Graphics Tablet:
Old version of Wacom Intuos Pro S

**Comment by Jose-Moreno** [comment] 2020-10-30 20:26
@jimmerjorns Is it possible for you to share the file that is causing the crash? That way the developers will be able to hopefully reproduce the specific issue that's affecting you and look for potential solutions quicker.

You can try using **wetransfer** anonymous link. It will be delete automatically in 1 week as well. https://wetransfer.zendesk.com/hc/en-us/articles/115004254743-How-do-I-send-a-link-transfer-

**Comment by jimmerjorns** [comment] 2020-10-30 20:41
https://we.tl/t-OTbI3BioeW

**Comment by Jose-Moreno** [comment] 2020-10-31 00:17
@jimmerjorns Hi. Thank you for taking the time to send the file.

I'm using the stable version and unfortunately managed to export the file you sent without problem using the default settings 😔 I also have Windows 10, 16GB of RAM and a Wacom Intuos 5 S, so at first glance it isn't a hardware issue.

I'm attaching the resulting video in case you need it too for now.
[science_project.zip](https://github.com/pencil2d/pencil/files/5468195/science_project.zip)

While I exported with MP4 to test, can you try exporting with other formats like AVI or WEBM format? You can find it after pressing the "browse" button.
![image](https://user-images.githubusercontent.com/4912907/97766137-25dbeb00-1ae3-11eb-8dc1-5a9641f936d6.png)

And clicking on the dropdown menu below the name of the file.

![image](https://user-images.githubusercontent.com/4912907/97766129-1bb9ec80-1ae3-11eb-941e-6ffc9f34a600.png)

Does it work or does it also crash upon export with those formats?

Next time it crashes can you consider taking a screenshot of the error and also go into your event viewer?

To get there you can:
1. Go to the start menu
2. Start type-searching the words "event viewer"
3. You'll get to this 
![image](https://user-images.githubusercontent.com/4912907/97766306-c3371f00-1ae3-11eb-84c8-e3d9ff469249.png)
4. Then open the "app" and you'll see a windows with various elements. On the left open the Windows logs folder > Then click on the Application folder.

![image](https://user-images.githubusercontent.com/4912907/97766347-e9f55580-1ae3-11eb-93cf-6167257a72c8.png)

5. Once the list loads, look for an "Error" that is of Source type "application error" and in the **Faulting application name** it matches **Pencil2D.exe**
![image](https://user-images.githubusercontent.com/4912907/97766381-17420380-1ae4-11eb-9c46-8a396069247f.png)

For now this information will help us narrow down any possible problem. However If this keeps happening to you, meanwhile we find out what's happening, I'll recommend you an alternative animation application from a curated list we have just so you can continue your work without further delays and will gladly help you out to transfer the images to the new app you choose in case you need to 😄

**Comment by rpg1129** [comment] 2020-11-03 01:33
I am having the same exact problem.  I am running the program on Mac OSX 10.10 (Yosemite).  The animation will not render in any format, regardless of the extension.

**Comment by Jose-Moreno** [comment] 2020-11-03 01:51
@rpg1129 Hi. Can you please take a screenshot of the error or crash report? If there's not crash then it's unfortunately not the same error, and we should move this to a different ticket.

**Comment by rpg1129** [comment] 2020-11-03 01:58
There isn't a crash—what happens is that the export never actually happens.  The progress window shows it happening, but the files are not saved anywhere on the computer.

**Comment by rpg1129** [comment] 2020-11-03 01:59
Dozens of people are reporting this same issue, judging from other forums.

**Comment by Jose-Moreno** [comment] 2020-11-03 03:00
@rpg1129 Unfortunately, this is actually a rare sight. There are a few reports but as far as I'm aware this is a compatibility problem between certain legacy macOSX versions and the FFMPEG plugin which is used to export movies.

One of the Pencil2D devs was working on a potential test build for Pencil2D 0.6.5 to fix this problem, but i'm not a macOSX user so i don't have a copy handy right now. I've already asked them to provide us with another link to try that version and see if it works for you, however this will take time to setup as they are currently very busy with their day job and can't spare enough time to volunteer in the project, so meanwhile please consider the following:

In the forum a user with a similar issue provided a guide to compile FFMPEG from source to help legacy macOSX users with this problem: https://discuss.pencil2d.org/t/export-not-working-in-legacy-os-x-version/4587/14 apparently their FFMPEG file worked as expected.

Consider compiling the ffmpeg version required for your OS and then replace it in your .APP folder for Pencil2D. The FFMPEG file is found in the folder structure:

```
Pencil2D.app
-- contents
--- MacOS
---- plugins
----- ffmpeg
```

You could also try to use the user's **pre-compiled ffmpeg build** https://www.dropbox.com/s/jncl1a9dd8tt7rp/ffmpeg?dl=0, however I can't assure that it will work for your particular macOSX version. Be wary that it is a third party created file, not something made by the Pencil2D maintainers.

I'll update you once I have more info on the test build.

**Comment by rpg1129** [comment] 2020-11-03 03:10
Thanks, I appreciate it.  I'll look into that info.

**Comment by Jose-Moreno** [comment] 2020-11-21 23:28
Since this isn't a bug caused by Pencil2D by by FFMPEG, I suggest we turn this into an enhancement request so Pencil2D will enforce a check that H.264 / MP4 videos always need to have dimensions divisible by 2. 

We'd need a warning pop-up too if the movie dimensions (width / height) are found to be indivisible by 2 once the user presses "export". It should also recommend to change the dimension in the actual camera layer and not on the output size (considering this scales the resulting image)

**Comment by rpg1129** [comment] 2020-11-25 16:17
Maybe I should try exporting at the default Canvas size instead of changing it to HD dimensions?

**Comment by Jose-Moreno** [comment] 2020-11-26 02:14
@rpg1129 As per the description of your problem it is unfortunate to say that lowering the resolution will not solve your issue. At least If we consider the legacy macOSX version into the mix.

Let's move the discussion to the new issue #1543 which is dedicated to track the compatibility problem that prevents video export for macOSX users with legacy versions below 10.12. 

If your export is crashing however, please post a screenshot of the error itself to troubleshoot further based on the report, otherwise it is hard for us to guess how much is a problem coming out of FFMPEG and how much it's a problem of the Pencil2D software itself.

**Comment by scribblemaniac** [comment] 2021-06-21 06:14
There really isn't enough information to go off of here, so I am closing this. There are numerous reasons why an export can fail which have been covered by other bug reports. Silent failures, if they exist, should at least be caught by https://github.com/pencil2d/pencil/commit/987929ed6abd9f737ced44d90414ec436723f25a now.

**Closed by scribblemaniac** 2021-06-21 06:14 UTC
Labels: Bug Triage, Crash, File Export
