### ISSUE TITLE
project becomes pixelated when i zoom in 

### ISSUE THREAD

**Issue by mmhwaffle** [pencil2d/pencil#1802] opened 2023-12-10 18:41 UTC
### Issue Summary

 so whenever i zoom in the project gets pixelated all the time and it happens in every version  

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by scribblemaniac** [comment] 2023-12-10 22:44
I'm afraid you have not provided nearly enough information to determine what the cause of your issue is. How are you trying to zoom in? What type of layer are you trying to zoom into? What does "every version" mean?

Without further details, I would say it's highly likely that you are encountering expected behavior and are simply confused about how some features of Pencil2D work. Bitmap layers store their data in a raster graphics representation and cannot be scaled up without a reduction in visual quality which you may describe as becoming pixelated. Vector layers store data using paths and thus can be redrawn at different resolutions, but as we have previously explained to you are not recommended for use due to their buginess and general difficulty for users to learn. To avoid degrading bitmap image quality, it is recommended that you set your resolution before you start your project, and only draw at that resolution so you do not need to zoom in. If you want an animated zoom effect, draw at your largest resolution, and zoom out for the part of your animation that you do not want zoomed in.

This GitHub repository's issues are intended primarily for developers to track bugs and feature requests. If you need support using Pencil2D, [our forums](https://discuss.pencil2d.org/) are better suited to problems such as this (though even there you will still need to provide more details than this). If you insist on raising future issues here on GitHub, please be sure to fill out all sections of the template, which provide essential information to help developers understand what your issue is and how to reproduce it.

I am closing this issue. It can be reopened if more information is provided.

**Closed by scribblemaniac** 2023-12-10 22:44 UTC
