### ISSUE TITLE
Lag using Huion tablet

### ISSUE THREAD

**Issue by brockm707** [pencil2d/pencil#877] opened 2018-01-30 02:17 UTC
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

I just got my huion tablet, got it all set up and when I went to draw with pencil 2d it kinda lagged out like I would draw a circle and it would draw a strait line and catch up with my pen to kinda make a squished circle pleas fix or send tips

**Comment by chchwy** [comment] 2018-01-30 03:35
Hi @brockm707 We need more information to help you. 

At least tell us what OS you are using? Is it Windows, Mac and Linux? What version are you using? Is it 0.6.0?

**Comment by Jose-Moreno** [comment] 2018-06-16 16:52
@brockm707 Does this still happen for you? Have you updated to the latest drivers for your HUION tablet? if not please do and try out a development build by getting it here http://pencil2d.org/download#nightlybuild

**Comment by starndust31** [comment] 2018-07-06 18:42
I think I have a similar problem. I have a huion h610 pro with the Digimend 7. r80. gcda5bdf-1 driver on Manjaro 4.14.53-1 and I'm running pencil2D 0.6.1.1-1. In pencil2d, hovering my pen over my tablet doesn't work. It works in Krita though, which is why I thought there might be a problem with pencil2D.

**Comment by Jose-Moreno** [comment] 2018-07-06 19:48
@starndust31 I know Digimend is a Linux effort for bringing more support to non-standard graphics tablets, but I don't really know if Krita has done anything else to include the digimend project code. 

It seems they have several HOW To guides for every other software than Pencil2D which makes me think the driver support is indeed provided per program, https://digimend.github.io/support/

With that said Pencil2D would have to investigate how to provide further support with the digimend project for Linux as apparently the QT sanctioned drivers are not enough to support non-standard graphics tablets like HUION, however I'm not sure how or when that would happen. So if you know someone who'd like to contribute, please guide them to our developer wiki: https://github.com/pencil2d/pencil/wiki

@chchwy @scribblemaniac @CandyFace @J5lx what do you think about this?

**Comment by jin-eld** [comment] 2018-07-13 17:05
Just wanted to throw in: I have a Huion H610 tablet and I did not expect any lag or other tablet related issues with todays master head build of Pencil, I'm on Fedora 27.

One issue that I have though is, that the icons of the tools (pen, eraser etc) are often wrong and show either arrows or other things, which makes it difficult to aim at the pixel you want to draw, but  I do not think that it is tablet related.

**Comment by Jose-Moreno** [comment] 2018-07-13 17:46
@jin-eld  Thank you for your input regarding this issue. 

With respect to the other issue you mention, If  understand correctly you're saying that on Fedora 27 (Linux) using the latest master, your tool icons are missing right? I think it would be wise to file a report for that, but I think this was an issue that has supposedly been fixed already.

If I may bother you can you please comment and describe your experience on the following issue #957 and when you do so please tag the developer(s) that commented in that thread (chchwy and scribblemaniac) so they are aware of the problem. Even if it's closed it can be re-opened.

**Comment by jin-eld** [comment] 2018-07-13 18:48
Actually, now that you mentioned #957, I did some tests without the tablet and the icons are fine, so it seems to be a tablet related issue after all. Shall I still add it to #957 or rather open a new one, specific to tablet usage?

**Comment by Jose-Moreno** [comment] 2018-07-13 19:01
@jin-eld Hey. Hmm since it seems to be tablet /driver related and sounds different from this issue then it's better to open a new issue to keep track of that, thanks!

**Comment by jin-eld** [comment] 2018-07-14 16:39
Added https://github.com/pencil2d/pencil/issues/1017

**Comment by Jose-Moreno** [comment] 2020-09-05 05:57
After careful consideration and research on what seem to be similar issues, I believe this issue could be partially fixed by #1443 specifically https://github.com/pencil2d/pencil/pull/1443/commits/5c8f2da429f795992643160143905e931d79f05e the other half of the work will depend on a robustly crafted configuration guide for Windows users on how to customize their Windows-Ink settings which affect **all tablet brands** according to both Microsoft and Wacom official support articles.

This issue has also been reported in the forum where people would describe start drawing a circle and a straight line would be immediately drawn for a bit and only afterwards they would regain control of the stroke. This shares commonality with the "serrated" line issue reported in #1418 which is under the [wacom-stroke-glitch tag](https://discuss.pencil2d.org/tag/wacom-stroke-glitch) on our forum. This issue has been minimally reproduced under Windows 10 with a Wacom tablet on the latest versions, however once the mentioned commit was implemented in a debug build, while using Windows Ink, this problem seemingly disappeared.

I'll leave this issue open to keep track of the mentioned "straight line lag" problem which i've tagged on the forum as [windows-ink](https://discuss.pencil2d.org/tag/windows-ink)

**Comment by scribblemaniac** [comment] 2020-09-06 20:14
I'm going to disagree with @Jose-Moreno here. The type of lag behavior seen with Huion tablets seems to be exclusive to them. See [this](https://drive.google.com/file/d/12aePv30ygNChFSJKpKHvWabTSGR7GFv6/view?usp=sharing) and [this](https://www.youtube.com/watch?v=em0l2zjjPnE) for example videos from our users. Note that some of the users who reported this were on macOS so this can't been a Windows Ink issue. As I discussed in #1133, the lag was probably the result of the high tablet event reporting rate from the Huion drivers.

The straight line issue is something that has happened with Huion tablets too, but it was not mentioned in this particular issue. It is probably not the same as the serrated stroke issue because it was drawing two separate lines simultaneously, while the serrated stroke is one continuous line.

I'm going to recommend that this be closed in favour of the much more technically comprehensive post at #1133 which describes lagging like this issue, and a few other related issues. Given the lack of information initially provided, we can only really speculate here as to what the actual issue was.

**Comment by Jose-Moreno** [comment] 2020-09-06 21:20
> It is probably not the same as the serrated stroke issue because it was drawing two separate lines simultaneously

Indeed it's not. The "straight line issue" on the forum is separate from the "serrated" one via tags (wacom-stroke-glitch vs windows-ink). 

> Note that some of the users who reported this were on macOS so this can't been a Windows Ink issue.

The particular problem I'm referring to has been reported on Windows primarily, I have not seen a macOS case for that, but if it's possible, can you post the specific macOS cases with a similar description so we can also document this?

---

To be honest after the last paragraph I had written a small treatise on why I think straight line and linear optimizer were not the same issue but y'know what? let's just close this lmao. 

I was actually going to close it last time I reviewed since there was simply not enough feedback to go on, but since the description was similar to the ones on the forum I decided to keep it open under that premise 🤷‍♂️ 

If the "straight line" issue being unique to huions is also caused by the linear optimizer issue, then I hope it's fixed with just that. I may not be 100% convinced that it is the same issue but I guess we can reopen once there's a new report or something. Closing.

p.s. Y'know _I'm not saying it's Windows, but it's Windows_ 😂

**Closed by Jose-Moreno** 2020-09-06 21:20 UTC
Labels: Bug, More Info, Tablet Support

**Comment by scribblemaniac** [comment] 2020-09-07 03:12
> The particular problem I'm referring to has been reported on Windows primarily, I have not seen a macOS case for that, but if it's possible, can you post the specific macOS cases with a similar description so we can also document this?

I'm talking specifically about stroke lag with the Huion tablet. I experienced it on a mac, and at least two users here experienced the same thing on mac: https://discuss.pencil2d.org/t/difficulty-with-huion-tablet/1369/3. In fact I do know if there has been a case of this on Windows at all. There was the report about it occurring on Manjaro here though.
