### ISSUE TITLE
[ISSUE] When using the Dynamic Sizing on VECTOR layers the preview circle is far off to its left

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#740] opened 2017-08-26 15:51 UTC
### --Issue Summary--
When Dynamically Resizing the size of a tool on a VECTOR layer, its preview circle will appear far off to its left-upper corner on the canvas

### --Actual Results
The preview circle is shown on the left-upper corner of the canvas (vector layer)

### --Expected Results--
To be shown underneath the cursor of the pen

### --Steps to reproduce--
- Open Pencil2D
- Select Vector layer
- Select a drawing tool
- Activate "Use Quick Sizing" on >Edit > Preferences > Tools
- Use the tool

### --System Information--
+ Pencil2D Version:
Last build 23August2017

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

---

**Comment by CandyFace** [comment] 2017-08-26 15:55
This has been fixed in upcoming PR #738

**Comment by Kaikogf** [comment] 2017-08-26 16:16
@CandyFace 
So it is a duplicated issue? I don't quite follow it :(

**Comment by CandyFace** [comment] 2017-08-26 16:23
Not entirely since the issue isn't about the exact same thing. It's related to #737, but I guess we can count it as a duplicate.

**Closed by CandyFace** 2017-08-26 16:23 UTC
