### ISSUE TITLE
windows & camera in v0.6.6 

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#1676] opened 2021-11-18 06:20 UTC
version 0.6.6 have a little problem to find the windows for changing size. as when my layers in timeline increases the window 's size should be  increased 
and the camera dont  have the old feature in which it can automatically move or zoom

**Comment by scribblemaniac** [comment] 2021-11-18 06:58
> version 0.6.6 have a little problem to find the windows for changing size. as when my layers in timeline increases the window 's size should be increased

Pencil2D should not change the window size based on the content. It merely specifies minimum sizes and is is up to the user to adjust the size of the window and and panels to their liking. If you have more layers than the timeline can display in the current panel size, it should create a scrollbar and allow you to scroll between all the layers. If this is not what you are talking about, can you describe the issue more and provide screenshots of the issue? Also please specify which operating system you are using.

> and the camera dont have the old feature in which it can automatically move or zoom

This sounds like a duplicate of #1488 which has already been fixed in the nightly builds.

In the future, please make separate issues for each issue you are having. You can post it to [our forum](https://discuss.pencil2d.org/) first if you are uncertain if you have actually found a new bug in the program or not.

**Comment by Jose-Moreno** [comment] 2022-05-22 22:56
I'm closing this since there has not been any reply from the OP since last year.

Currently it's a bit difficult to understand the description but I believe the first issue OP could be hinting is that where the timeline panel was not updated properly when the amount of layers increased, which was fixed here https://github.com/pencil2d/pencil/pull/1345 

The first point could also have to do with the old issue where resizing the window while using non-standard screen resolutions used to cause problems with the widgets as per https://github.com/pencil2d/pencil/issues/1417 which has been patched and should be working for most cases but is still lacking a definitive solution AFAIK

As Scribblemaniac mentioned the second issue related to camera interpolation has also been fixed in the development builds.

Without more information we can't continue troubleshooting this problem, so please test this by grabbing the most recent test build here https://pencil2d.org/download/nightly and let us know if your problems are solved. If not please reopen this issue and describe how your experience changed or not.

**Closed by Jose-Moreno** 2022-05-22 22:56 UTC
Labels: Bug, More Info, UI, No reply
