### ISSUE TITLE
Crash when selecting with _DEBUG enabled

### ISSUE THREAD

**Issue by libaineu2004** [pencil2d/pencil#1453] opened 2020-09-06 02:08 UTC
### Issue Summary
In debug mode, run the program, and then click Menu-Tools-Select to select a rectangle, and then the software will crash.

 

### Steps to reproduce
In debug mode, the exception will flash back, and then the breakpoint is in this function:
D:\\pencil-master\core_lib\src\interface\scribblearea.cpp
void ScribbleArea::paintEvent(QPaintEvent* event)   
{
......
......
 // outlines the frame of the viewport
#ifdef _DEBUG
    painter.setWorldMatrixEnabled(false);
    **painter.setPen(QPen(Qt::gray, 2));**
    painter.setBrush(Qt::NoBrush);
    painter.drawRect(QRect(0, 0, width(), height()));
#endif
}

 

### System Information
+ Pencil2D Version:
0.6.5

 

+ Operating System:
Win10 x64
Qt 5.12.9/MSVC2017 x64

 

+ RAM Size:
8GB

 

+ Graphics Tablet:

**Comment by scribblemaniac** [comment] 2020-09-06 06:46
I am unable to reproduce this on Ubuntu 20.04 with either master or v0.6.5 in a debug build (with _DEBUG manually defined because it's VS specific). I also can't think of any way that the line in question could fail, especially while the preceding one succeeds. Can you please provide more detailed reproduction steps? Does this happen whenever you change to the select tool or are there some preconditions to it? Does it crash if you switch to the select tool using the button in the Tools widget?

**Comment by libaineu2004** [comment] 2020-09-06 06:55
> I am unable to reproduce this on Ubuntu 20.04 with either master or v0.6.5 in a debug build (with _DEBUG manually defined because it's VS specific). I also can't think of any way that the line in question could fail, especially while the preceding one succeeds. Can you please provide more detailed reproduction steps? Does this happen whenever you change to the select tool or are there some preconditions to it? Does it crash if you switch to the select tool using the button in the Tools widget?

My development environment is windows. It's easy to reproduce the problem. You don't need to do anything. Just open the software, then select the "select button" on the toolbar, click on it, and drag a rectangle in the main view. The problem appears and it crashes.

**Comment by libaineu2004** [comment] 2020-09-06 06:59
The release version does not have this problem. Only debug.

**Comment by chchwy** [comment] 2020-09-06 08:02
Confirmed it happens to me. Windows 10 + Qt 5.12.9. the code is in a conditional macro `#ifdef _DEBUG`.

**Comment by scribblemaniac** [comment] 2020-09-06 17:14
> Just open the software, then select the "select button" on the toolbar, click on it, and drag a rectangle in the main view. The problem appears and it crashes.

Ah so the crash is not when switching to the select tool, but when actually trying to use it. Well in that case I can reproduce it as well, except that the debugger stops on the previous line which makes a lot more sense.

I have a fix for this, will push right away.

**Closed** 2020-09-06 17:21 UTC
Labels: Crash, Windows
