### ISSUE TITLE
Deleting Mistakely created layers. copy paste toooo doesnt work properly

### ISSUE THREAD

**Issue by Nep-Toodles** [pencil2d/pencil#1477] opened 2020-09-23 06:07 UTC
Ok so this is the footage gif which i recorded but please add it:

-1. please try copy pase
-2. please fix it like if i copy from a frame and paste it to another frame it does glithes and stuffs
-3.

 Improving ui and other systems.
forths keep it up its bettter than photoshop and Why do u have vector layer if u dont update it.

**Comment by J5lx** [comment] 2020-12-07 15:09
Hi, sorry for the wait. I tried copying from one frame to another, but I did not come across any glitches myself. Would you mind sharing more details about the issue you’re experiencing so we can try to narrow it down? For example:

- What kind of glitches did you experience? What did you expect to happen instead?
- Precisely which actions did you perform which led to the glitches? Did you copy the entire frame or from a selection? Did you paste straight onto the other frame or into a selection? Did you perform any other actions besides copying and pasting? Can you think of anything else which might have contributed to the glitches?
- Which operating system and which version of Pencil2D are you using? You can find this information in the menu in Help → About.

You also mentioned a GIF you recorded but it’s missing from your post, perhaps something went wrong with the upload. Can you try uploading it again?

> Why do u have vector layer if u dont update it.

Because the developers who originally created it have since moved on to other things and there is no one left who is actively working on it. We would like to improve it eventually, but it will take time. You seem to have some programming experience yourself, if you would like to work on it or know someone else who’d be interested, we’re always happy about a helping hand!

**Comment by scribblemaniac** [comment] 2021-01-06 05:21
Closing this issue as there is not enough details to determine what exactly the issue is here. Could be a duplicate of #1560.

**Closed by scribblemaniac** 2021-01-06 05:21 UTC
Labels: Bug Triage, More Info
