### ISSUE TITLE
[Enhancement] A way to turn Off/On the sound track

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#747] opened 2017-08-31 19:37 UTC
### --Issue Summary--
When playing back a sound track, it turns out that the _Hidden Layer Icon_ on the timeline is not used for Off/On the sound track but to hide its layer instead.

### --System Information--
+ Pencil2D Version:
Build 31August2017

+ Operating System:
WIN8.1 X 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

**Comment by Kaikogf** [comment] 2018-01-01 02:36
@chchwy 

This comment can be closed since the last build (31Dec2017) brings the on/off sound solution 👍 

By the way, I think, not sure though, that @CandyFace added a special mark for detecting sound tracks on the timeline. I would like to add something about it, but firstly does anyone knows where was it commented? Thanks

**Comment by CandyFace** [comment] 2018-01-05 17:31
Hmm I don't recall having implemented anything like that, could you give some more details about the "special mark" you recall having seen or heard?

**Comment by Kaikogf** [comment] 2018-01-07 03:19
My bad. I wrongly thought to have seen marks at the beginning of the sound tracks. 

What I saw was the Scrub of the "timeline" and the "Onion Skin of the Keyframes"

**Comment by Kaikogf** [comment] 2018-01-12 03:32
Closing this: the sound track has already a feature for ON/OFF the sound.
Thank you

**Comment by Jose-Moreno** [comment] 2018-01-12 03:40
@Kaikogf Please re-open this. I think this idea is helpful. While the "speaker" turns off all the sounds on the timeline, hiding the layer should, intuitevely only silence the sound(s) on said layer. Think of it as having a BGM and a few sfx, and you just want to focus on a particular sound effect, you hide the other layers and work only on the one that remains visible.

**Comment by chchwy** [comment] 2018-01-12 04:08
I'm reopening this issue.
Agree with @Jose-Moreno, it's good to have the ability to set every single sound layer on or off.

**Comment by CandyFace** [comment] 2018-01-12 12:34
This has now been implemented and integrated into the layer visibility system. When you hide a layer, the sound on that said layer will also be muted.

Awaiting confirmation that it works from other contributors, so we can close this.

**Comment by chchwy** [comment] 2018-01-12 12:48
the feature is available in the 12 Jan nightly build

**Comment by Kaikogf** [comment] 2018-01-13 03:48
@CandyFace 
This is for you since you was the one to implemented it:
Testing the sound layers on/off implementation.
Two issues:
A)- Testing with 2 sound tracks (on different layers): 
If we want to silence one of them it is not possible doing so while on playback mode. We have to stop playback and them select the specific track.
B)- The following issue must be related (I think) to the implementation of the on/off feature for sound layers :
I imported an animation of 1 layer with several frames. Hitting Start will playback the animation OK. 
But when stopping the animation and selecting a frame on the timeline, lets say #70, and hitting Start, 
the animation will not start meaning you will still see frame #70 on the canvas as an image, but after 
a while the timeline indicator will start moving and the animation is displayed on the canvas. 
I figured out that what really happened was that when hitting **_Start_** Pencil2D would start the animation all over from frame #1 (but hidden?) and them when it reached frame #70 it would display the animation normally.

When working with sound layers this issue shows differently: 
When playing back a sound track without interferences it will work OK. When stopping it and selecting a frame from the timeline (several frames after the first one) and hitting the Start button, it will not play it synchronized to the real soundtrack time. It is normally played as the number of frames where a little bit less than the original soundtrack. OK,  It is barely noticeable so and, as the issue above, the timeline scrub will not move immediately after hitting Start but taking some time to move while the soundtrack is heard !

**Comment by CandyFace** [comment] 2018-01-14 12:15
Thanks for testing @Kaikogf although issue A is not solely related to this, it's just the way the timeline works atm. nothing will be updated until you press stop.

as the for second issue, I'm not sure I understand the problem.. would you be able record a small video of the behaviour?

I'm pretty confident that the second issue is not caused by my implementation, so just to be sure. When you hide a layer now, is the sound muted?

**Comment by Jose-Moreno** [comment] 2018-01-14 15:58
@CandyFace @Kaikogf l I tested the second case and I can reproduce it when using sound (Jan 12th 2018). Basically when you import a sound, stop playback and attempt to resume at a later frame, the playback head will freeze for the amount of time you actually skipped forward counted from the first frame (in my test case it was about 4 seconds at 12fps, i stopped roughly at frame 12 and resumed at frame 48) and then resume it's playing speed, but once the sound stops playing since the playback lagged behind, it will not reach the end of the timeline, and thus it will repeat the sound last part until it reaches the timeline.

If it's ok I'll open a bug report on this case as a standalone problem. However I don't recall this issue was happening before 0.6 release.

**Comment by CandyFace** [comment] 2018-01-14 16:21
@Jose-Moreno Interesting, please try the Jan 11 build, which does not have this implementation. I'm still pretty confident that my PR has nothing to do with it, since it's not doing anything except skipping the layer if it's hidden.

**Comment by Jose-Moreno** [comment] 2018-01-14 16:28
@CandyFace Don't worry it wasn't your implementation, This happens on Jan 1st 2018 nightly build as well. Is working as intended only up to the Dec 20th 2018 build, I already submitted a new issue for this.

**Comment by CandyFace** [comment] 2018-01-14 16:33
I'm closing this, since it's already gone far off track from the actual issue.

**Closed by CandyFace** 2018-01-14 16:33 UTC
Labels: enhancement, sound

**Comment by Kaikogf** [comment] 2018-01-15 01:43
Glad @Jose-Moreno step forward ! 👍
