### ISSUE TITLE
My paint brush dose not work

### ISSUE THREAD

**Issue by NedicTeamNS** [pencil2d/pencil#670] opened 2017-05-14 11:43 UTC
###

### System Information
+ Pencil2D Version: Pencil2D 0.5.4 beta (for pc)

+ Operating System: Win 10 pro

+ RAM Size: 4GB

+ CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz 1.70GHz

+ Graphics Tablet: I'm drawing with my mouse and my laptop's touch screen, I do not use it.

---

**Comment by Jose-Moreno** [comment] 2017-05-14 19:14
@NedicTeamNS Hi, don't worry. Thank you for letting us know your system specs, it's easier to help like that :smile: 

So, you're using a really old version (0.5.4) I have to ask you to please try out a more recent "development" since it's more stable. The latest development build that has been released for Windows is from November 2016 and here's a **direct link for Windows 32bits systems**: 

https://drive.google.com/open?id=0BxdcdOiOmg-CWjF1TWRwY3RMUUE

Please try this version and report back if it fixed your issue. 

As a final note, there's a lot of other stuff that has been already been fixed since November (like getting better audio support and improving how the vector fill works) but developers are trying to push for a proper release so rest assured that they are working on it as hard as possible when they have spare time to volunteer for the project.

**Comment by CandyFace** [comment] 2017-05-20 16:20
@NedicTeamNS A recent build has become available for Windows 32/64 bit now, grab it here:
https://drive.google.com/drive/u/0/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by CandyFace** [comment] 2017-06-20 23:01
I'm closing this as OP used an old version of Pencil and the problem can't be reproduced in the latest build.

**Closed by CandyFace** 2017-06-20 23:01 UTC
