### ISSUE TITLE
Movie export is not working.

### ISSUE THREAD

**Issue by Nicole-Fuzbrain** [pencil2d/pencil#840] opened 2017-12-20 08:43 UTC
--Issue Summary--
When I attempt to export to my animations to movie (mp4, avi, gif), it acts like it's rendered the animation but it hasn't.

--Video or Image Reference--
https://youtu.be/I_BDhjfJ--s

--Steps to reproduce--
Attempt to export any length of frames into a .mp4, .gif, or .avi

--System Information--
+ Pencil2D Version:
Version: 0.6.0

+ Operating System:  32bit Ubuntu 16.04 LTS

+ RAM Size:
1GB or 1753MB

+ Graphics Tablet:
Wacom intuos small, CTL-480

**Comment by Kaikogf** [comment] 2018-01-07 03:52
Tested it here and got the same behaviour
 (last nightly build Pencil2D 04Jan2018)

**Comment by CandyFace** [comment] 2018-01-08 18:15
I can't reproduce this behaviour on Mac OS. @Kaikogf did you test on Linux too?

**Comment by chchwy** [comment] 2018-01-08 23:17
One thing I noticed is no file extension there.
The exporting file should be "key.gif" not just "key", probably it's the reason exporting not working.

**Comment by Kaikogf** [comment] 2018-01-11 02:32
@chchwy 
You can actually see the extension. Well, at least I can see it ;). File > ExportMovie > Export Movie window shows "File". If there are no name for the file > "Browse...", choose a name and after saving it you can check the extension will appear on the File path.
(not sure if this was what you was talking about) 

@CandyFace 
I tested it only in **_Windows 8.1 x 64bits_**. I build Pencil2D today (11JAN2018) and the issue is still there. I tested the export features and it is working fine with _Image Sequence_ so far

**Comment by chchwy** [comment] 2018-01-11 03:05
oh..I mean in the video, the export path is `/home/nicole/Desktop/key` without .gif and the end.
However, I'll check it again tonight.

**Comment by chchwy** [comment] 2018-01-11 11:26
Confirmed that the gif exporting is NOT working currently.
ffmpeg 3.4 is not able to generate gif palette, the error message is:
```
"[Parsed_palettegen_0 @ 00000264ac18e660] 206(+1) colors generated out of 206 colors; ratio=1.000000"
```
However, previous version ffmpeg 3.2 is working fine! Still looking into it...

**Comment by chchwy** [comment] 2018-01-11 11:35
I downloaded ffmpeg 3.4.1 and then the gif exporing is working again. So it's ffmpeg's issue. 

@Nicole-Fuzbrain Could you please check the ffmpeg version of your computer? Open terminal and type `ffmpeg` should tell that. 

I'm going to update ffmpeg version of windows nightly build as well.

**Comment by Nicole-Fuzbrain** [comment] 2018-01-16 05:15
Sorry for taking so long.
ffmpeg version 2.8.11-0ubuntu0.16.04.1

**Comment by scribblemaniac** [comment] 2018-01-16 05:53
> ffmpeg version 2.8.11-0ubuntu0.16.04.1

The version embedded in the 32-bit AppImage is this version as well.

**Comment by Kaikogf** [comment] 2018-04-03 03:16
@chchwy 
Would you mind to tell me where do I have to paste the ffmpeg 3.4.1 ?
Thanks

Pencil2D is still not able to export any file animation so far

**Comment by chchwy** [comment] 2018-04-03 03:22
I suppose you are using Windows.
Create a folder called `plugins` next to the pencil2d.exe and put the `ffmpeg.exe` in the plugins folder.

**Comment by Kaikogf** [comment] 2018-04-03 12:05
i downloaded the last version of ffmpeg.exe, still there is no sign of the exported movie. Using windows here.
The thing is that I am using Qt Creator t build Pencil (last build) but when I switched to the nightly build from 15Mar2018 Pencil2D do manage to export all file movies (but GIF)

One thing I noticed here, despite the animation has the camera zooming at the beginning, the exported video the camera is still.

**Comment by Jose-Moreno** [comment] 2018-06-16 16:47
@Nicole-Fuzbrain does this issue still happens or you on the latest nightly build? If not Nicole can you please close this issue? thanks!

**Comment by Jose-Moreno** [comment] 2018-08-17 15:57
**Closing**
---
_**Reason**_
After some deliberation the problem seems to have been tied with the FFMPEG version. Updating the plug-in version seems to correct the problem and newer nightly builds will contain an updated version of the plug-in.

As for reported issues with the GIF export or Camera tweening issues that were brought up, during that period the GIF export was being refactored and the camera tween issue was reported twice and solved in another commit.

**Closed by Jose-Moreno** 2018-08-17 15:57 UTC
Labels: bug, bug: file-export
