### ISSUE TITLE
Importing Sound On Mac Causes Crash

### ISSUE THREAD

**Issue by cjburkey01** [pencil2d/pencil#715] opened 2017-07-28 02:43 UTC
### --Issue Summary--
When importing a sound, Pencil2D crashes suddenly.

### --Results
I expect the program to create a sound layer and import the sound, but it crashes before either is done.

### --Steps to reproduce--
I've tried a new project, and dragging sound in causes crash immediately. Importing from the file menu. creates the channel and then crashes.

### --System Information--
+ Pencil2D Version:
0.5.4

+ Operating System:
macOS 10.12

+ RAM Size:
8GB

**Comment by Jose-Moreno** [comment] 2017-07-28 04:14
@cjburkey01 Hi, hmm I don't know how to say this but on the main website it's stated that Pencil2D has deprecated the use of version 0.5.4. So please use the latest development version which actually supports sound and has tons of fixes implemented ever since that old version. You can find the links on www.pencil2d.org landing page. But if you can't find it please visit the following link to get the builds: https://drive.google.com/drive/folders/0BxdcdOiOmg-CeVpTY294cXdLZ2c

There you'll find MAC OSX versions, and you can download the one from July 19th 2017. Please test that out and if you find it solves your issue please close this thread. Thanks :smile:

**Comment by CandyFace** [comment] 2017-07-28 13:43
Thanks for reporting, though as @Jose-Moreno says, there's a newer version available where this problem should have been fixed. Therefore i'm going to close this issue.

**Closed by CandyFace** 2017-07-28 13:43 UTC

**Comment by cjburkey01** [comment] 2017-07-28 17:19
That is what I ended up doing, and it works fine. The only issue is that (even with vector smoothing off and the vector layer disabled) brushes are extremely slow in this newer version. The slower I drag my mouse, the slower the brushes follow them.

**Comment by CandyFace** [comment] 2017-07-28 17:24
That sounds odd, what version of OS X are you using? I'm developing on a mac myself and have no such problem. I'm on OS X 10.11.6 myself. 

Would you be able to make a video or gif of the issue?

**Comment by Jose-Moreno** [comment] 2017-07-28 19:22
@CandyFace Actually someone on [facebook ](https://www.facebook.com/pencil2dsoft/posts/1855546264706073?comment_id=1857667054493994&reply_comment_id=1865963973664302&comment_tracking=%7B%22tn%22%3A%22R%22%7D) reported a similar issue with MAC OSX, claiming they were having a slowdown with their brushes. that was for July 11th version if i'm not mistaken, I suggested he use the one from July 19th and never got back to me on tha particular point. You can read the whole set of comments on this [thread](https://www.facebook.com/pencil2dsoft/posts/1855546264706073)

**Comment by scribblemaniac** [comment] 2017-07-28 19:41
I'm on OS X 10.12.5 and I also have no such issues, the brushes are very responsive in the latest versions. Just speculation here since I don't have a way to test this, but perhaps it is an issue with Retina displays? The higher resolution might make it slower to update.

**Comment by CandyFace** [comment] 2017-07-28 20:16
@scribblemaniac While your speculation could be true, it shouldn't be possible, given that only a very small buffer image is updated as you draw. The pixel density shouldn't make it harder to update that area. 

Without having a unit we can reproduce this on though, it's going to be difficult to figure out what's causing the delay. 

@cjburkey01 is your macbook one of the newer ones with retina display? if so, would you be able to change the resolution to say, 1080P and see if you can reproduce the said problem?

**Comment by cjburkey01** [comment] 2017-07-28 21:52
I'm using an iMac late 2013 MacOS 10.12.4. 2.9 GHz processor, 8 GB memory. Here's a gif: http://imgur.com/gbePnOw

Pencil2D Version: 2017-07-19_14:19:49

**Comment by CandyFace** [comment] 2017-07-28 22:29
Thanks for the information. So if my research is correct, it should be the 21.5 inches iMac with 1080p display, correct? if that's the case, then it's unlikely that the resolution is causing the problem. The problem looks very much like something we've had before, though I can't say whether they relate since a that was fixed a long time ago.

Are you drawing with a tablet or mouse? If the former, do you also experience lag with the mouse?

**Comment by cjburkey01** [comment] 2017-07-29 19:21
Yes, that information is correct, I use a mouse.
