### ISSUE TITLE
Layers using OS 10.10.5

### ISSUE THREAD

**Issue by dogenzip** [pencil2d/pencil#491] opened 2016-03-06 18:08 UTC
After upgrading Mac OS 10.10.5 many bugs: cannot create new layers in Pencil, cannot move layers to front/back, and error text always appears "drawing on an invisible layer". Completely deleted old version of Pencil and downloaded another version of Pencil and had the same result. 
Anyone else having this problem?  Any fixes or work-arounds?

**Comment by Jose-Moreno** [comment] 2016-03-06 23:06
@dogenzip Please let us know exactly which "new" version of Pencil2D you are using (go to Help Menu > About > Copy & Past version info) 

Also is MAC OS 10.10.5 by any chance the one called "El Capitan"? It seems this OS is the one that has the most issues out of all other MAC OS X versions.

**Comment by dogenzip** [comment] 2016-03-06 23:15
Hello,
Thank you so much for replying to my email.  I really miss not using Pencil.
I am using Yosemite OS 10.10.5.  Pencil worked OK on my previous operating system. Had I known Yosemite would not work with Pencil, I would not have upgraded.

The version of Pencil I am using is:


I would appreciate any suggestions you may have that would get Pencil working.

Paul-André



On Mar 6, 2016, at 3:06 PM, Morr <notifications@github.com> wrote:@dogenzip <https://github.com/dogenzip> Please let us know exactly which "new" version of Pencil2D you are using (go to Help Menu > About > Copy & Past version info) 
Also is MAC OS 10.10.5 by any chance the one called "El Capitan"? It seems this OS is the one that has the most issues out of all other MAC OS X versions.  I am using YOSEMITE, an earlier operating system.

**Comment by Jose-Moreno** [comment] 2016-03-06 23:25
@dogenzip For some reason the version information was not copied (or I can't see it at all in the message) don't worry anyway.

If you downloaded the package from our downloads section in the website then I'm pretty sure it won't work on any MAC OS X version past leopard since though is a version from 6 years ago, despite being the "stable" version

So I'll have to ask you to visit this Google Drive link that contains all the new, but experimental versions from the past 6 months.

https://drive.google.com/folderview?id=0BxdcdOiOmg-CcWhLazdKR1oydHM&usp=sharing#list

There please look for the **Pencil2D-mac-20160114.zip** file, and unzip it on a folder. Then find the executable file (I think it's a .dmg) and try it out.

**Comment by dogenzip** [comment] 2016-03-06 23:51
Hello Morr,
IT WORKED!  I download this program and tried it out.
Thank-you.
IS there any way I could contribute to your website, given I have no coding skills?
Paul-André

**Comment by dogenzip** [comment] 2016-03-07 00:11
Morr,
I regret to say that this version of Pencil also has serious problems.
1.  The line brush or pencil tool follows the cursor very slowly, leaving a empty space about 2” on my screen.  It is not possible draw accurately as a result.
2. The tools box view disappears from the screen every time I make a new mark or line and needs to be reset every time.  I tried pacing it outside of the animation fame and that seems to work better.
3. This version of Pencil will not open my previous Pencil animations, even though I tried all of the options provided.
Any suggestions?
Paul-André

**Comment by Jose-Moreno** [comment] 2016-03-07 01:13
@dogenzip 

**1)** I'm glad to see that the new versions are a step in the right direction, but sadly all versions are suffering from the "cursor lag" when drawing, apparently this has happened because of recent changes done to the Qt framework itself, as well as other programming tasks that were done previously. 

This problem was apparently more present in MAC OS X "El Capitan" as well (other Yosemite user haven't pointed out this particular problem) but, it's really happening all over the place in every version. 

For now our devs are looking into it and there are plans to work on it, but I can't give you an estimated time for it to become fixed.

**2)** The tool box problem sounds new to me. If this happens have you tried first minimizing and then "maximizing" the window to it's full state (using the -(minus) and + (plus) signs on the top right bar), if that doesn't work at all, have you tried going to the **View Menu > Reset Windows option** ? I'm afraid that if this problem persist I'll have to ask of you to take some screenshots when this problem occurs.

**3)** Note that Pencil files or .PCL (Pencil native file) files MUST be next to a folder that has the same name or they won't open in any version either past or future.

For example if you have a **pencil file** called **"my_file.PCL"** in the same location (i.e desktop) there has to be a **folder** called** "my_file.PCL.DATA" **which has several important elements inside. If you DON'T have these folders, I'm afraid the files won't open because the PCL file is like an "address" book, it only tels the Pencil "engine" to look for resources over that folder. If the resources are lost, Pencil won't open anything.

If you do have the folders intact with the PCL files outside of them, and you still can't open the PCL file properly, please collect and zip both PCL and folder and upload it so we can take a look at it.

As a friendly reminder please always try to open the files through Pencil >File > Open option, and not double clicking the file from your finder. Just in case.

**Comment by feeef** [comment] 2016-03-07 09:03
Hi @dogenzip, Thanks for your feedback!

Pencil2D is currently in a transitional state. The lack of development resources has made the previous official release (0.5.4), stand there for a very long time. Much too long actually. We are working on making the next version of Pencil2D to be working on top of the latest version of QT as well as the latest operation systems. It requires some effort and we are slowly but surely getting there.

We want Pencil2D to be lightweight, easy to use for everyone but still full featured. I personally want the Pencil2D's brush engine to be very responsive on old (slow) computer and I realize we are quite far from there with the current brush engine. For that matter, I plan to implement MyPaint as the main bitmap brush engine for Pencil2D.

@Jose-Moreno I was thinking of keeping this MyPaint update for after the 0.6 release but it seems that it is something we should think of having sooner as this lagging problem is making Pencil2D almost useless for many users.

I will add this bug to the 0.6 milestone and restart the "mypaint" branch on my repository.

**Comment by Jose-Moreno** [comment] 2016-03-07 17:36
@feeef I'm worried that you're having to bear almost all of the developing burden man. I think we should look into a way of getting someone to help you, but even though I put some notice on the facebook page requesting for developers, no one has even dared to contact us. If you can think of a friend or anyone that can help you out, please let them know.

Another difficulty I've encountered through the "tumblr" blog, is that many MAC users are having tremendous amount of problems with the software particularly with the 15th JAN 2016 Nightly Build. That damn OSX update screwed up everything, I'm even beginning to think it's Qt's fault. 

Also since I can't build new Nightly Builds for neither WIN nor MAC, I don't know what to tell them, or how to help further once the problem is related to the binaries. Most are understanding, but a few angsty teenagers are getting on my nerves.

To be honest so far Pencil2D has a bad reputation spread-out. I've been trying to output great work from exceptional people that have used Pencil2D in spite of it's flaws, but the app needs to redeem itself to the larger userbase. 

So far Drawing, Exporting, Corrupted or Unusable files due to the PCL vs PCLX file format confusion AND the fact that all the data is stored outside of the PCL file, as well as Crashing / stability Issues are the top 4 problems I encounter time and time again when browsing.

I don't know if we could like ask for donations to pay you at least one day of full work or something on Pencil2D. Since we're not a "foundation" but rather a "volunteer collective" we are limited to what as a group we can do. I can't go and fund Pencil2D by myself either because exchanging my currency to EUR would dry me up, although maybe if it's one day we could find a way. I'm just thinking out loud, but this is the time to think about it. We are neck deep here, so we either get out of the water or drown completely hah.

Anyway, thank you for your resilience, it's inspirational that you continue to help the project out like this. :+1:

**Comment by dogenzip** [comment] 2016-03-07 17:57
I agree with your email.
One or two people cannot bear the burden of this task. 
I would be willing to contribute $$$ to get Pencil up and running for OS users. 
Is there a way this could be done?

**Comment by Jose-Moreno** [comment] 2016-03-07 18:38
@dogenzip Right now our volunteering efforts are fragmented and we don't really know how many people will be willing to help, or even accept money to develop this software.

I'd have to think of a way to do this with as much transparency as possible for both the users as well as our developers. I'd be willing to take care of it, but I can't appoint myself to do such a task as easily because despite my presence on the website and my willingness to help the project, no body really knows me so even I would be skeptical at first to hand me such task. So we would need to at least guarantee that the money that anyone donates will be actually spent in development.

There are just too many things that have to be discussed for that to happen. I'll have to make a plan and propose it to the entire user base through the website forum and through a massive announcement. But right now  I'm afraid I don't know when that could be happening.

If you want to help us out right now, try reaching out to friends or colleagues that know how to code in C++ that want to learn how to use the Qt framework or that already know how. That would be definitely be important. Maybe they have friends as well or acquaintances that would be interested. This is a project for all animators out there, not just those who work on it. Thank you once more for your interest in Pencil2D :smile:

**Comment by feeef** [comment] 2016-03-07 19:07
Thanks a lot for proposing your help!
Don't worry about Pencil's bad reputation. The users are aware that it is still under development and not even at version 1.0. With time, we will get it there! ;)

Being alone to do this mypaint integration is not a problem at all. setting up the base of the integration is a bit tricky but as soon as I will have done that, things will be quite easy to implement. Honestly, I'd rather implement it by myself  because handling collaborative development and communication will be even more effort for this kind of task.

There are still some annoying problems with Windows and MacOS but the app is getting better and better anyway. I have started animating for my clients with Pencil2D (only a few things) so the state of the software is not too bad. We fix things step by step and we will end up with a very powerful software at the end. I am confident about it. It is free software so the project will never be shut down because of some private interest. As long as there is 1 person who wants Pencil2D to grow, Pencil2D will grow. We just need to be patient.

I am also confident that when we will get to a stable version with the current features, we will get a lot more interest and we can start building a community. At this point, Pencil2D can become a foundation and start doing crowd-funding to finance its development. This is the way to go to have a serious business model. We need a community first. It is what I look forward to anyway. It can happen quite soon actually. We can get to this stable version some time this year.

Until then, we will have to keep tracking bugs, keep debugging, improving the software and most of all, we will have to be patient! ;)

**Comment by dogenzip** [comment] 2016-03-09 00:47
Hello François,
Thanks for the information.
Please let me know if and when funding through crowdsourcing e. g. kickstarter, will take place to revise Pencil so that it can regain wide use among OS 10.10.5 users and others.  I need to get some animations out the door and trying to decide whether to use Synfig which appears to have a steep learning curve.
Cordially,
Paul-André

**Comment by feeef** [comment] 2016-03-09 09:09
Thanks @dogenzip ,
While waiting for the stable release to happen, what you can do, if you have a spare computer that doesn't do much, is install Debian Stretch (testing) to it. Debian Stretch is my daily OS and even if it is not the stable release, it is very stable. I just noticed that whoever maintains the Pencil2D package on Debian has updated it with our latest nightly build. This is a very good news because it means we are being followed by the FOSS community and Debian wishes to include our upcoming stable version to there next stable release.

As I had very limited latency problems on Debian, it could be an alternative for you to start using it right now. You could even try it on a virtual machine (virtualbox)

Once Debian is installed just open the terminal as root and type : apt install pencil2d

**Comment by dogenzip** [comment] 2016-03-12 02:26
Hello, Thank-you for these suggestions.

I may try to connect a auxiliary hardest with firewire to my Mac, load an older OS which worked with Pencil, download another Pencil software and then open this operating system when the MacMini turns on.   Alternative would be to use Debian as the OS.

Also I downloaded Pencil (latest version) onto Windows, and it works w/o mouse tracking delay and layers, etc but it will not save the animation in any video format.  Nothing happens.

I would appreciate any feedback you may be able to provide.

Cordially,
Paul-André

**Comment by dogenzip** [comment] 2016-03-12 02:30
Hello Francois, 
Thank-you for these suggestions.
> 
> I may try to connect a auxiliary hard drive with firewire to my Mac, load an older OS which worked with Pencil, download another Pencil software and then open this operating system when the MacMini turns on.   Alternative would be to use Debian as the OS.
> 
> Also I downloaded Pencil (latest version) onto Windows, and it works w/o mouse tracking delay and layers, etc but it will not save the animation in any video format.  Nothing happens.
> 
> I would appreciate any feedback you may be able to provide.
> 
> Cordially,
> Paul-André


> 
>

**Comment by Tom3141** [comment] 2016-03-12 04:11
I was following this thread over the last couple of day.   Perhaps one way to get more developers working on pencil2d could be through google summer of code.   It's too late for 2016 but there's always next year. https://summerofcode.withgoogle.com/

**Comment by Jose-Moreno** [comment] 2016-03-12 04:34
@Tom3141 Thanks a lot for your interest Tom. Google Summer of Code is a great choice, however it's aimed towards organizations that have at least an established core team. Students join the project with proposals but they HAVE to be mentored by the software's core team in order to develop the features. Right now Pencil2D is, to put it bluntly, a band of misfits. We just don't qualify for their requirements, as most of us are merely volunteers who need the program for their own endeavours.

However if we could manage to actually prove to the open source world that Pencil2D is still one-of-a-kind piece of software, as it's mere concept has always suggested, we might get some development interest. Yet no matter how I look at it, we need to get a working program for that to happen, as well as talented artists that use the program. I've been thinking to contact a public university, to see if maybe they can help us. For example the Paris-8 began to replace their Adobe software for open-source apps. As well as to help develop occasionally Natron (which is french software). Pencil originally was developed mainly by Frenchman Pascal Naidon, but I wonder if they'd be interested in funding this software, or at least using it to teach hand drawn animation :+1:  We need to deliver positive results for anything to happen in the near future.

We will see how things unfold. Thank you for your contribution and suggestions!

**Comment by feeef** [comment] 2016-03-12 08:44
@degenzip, we still didn't finish to implement video export so this feature has been temporarily removed from the software.
A good practice is to export as image seqences and use an external compositing software.

Here is my workflow : I do my animations with pencil, then I export them as PNG image sequences with transparency an do my compositing on another software. I use blender but you can use any other compositing software, which will have much better compositing features than Pencil2D. I do this for each shot and edit everything with a video editor.

By transfering my footage as image sequences I don't lose any quality while having the ability to handle transparency.

**Comment by chchwy** [comment] 2017-11-06 06:26
Hi @dogenzip,
If you are still interested in Pencil2D, please try our recent nightly build: http://pencil2d.github.io/download/. It has been improved and got a bunch of bug fixes.

I believe the issues you mentioned 1. slow stroke 2. toolbox disappearing have been fixed.
And any problem with opening an old pencil file, please send it to me chchwy (at) gmail.com I will take a look at it.

Feel free to open another issue if something still goes wrong. I'm gonna to close this :)

**Closed by chchwy** 2017-11-06 06:26 UTC
