### ISSUE TITLE
Enabling "Dotted Cursor" in preferences crashes Pencil2d.

### ISSUE THREAD

**Issue by tofarley** [pencil2d/pencil#515] opened 2016-06-17 17:13 UTC
OS: Mac OS 10.11.5 El Capitan
Pencil2d version: build from current master HEAD 22f9a7c 
Steps to reproduce:
- Launch Pencil2d.
- Select the Pencil2d menu -> Preferences
- Choose The "Dotted Cursor" Checkbox.
  Crash.

I don't need this feature, in fact I only clicked on it to see what it did. But I didn't see another report, so I figured I'd leave a quick note here.

**Comment by hankofficer** [comment] 2016-06-18 21:41
I can confirm this in Debug mode. I'm on Windows 10.

**Comment by Spark01** [comment] 2017-11-26 17:10
This seems to be fixed. Not sure exactly when it got fixed but I see no problem with it in the code and it's not crashing for me. Can someone confirm this is fixed before we close it?

**Comment by CandyFace** [comment] 2017-11-26 17:13
I believe it was fixed in https://github.com/pencil2d/pencil/commit/bd9f9cba17fb7dc0ce5657acb3b7424efa8c1fe2

tested and confirmed fixed. Closing.

**Closed by CandyFace** 2017-11-26 17:13 UTC
Labels: bug

**Comment by BriannaRice** [comment] 2019-04-19 13:14
I did this and it didn't work. Mine is doing a thing where I draw and it makes a dotted line and it won't let me erase it.

**Comment by Jose-Moreno** [comment] 2019-04-19 20:52
@BriannaRice Hi. This issue seems to be unrelated to yours so whenever possible please either open a new issue or ask for a bug review on the forum at http://discuss.pencil2d.org

That said, it's important that you use the latest version of Pencil2D straight from the official website. the latest one is 0.6.3

There is indeed an issue on Windows machines where sometimes there is an issue with how the canvas updates, but don't worry as this won't show up in the final animation. I know it's a bit annoying but we're aware of this problem.

Can you tell us however some additional information about your computer?:

1. What operating system do you have
2. Does your issue keeps happening with the latest version
3. Does your issue happens with a mouse too? or only with a graphics tablet?
4. What is the brand of your graphics tablet? e.g Wacom Intuos 5, Huion 410, etc
5. If your go to EDIT > PREFERENCES > GENERAL > And turn off the "dotted cursors" option, does this keep happening with the tool cursors on? can you try to turn those off as well?
