### ISSUE TITLE
The eraser bug

### ISSUE THREAD

**Issue by TheAnimater** [pencil2d/pencil#1697] opened 2022-02-21 18:47 UTC
the eraser does nothing i keep reopening. when i try to use it it doesn't erase
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by scribblemaniac** [comment] 2022-03-02 21:56
Hi, first of all this is the developer forum where you are meant to place tickets on confirmed issues.

We have a template for these issues that is very specific. You are assumed to fill the form sections at least to describe the problem, because we can't know what the problem is if you don't accurately say what the problem is.

We will need much more information if we can be expected to know what your actual issue is. Are you using an outdated version of Pencil2D? How are you switching to the eraser? What are you trying to erase? Do you have the layer with the content you are trying to erase selected? What is the type of that layer? What are the settings for your eraser? A very high feather value can make it seem like it is not erasing.

So please, if you want help you need to be more specific. We have a policy of waiting for 2 weeks before closing low effort tickets so we will wait for you to describe your problem better, otherwise we will close this issue and I'll have to ask to gather your thoughts and post in the forum instead which is also active https://discuss.pencil2d.org/

**Closed** 2022-04-16 13:49 UTC
Labels: More Info, Eraser
