### ISSUE TITLE
I cant save my animations

### ISSUE THREAD

**Issue by KRZYK1029** [pencil2d/pencil#1171] opened 2019-02-09 23:42 UTC
i recently just got the newest version of pencil2d thinking that it would fix the issue but it still has this issue i don't know what to do at this point and i would like some help.

(btw im new to github so if i messed anything up thats my fault)

System Info
                   v
Pencil version: 0.6.2 (stable)
Build ABI: i386-little_endian-ilp32
Kernel: winnt, 10.0.17134
Operating System: Windows 10 (10.0)
Tablet:none
RAM Size: 1 gigabyte (GB) for 32-bit or 2 GB for 64-bit (i think)

Actual Results: it would stop saving and display an error message.

Expected Results: i was hoping it would save successfully with the newest version of pencil.

Video and Image Reference.

video: https://youtu.be/ezGaQbi2llY

![bandicam 2019-02-10 07-17-16-056](https://user-images.githubusercontent.com/47487421/52527527-db11b280-2d04-11e9-9798-c30d4aa5dd48.png)

(thanks for your help)

**Comment by Jose-Moreno** [comment] 2019-02-10 02:41
@KRZYK1029 Hi. This is very odd indeed, this issue was fixed before. For now is it possible that you share the file that is causing you trouble?

Also in these cases please test out the latest development version instead of the download version. Development versions are updated regularly with fixes so if this particular problem was already fixed or not it can help to pin down the real problem and solve it as soon as it is possible.

This is the direct link to the windows 64 bits nightly build for **February 5th 2019**: https://drive.google.com/open?id=1juDKIkv1F8fuNruGBwauA_y-7UNWibis in case you can test it out in another computer however It seems you have a 32 bit version of Windows 10, and for now we have to wait for a developer to help us with this since there are no 32bit dev builds.

I'll tag a developer that has handled these errors before so once you share the file they can take a look at it.

**Comment by Jose-Moreno** [comment] 2019-02-10 02:43
@chchwy Can you take a look at this issue? It seems related to the file manager issue that you fixed before, but this time happening in a Windows 10 32 bit build release and the user is using 0.6.2. I've already asked the user to submit the file that's causing the issue, so hopefully you can find out what's happening when you have some time. Thanks in advance :+1:

**Comment by scribblemaniac** [comment] 2019-02-10 06:32
@KRZYK1029 We'll look into the issue, but in the mean time in addition to trying the nightly build as already suggested, you may also have more luck saving as a .pcl file rather than a .pclx file. You can change this in the file selection dialog that comes up when you try to save and then you may need to explicitly adding ".pcl" to the end of your filename too.

**Comment by KRZYK1029** [comment] 2019-02-10 14:42
ye hey i downloaded the 64 bit build but it has the same problem and i
can't do anything about it.

**Comment by Jose-Moreno** [comment] 2019-02-11 05:39
@KRZYK1029 Hi, in that case please, if possible, share the problem file via google drive, dropbox or wetransfer.com with a direct link to it so developers can test it and get to the core of the issue, otherwise reproducing this problem currently seems to be impossible for us since we've tried saving and loading several times with both dev builds and download versions and this specific issue is not happening, so if your file has a particular code embedded that might be causing the issue to occur, it would help a lot to get the problem investigated and hopefully solved. Thanks in advance.

**Comment by Jose-Moreno** [comment] 2020-08-28 05:21
@KRZYK1029 Hey. It's been a while. I'm sure you don't even use Pencil2D anymore, but we're wondering if you still have this issue? Currently a new version is released and I can't reproduce this problem no matter how I try to break the program. If you're able please test this and let us know if this issue has finally been fixed or not for you. Cheers.

**Comment by J5lx** [comment] 2022-06-05 21:15
Hi, since we haven’t heard back from you I’m going to assume that you are no longer having this problem and I’ll close this issue. If you are still having trouble, please let us know and we’ll reopen it.

**Closed by J5lx** 2022-06-05 21:15 UTC
Labels: Bug, File Save, No reply
