### ISSUE TITLE
[BUG] Pencil2D crashes when attempting to modify a non-existing first (key)frame

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#950] opened 2018-04-20 07:55 UTC
### --Issue Summary--

Pencil2D crashes when attempting to modify a non-existing first (key)frame.

### --Actual Results--

Pencil2D crashes.

### --Expected Results--

Whatever is action is performed should be ignored.

### --Video or Image Reference--

![image](https://user-images.githubusercontent.com/11491024/39036787-e63d39aa-447e-11e8-8f9b-09136cb069fe.png)
Attempting to use a tool on the first frame like so will cause the program to crash

### --Steps to reproduce--

1. Create a new project. (This happens in existing projects too.)
2. Move the first frame of either the Bitmap layer or Vector layer to another position. (The Camera layer doesn't seem to have this problem).
3. Use a tool on the canvas. (Pencil, selection, etc.)

### --System Information--
+ Pencil2D Version:

Version: 0.6.1.1

+ Operating System:

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64

+ RAM Size:

8GB

+ Graphics Tablet:

WACOM Intuos CTL-490

**Comment by Jose-Moreno** [comment] 2018-05-28 15:49
@CandyFace I have to add some details. It was reported today that exporting under these conditions also trigger a crash. So If you move the first frame forward and try to export a movie like that, it will trigger the crash as well.

**Comment by CandyFace** [comment] 2018-05-28 16:49
@Jose-Moreno Yup I can see that, looking into it currently.

**Comment by CandyFace** [comment] 2018-05-29 18:25
The mentioned crash when exporting has been fixed now too in #984

**Comment by CandyFace** [comment] 2018-06-01 05:34
Fix will be available in next nightly build, so i'm closing this.

**Comment by ryyharris** [comment] 2019-04-15 21:42
I found that when I 
1.  Create another keyframe in the vector layer
2. Delete the first keyframe
3. Try and draw when at the first keyframe
The program still crashes. It does not when I do the same steps with the bitmap layer

**Comment by Jose-Moreno** [comment] 2019-04-15 21:50
@ryyharris I can confirm your steps lead to an immediate crash. Thank you for reporting! I'll reopen this issue in lieu of your findings.

@CandyFace Since you fixed this last time, could you take a look at the same issue on the vector layer when you have a chance? Thanks

The bug happens on vector layers in the latest version.
Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by CandyFace** [comment] 2019-04-16 16:08
Yea I'll look into it.

**Closed** 2019-05-02 23:34 UTC
Labels: bug
