### ISSUE TITLE
Automatic zoom issue 

### ISSUE THREAD

**Issue by Kimlir** [pencil2d/pencil#1556] opened 2020-12-19 11:57 UTC
###Automatic zooming
Hello to everyone! 

I am using a Chromebook Asus C423N on which i have installed pencil2D through the Linux interface. 

I am just starting to use Pencil2D so forgive me if I ask something which seems very obvious to you all :). 
When i have created several frames on the Bitmap layer, on which I have drawn, I try to move from one to another, the zooming changes on its own. It actually zooms in, every time I move to another frame. Do you think its a shortcut issue, or a trackpad issue?
 
Would you have any idea on how to solve this? 

Thank you so much for taking the time to read me and think about my problem! 
Have a good day ya all! 

Caroline.

**Comment by Jose-Moreno** [comment] 2020-12-20 05:33
@Kimlir Hi Caroline. While this may be a bug, it is important that we try something else first. From your description it could be that the camera layer (yellow colored track) has different keyframes created and the zoom or scale factor is different in each one. So first check your camera layer for any extra frames created after the first one, and reset the zoom scale by selecting the camera layer and pressing CTRL + H or going to View > Zoom > 100%

Another possible issue is that the keyboard shortcut for zooming could be certainly duplicated for your system. To look into this possibility go to Edit > Preferences > Shortcuts > Zoom In / Zoom Out and then check your graphics tablet if you have one to see if the device has similar shortcuts mapped.

Your last suggestion of a problem regarding the trackpad could also be a possibility but for this I'm afraid I don't have any suggestion. If this doesn't happen when using a mouse or a graphics tablet, it could very well be a software (drivers) or even a hardware issue and as far as I know Pencil2D only works with mouse pointers and graphic tablets, so unless the trackpad is acting as a mouse it could be having a compatibility issue with your Linux distribution, but that's mere speculation on my part.

Another possible issue that occurs to me which may seem like it's zooming or popping, but it's not, is an actual bug where the drawings are not updated properly when you traverse through the timeline, the workaround right now is to select another layer and then the one with your drawings. This will be fixed in an upcoming patch which we hope to release before the end of january

Lastly we don't really support Chromebooks, but I've heard positive account on users interfacing through Linux, however this is quite honestly unexplored terrain for us. If you continue to have this issue, can you describe a set of instructions that will always get you to experience this problem? Perhaps that way we can try to reproduce it and find the issue even without owning a chromebook.

Let us know how it goes.

**Comment by J5lx** [comment] 2022-06-05 21:17
Hi, since we haven’t heard back from you, I’m closing this issue. If you’re still having this problem, please let us know and we’ll reopen it.

**Closed by J5lx** 2022-06-05 21:17 UTC
Labels: Bug Triage, More Info, No reply
