### ISSUE TITLE
I think my process has not been saved...

### ISSUE THREAD

**Issue by FreddGamePlay** [pencil2d/pencil#977] opened 2018-05-22 13:35 UTC
This is what I get : 

Error Display : 
Title: Internal failure
Description: An internal fault occurred. The file may not have been recorded # correctly.

System Info : 
Pencil version: 0.6.1.1
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.16299
Product name: Windows 10 (10.0)

**Comment by Jose-Moreno** [comment] 2018-05-22 14:36
@FreddGamePlay Sorry to hear you're having this issue. thank you for reporting we'll be investigating this as soon as possible.

**Comment by Jose-Moreno** [comment] 2018-05-22 14:40
@chchwy @CandyFace @scribblemaniac Ok, this is like the third time we've had similar reports to this. I dare say the save manager is still broken, but it seems to be specific to Windows 10, since all the reports I've seen are coming from that platform. A similar report was issues on the forum almost a month ago:

https://discuss.pencil2d.org/t/internal-error-cant-save-for-the-3rd-time/2596

I believe one of you mentioned before that there were some pending fixes to be applied to the save manager after it was patched for 0.6.1, but hopefully this is not something that's beyond the scope of the upcoming maintenance version.

**Comment by chchwy** [comment] 2018-05-22 23:45
Hi @FreddGamePlay 
Sorry to hear that. Just double check with you, can you tell us what happened after you see the error message? Is the file no longer opened? Or you can open it but something is missing?

Usually, the error message comes with more details, not just an "Internal error". It would be extremely helpful if you can tell me all those details.

**Comment by chchwy** [comment] 2018-05-22 23:59
@Jose-Moreno I will go through the save manager and put more debug details to make sure we can get enough information to work on it.

**Comment by Jose-Moreno** [comment] 2018-05-23 00:04
@chchwy That would be great, thank you! I still think it must have something to do with Windows 10, since all of the reports have ocurred there, but hopefully with more thorough debug details we can find the cause of this :slightly_smiling_face:

**Comment by Jose-Moreno** [comment] 2018-05-26 21:56
@0-name-0 Gosh, this thing is getting worse by the minute. First of all thank you for your report. We're sorry to hear you've lost a whole lot of work :slightly_frowning_face: If you see the temp working folder will contain your most recent work, so even if you can't save you would be able to backup the RAW drawings from that folder before closing the software. The team devs are looking into this issue at the moment as they acknowledge that this is a very strange and critical issue.

I want to mention one thing as well. When using Pencil2D do you have administrative rights for your computer? Can you try to open, work and save a new test project with Pencil2D by using the "run as administrator" command and then tell us if that works initially for you in a way that it won't make you lose work or not? I know it's bothersome to ask since you must have better things to do, but to me this problems seems more and ore related to how Windows 10 does things regarding permissions. This would be for sure an important test meanwhile the developers find a solution to this problem.

**Comment by 0-name-0** [comment] 2018-05-26 22:47
@Jose-Moreno Thank you for the advice! I will check the folder and see if I can recover anything :D
Anyway, I'm pretty sure I have administrative rights on this computer, but the account i'm using isn't the original one, I actually got this computer from someone else. As for the error, I tried the "run as administrator" command and made/saved a short animation. Sadly, the same error still came up. 

One more thing, I had been using the 0.6.1 version since may 1st, and it had been working really well. About 1 or 2 days ago, my computer had a big update, and there were a few differences from the past "version" of windows 10. I hadn't opened pencil2d after the update until now. I don't know if that had anything to do with the error, but I hope it helps!

**Comment by 0-name-0** [comment] 2018-05-27 18:45
@Jose-Moreno Hi again, I'm not completely sure but I think I found the problem... I was working on something this morning and needed to download something to my USB. When I tried downloading it, an error came up saying there wasn't enough space left. Sure enough, my USB was out of space. The thing is, I usually save my animations onto my USB. So I tried deleting stuff I didn't really need and got quite a bit of space, and then tried making a short animation, and it saved correctly. As for the animation I was working on, it won't let me open the file anymore. I'm not sure why, but my guess is that it happened because I was trying to save it so many times. Either way, I hope this was helpful!

**Comment by Jose-Moreno** [comment] 2018-05-27 19:03
@0-name-0 Thank you once more for taking these risk in order to verify the information. It seems that Windows 10 is the culprit if we base our observations on how every report comes from that OS. It's also quite possible that there is an issue with read & write permissions that was triggered by the last update you mentioned since the reports have been very close to each other by mere days. Either way I'm hoping  that there can be a counter measure devised for this issue that won't allow file corruption and will allow a clean backup in case things go wrong. Thanks again for your time!

**Comment by Jose-Moreno** [comment] 2018-06-06 00:40
@0-name-0 @FreddGamePlay Hey people. Today a new development build was made with a fix for this problem. If you don't mind could you test it out with a disposable file and let us know if this has been fixed for you or not? Visit http://pencil2d.org/download#nightlybuild and look for the June 5th 2018 nightly build. Thanks :slightly_smiling_face:

**Comment by 0-name-0** [comment] 2018-06-09 01:07
Hi! sorry for not getting back to you sooner, i was kinda busy 😅 I tested it out a few minutes ago (with audio), and it saved normally :D
Thank you for fixing the problem!!

**Comment by Jose-Moreno** [comment] 2018-06-14 04:05
@chchwy I think we can close this one and those issues that are related to it.

**Comment by chchwy** [comment] 2018-06-14 04:42
@Jose-Moreno cool, i'm closing this.

@0-name-0 Thanks for reporting!

**Closed by chchwy** 2018-06-14 04:42 UTC
Labels: bug, file-save
