### ISSUE TITLE
Latest and Previous monthly build for Pencil2d fails to launch on OS X 10.10

### ISSUE THREAD

**Issue by paranoidfactoid** [pencil2d/pencil#668] opened 2017-05-13 02:17 UTC
### --Issue Summary--

Download Application from main site. Attempt to launch. It fails to start with the message:

"Pencil2D cannot be opened because of a problem. Check with the developer to make sure Pencil2D works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X."

Please note, if I open package contents and attempt to start the application from the command line, here is the error message I get: 

/Volumes/User\ Data/XXXXX/Downloads/Pencil2D\ 2/Pencil2D.app/Contents/MacOS/Pencil2D ; exit;
dyld: Library not loaded: /usr/local/Cellar/qt@5.7/5.7.1/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Volumes/User Data/XXXXX/Downloads/Pencil2D 2/Pencil2D.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
Trace/BPT trap: 5
logout

Note that the QT framework libs are in the Frameworks directory for the application build. So this is probably a build bug, referencing library paths on the build host instead of within the package contents. 

### --Actual Results

I expected the application to start. It did not. 

### --Expected Results--

It should have started. 

### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ CPU:

+ Graphics Tablet:

---

**Comment by paranoidfactoid** [comment] 2017-05-13 07:15
FYI: The last build version that launches properly is Nov 8, 2016.

**Comment by CandyFace** [comment] 2017-05-13 07:30
Hmm it looks like some of my latest to the travis file has been reverted... that is probably the reason this is happening. 

working on a fix, coming up asap.

**Comment by CandyFace** [comment] 2017-05-13 08:00
Fix is up now, weird though that even the builds that worked prior to some of the recent changes has been removed too. I'll remove the broken nightly builds from the google drive folder.

**Comment by paranoidfactoid** [comment] 2017-05-13 15:42
Hi. Thanks for such a quick response. However, I downloaded the latest build you posted and still have exactly the same problem (with exactly the same error messages). Macs expect the package to self contain all libs and runtime dependencies. Not sure what your build environment looks like, but I'd guess there's a Makefile here with a bad path. Probably autogenerated as part of your crossplatform build system.

**Comment by CandyFace** [comment] 2017-05-13 15:54
Well the PR hasn't been merged yet, so there's no new build with the applied fix. The thing is MacdeployQt is pretty broken, so you have to do a bunch of things yourself to fix it.

If you grab the source code from my branch https://github.com/CandyFace/pencil/tree/travis-regression-fix
then after you've compiled the pencil2d, you have to do the following:
* Apply the macdeployqt, by entering this in the terminal:
`macdeployqt Path/to/Pencil2D.app`
* grab the macdeployqtfix from here:
https://github.com/aurelien-rainone/macdeployqtfix/archive/master.zip
* run the following in the terminal (this requires python 3.x):
`python Path/to/macdeployqtfix-master/macdeployqtfix.py path/to/pencil2D.app/Contents/MacOS/Pencil2D /path/to/qt `(we use 5.7.1 here)

If everything goes accordingly, then it should work.

**Closed** 2017-05-14 04:33 UTC
